// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    public partial class Advertisement
    {
        [Key]
        [StringLength(13)]
        public string SerialID { get; set; }
        [Key]
        [StringLength(3)]
        public string Item { get; set; }
        [Required]
        [StringLength(8)]
        public string StoreID { get; set; }
        [Required]
        [StringLength(8)]
        public string Months { get; set; }
        public double Amount { get; set; }
        [Required]
        [StringLength(250)]
        public string Remark { get; set; }
        [Required]
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [Required]
        [StringLength(4)]
        public string ChangePerson { get; set; }
    }
}