// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    public partial class AgeSegment
    {
        [Key]
        [StringLength(10)]
        public string SegID { get; set; }
        [StringLength(50)]
        public string SegName { get; set; }
        [StringLength(15)]
        public string BeginAge { get; set; }
        [StringLength(15)]
        public string EndAge { get; set; }
        [StringLength(99)]
        public string Remark { get; set; }
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [StringLength(5)]
        public string ChangePerson { get; set; }
    }
}