// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Keyless]
    public partial class AGQ_Detail
    {
        [Required]
        [StringLength(20)]
        public string PjtID { get; set; }
        [Required]
        [StringLength(50)]
        public string Type { get; set; }
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [StringLength(10)]
        public string ChangePerson { get; set; }
        [StringLength(10)]
        public string Item { get; set; }
        [StringLength(20)]
        public string Store { get; set; }
        [StringLength(50)]
        public string ClientShort { get; set; }
        [StringLength(20)]
        public string GoodID { get; set; }
        [StringLength(10)]
        public string SizeNo { get; set; }
        [StringLength(10)]
        public string SizePosition { get; set; }
        [StringLength(10)]
        public string NeedQty { get; set; }
        [StringLength(10)]
        public string TotQty { get; set; }
        [StringLength(10)]
        public string StorageQty { get; set; }
        [StringLength(10)]
        public string Num { get; set; }
        [StringLength(10)]
        public string StorageQtyT { get; set; }
        [StringLength(10)]
        public string StorageQtyO { get; set; }
        [StringLength(10)]
        public string TakeQtyNew { get; set; }
        [StringLength(8)]
        public string SizeName { get; set; }
        public double? NoDealNum { get; set; }
        public double? SellAmt { get; set; }
        public double? SellNum { get; set; }
        public double? FactNum { get; set; }
        public double? MidNum { get; set; }
        public double? PreTranNum { get; set; }
        public double? TheoryNum { get; set; }
        public double? ZCNum { get; set; }
        public double? BuNum { get; set; }
        public double? FactNum_New { get; set; }
        public double? BuNum_New { get; set; }
        [StringLength(8)]
        public string KCFlag { get; set; }
        public double? WeekQty { get; set; }
        public double? LSellQty { get; set; }
        public double? StorageQty_ZC { get; set; }
        public double? StorageQty_Ori { get; set; }
        public double? SafeNum { get; set; }
        public double? SellRate { get; set; }
    }
}