// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Keyless]
    public partial class AGQ_Project
    {
        [Required]
        [StringLength(20)]
        public string PjtID { get; set; }
        [Required]
        [StringLength(50)]
        public string Type { get; set; }
        [StringLength(1000)]
        public string Season { get; set; }
        [StringLength(1000)]
        public string Brand { get; set; }
        [StringLength(1000)]
        public string Store { get; set; }
        [StringLength(1000)]
        public string Sort02 { get; set; }
        [Column(TypeName = "text")]
        public string GoodID { get; set; }
        [StringLength(10)]
        public string BaseStore { get; set; }
        [StringLength(8)]
        public string SBaseDate { get; set; }
        [StringLength(8)]
        public string EBaseDate { get; set; }
        [Column(TypeName = "text")]
        public string InBaseStore { get; set; }
        [Column(TypeName = "text")]
        public string OutBaseStore { get; set; }
        [Column(TypeName = "text")]
        public string JoinBaseStore { get; set; }
        [Column(TypeName = "text")]
        public string NoJoinBaseStore { get; set; }
        [StringLength(10)]
        public string Week { get; set; }
        [StringLength(100)]
        public string NoMoveDays { get; set; }
        [StringLength(100)]
        public string WeekSellRate { get; set; }
        [StringLength(100)]
        public string LimitNum { get; set; }
        [StringLength(100)]
        public string SellRate { get; set; }
        [StringLength(100)]
        public string StorageNum { get; set; }
        [StringLength(100)]
        public string Rank { get; set; }
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [StringLength(4)]
        public string ChangePerson { get; set; }
        [StringLength(1)]
        public string AutoFlag { get; set; }
        [StringLength(1)]
        public string SameFlag { get; set; }
        [StringLength(10)]
        public string SellRate_ZC { get; set; }
    }
}