// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Keyless]
    public partial class AGQ_GoodDetail
    {
        [Required]
        [StringLength(20)]
        public string PjtID { get; set; }
        [Required]
        [StringLength(30)]
        public string OutStore { get; set; }
        [StringLength(30)]
        public string InStore { get; set; }
        [StringLength(30)]
        public string GoodID { get; set; }
        [StringLength(1)]
        public string SizeNo { get; set; }
        [StringLength(2)]
        public string Position { get; set; }
        public long? Qty { get; set; }
        [StringLength(1)]
        public string DealFlag { get; set; }
        public long? SellQty { get; set; }
        public long? TotalSellQty { get; set; }
        [StringLength(2)]
        public string SizePosition { get; set; }
        [StringLength(8)]
        public string SIZEName { get; set; }
        [StringLength(50)]
        public string Type { get; set; }
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [StringLength(1)]
        public string PType { get; set; }
    }
}