// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    public partial class Agreement
    {
        [Key]
        [StringLength(13)]
        public string SerialID { get; set; }
        [Required]
        [StringLength(8)]
        public string StoreID { get; set; }
        [Required]
        [StringLength(8)]
        public string OccDate { get; set; }
        [Required]
        [StringLength(4)]
        public string EmpID { get; set; }
        [Required]
        [StringLength(20)]
        public string ContactPerson { get; set; }
        [Required]
        [StringLength(20)]
        public string Tel { get; set; }
        [Required]
        [StringLength(8)]
        public string StartDate { get; set; }
        [Required]
        [StringLength(8)]
        public string EndDate { get; set; }
        [Required]
        [StringLength(1)]
        public string Flag { get; set; }
        [Required]
        [StringLength(250)]
        public string ArgreeDetail { get; set; }
        [Required]
        [StringLength(250)]
        public string Remark { get; set; }
        public double SellAmount { get; set; }
        public double PackAmount { get; set; }
        public double CleanAmount { get; set; }
        public double ManageAmount { get; set; }
        public double CardAmount { get; set; }
        public double ByStagesAmount { get; set; }
        [Required]
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [Required]
        [StringLength(4)]
        public string ChangePerson { get; set; }
    }
}