// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    public partial class AlipayAccount
    {
        [Key]
        [StringLength(128)]
        public string OrderNo { get; set; }
        [StringLength(50)]
        public string OrderDT { get; set; }
        [StringLength(128)]
        public string ReOrderNo { get; set; }
        [StringLength(128)]
        public string BankOrderNo { get; set; }
        [StringLength(50)]
        public string BankOrderDT { get; set; }
        [StringLength(128)]
        public string ReBankOrderNo { get; set; }
        [StringLength(50)]
        public string ReBankOrderDT { get; set; }
        [StringLength(20)]
        public string SellID { get; set; }
        [StringLength(1024)]
        public string BuyerID { get; set; }
        [StringLength(50)]
        public string BuyerWallet { get; set; }
        [StringLength(10)]
        public string CurrencyName { get; set; }
        public float? OrderAmount { get; set; }
        [StringLength(50)]
        public string Status { get; set; }
        [StringLength(20)]
        public string TermID { get; set; }
        [StringLength(200)]
        public string OrderTitle { get; set; }
    }
}