// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    public partial class ApiDRCnew
    {
        [Key]
        public long PlatformID { get; set; }
        [Key]
        [StringLength(20)]
        public string TransactionId { get; set; }
        [Key]
        [StringLength(200)]
        public string OrderID { get; set; }
        [Key]
        [StringLength(20)]
        public string DeliveryReceiptId { get; set; }
        [StringLength(200)]
        public string FirstBarcode { get; set; }
        [StringLength(200)]
        public string RoutingBarcode { get; set; }
        [StringLength(200)]
        public string PickupEShopBarcode { get; set; }
        [StringLength(200)]
        public string PickupCodBarcode { get; set; }
        [StringLength(200)]
        public string PickupLogisticCode { get; set; }
        [StringLength(200)]
        public string LogisticCode { get; set; }
        [StringLength(200)]
        public string LogisticCheckSum { get; set; }
        [StringLength(200)]
        public string QrCode { get; set; }
        [StringLength(200)]
        public string StoreEquimentId { get; set; }
        [StringLength(200)]
        public string StoreRegion { get; set; }
        [StringLength(200)]
        public string StoreRoute { get; set; }
        [StringLength(200)]
        public string StoreRouteTrim { get; set; }
        [StringLength(200)]
        public string ReturnPeriod { get; set; }
        [StringLength(200)]
        public string ReturnType { get; set; }
        [StringLength(200)]
        public string MobilePhone { get; set; }
        [StringLength(200)]
        public string ConvenienceStoreId { get; set; }
        [StringLength(200)]
        public string ConvenienceStoreName { get; set; }
        [StringLength(200)]
        public string OrderInformation { get; set; }
        [StringLength(200)]
        public string LogisticOrderNumber { get; set; }
        [StringLength(200)]
        public string DistributionCenter { get; set; }
        [StringLength(200)]
        public string CustomerInformation { get; set; }
        [StringLength(200)]
        public string Remark { get; set; }
        [StringLength(200)]
        public string OfficialName { get; set; }
        [StringLength(200)]
        public string ChildShopcode { get; set; }
        [StringLength(200)]
        public string MomShopcode { get; set; }
    }
}