// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    public partial class ApiDeliveryReceiptContrast
    {
        [Key]
        public long PlatformID { get; set; }
        [Key]
        [StringLength(30)]
        public string TransactionId { get; set; }
        [Key]
        [StringLength(30)]
        public string OrderID { get; set; }
        [Key]
        [StringLength(20)]
        public string DeliveryReceiptId { get; set; }
    }
}