// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    public partial class ApiMember
    {
        [Key]
        public long PlatformID { get; set; }
        [Key]
        [StringLength(100)]
        public string Code { get; set; }
        [StringLength(20)]
        public string Password { get; set; }
        [StringLength(8)]
        public string MemberID { get; set; }
        [StringLength(50)]
        public string Buyer_Name { get; set; }
        [StringLength(100)]
        public string Buyer_EMail { get; set; }
        [StringLength(20)]
        public string Buyer_Tel { get; set; }
        [StringLength(100)]
        public string Buyer_Address { get; set; }
        [StringLength(50)]
        public string Receiver_Name { get; set; }
        [StringLength(100)]
        public string Receiver_EMail { get; set; }
        [StringLength(20)]
        public string Receiver_Tel { get; set; }
        [StringLength(100)]
        public string Receiver_Address { get; set; }
    }
}