// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    public partial class ApiOrder
    {
        [Key]
        public long PlatformID { get; set; }
        [Key]
        [StringLength(30)]
        public string TransactionId { get; set; }
        [Key]
        [StringLength(30)]
        public string OrderID { get; set; }
        [StringLength(20)]
        public string OrderStatus { get; set; }
        [StringLength(50)]
        public string OrderStatusDesc { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? TransferDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastShippingDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? OrderShippingDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? OrderCloseDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? BuyerConfirmDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? EntryAccountDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? PickingDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? OrderPackageDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastDeliveryDate { get; set; }
        [StringLength(20)]
        public string OrderShippingId { get; set; }
        [StringLength(20)]
        public string InvoiceNo { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? InvoiveDate { get; set; }
        [StringLength(50)]
        public string DeliverType { get; set; }
        [Column(TypeName = "ntext")]
        public string OrderNote { get; set; }
        [StringLength(50)]
        public string PayType { get; set; }
        [StringLength(50)]
        public string ShippingType { get; set; }
        public bool? NonPayment { get; set; }
        [StringLength(10)]
        public string DeliverCode { get; set; }
        [StringLength(30)]
        public string ShippingCarID { get; set; }
    }
}