// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Keyless]
    public partial class ApiProductSpecList
    {
        public long PlatformID { get; set; }
        [Required]
        [StringLength(20)]
        public string ProductID { get; set; }
        [Required]
        [StringLength(20)]
        public string SkuID { get; set; }
        [Required]
        [StringLength(20)]
        public string GoodID { get; set; }
        [Required]
        [StringLength(50)]
        public string SizeName { get; set; }
        public int? Qty { get; set; }
        public bool? StockIgnore { get; set; }
        public int? NoDeal { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ChangeTime { get; set; }
        [StringLength(50)]
        public string SaleType { get; set; }
    }
}