// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    public partial class ApiProductSpec
    {
        [Key]
        public long PlatformID { get; set; }
        [Key]
        [StringLength(20)]
        public string ProductID { get; set; }
        [Key]
        [StringLength(20)]
        public string SkuID { get; set; }
        [Required]
        [StringLength(20)]
        public string GoodID { get; set; }
        [Required]
        [StringLength(50)]
        public string SizeName { get; set; }
        public int? Qty { get; set; }
        public bool? StockIgnore { get; set; }
        public int? NoDeal { get; set; }
        [StringLength(50)]
        public string SaleType { get; set; }
        [StringLength(100)]
        public string YSizeName { get; set; }
        [StringLength(100)]
        public string ProductName { get; set; }
        [StringLength(100)]
        public string Sort05Name { get; set; }

        [ForeignKey(nameof(PlatformID))]
        [InverseProperty(nameof(ApiPlatform.ApiProductSpec))]
        public virtual ApiPlatform Platform { get; set; }
    }
}