// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    public partial class ApiReturns
    {
        [Key]
        public long PlatformID { get; set; }
        [Key]
        [StringLength(30)]
        public string ReturnNo { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ReturnDate { get; set; }
        [Key]
        [StringLength(30)]
        public string TransactionId { get; set; }
        [Key]
        [StringLength(30)]
        public string OrderID { get; set; }
        [StringLength(100)]
        public string ProductId { get; set; }
        [StringLength(2000)]
        public string ProductName { get; set; }
        [StringLength(20)]
        public string SkuId { get; set; }
        [StringLength(20)]
        public string GoodId { get; set; }
        [StringLength(2000)]
        public string SizeName { get; set; }
        [StringLength(2000)]
        public string Spec { get; set; }
        [StringLength(100)]
        public string Sort05Name { get; set; }
        public int? ReturnQty { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? ReturnAmt { get; set; }
        [StringLength(2000)]
        public string ReturnReason { get; set; }
        [StringLength(50)]
        public string Name { get; set; }
        [StringLength(20)]
        public string Phone { get; set; }
        [StringLength(20)]
        public string Mobile { get; set; }
        [StringLength(20)]
        public string Zipcode { get; set; }
        [StringLength(2000)]
        public string Address { get; set; }
        public bool? Flag { get; set; }
    }
}