// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    public partial class ApiSHOPLINEeinv
    {
        [Key]
        public long PlatformID { get; set; }
        [Key]
        [StringLength(30)]
        public string TransactionId { get; set; }
        [Required]
        [StringLength(20)]
        public string tax_id { get; set; }
        [Required]
        [StringLength(2000)]
        public string mailing_address { get; set; }
        [Required]
        [StringLength(1)]
        public string invoice_type { get; set; }
        [Required]
        [StringLength(50)]
        public string buyer_name { get; set; }
        [Required]
        [StringLength(1)]
        public string carrier_type { get; set; }
        [Required]
        [StringLength(20)]
        public string carrier_number { get; set; }
        [Required]
        [StringLength(20)]
        public string n_p_o_b_a_n { get; set; }
        [Required]
        [StringLength(1)]
        public string invoice_tax_type { get; set; }
        [Required]
        [StringLength(20)]
        public string invoice_number { get; set; }
        [Required]
        [StringLength(20)]
        public string invoice_status { get; set; }
        [Required]
        [StringLength(8)]
        public string invoice_date { get; set; }
        [Required]
        [StringLength(8)]
        public string invoice_cancelled_at { get; set; }
    }
}