// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    public partial class ApiSetting
    {
        [Key]
        public long PlatformID { get; set; }
        [Key]
        [StringLength(50)]
        public string Key { get; set; }
        [StringLength(50)]
        public string Value { get; set; }
    }
}