// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    public partial class APjtT5Send
    {
        [Key]
        [StringLength(15)]
        public string PjtID { get; set; }
        [Key]
        public int Item { get; set; }
        [StringLength(20)]
        public string GoodID { get; set; }
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [StringLength(4)]
        public string ChangePerson { get; set; }
    }
}