// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    public partial class APjt
    {
        [Key]
        [StringLength(12)]
        public string PjtID { get; set; }
        [StringLength(15)]
        public string SStore { get; set; }
        [StringLength(15)]
        public string EStore { get; set; }
        [StringLength(8)]
        public string SDay { get; set; }
        [StringLength(8)]
        public string EDay { get; set; }
        public double? PjtQty { get; set; }
        public double? PjtPrice { get; set; }
        [StringLength(1)]
        public string SChk { get; set; }
        public double? SPrice { get; set; }
        [StringLength(200)]
        public string Remark { get; set; }
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [StringLength(4)]
        public string ChangePerson { get; set; }
        public double? PjtDiscount { get; set; }
        [StringLength(1)]
        public string PjtType { get; set; }
        public double? T2Num { get; set; }
        public double? T2Dis { get; set; }
        public double? T3Num { get; set; }
        [StringLength(8)]
        public string StartCardID { get; set; }
        [StringLength(8)]
        public string EndCardID { get; set; }
        [StringLength(1)]
        public string T1SendFlag { get; set; }
        public double? T1SendNum { get; set; }
        public double? T4Amount { get; set; }
        public double? T4Price { get; set; }
        public double? T1TypeNum { get; set; }
        public double? T4ERAmount { get; set; }
        [StringLength(20)]
        public string T4ERGoodID { get; set; }
        [StringLength(1)]
        public string T4ERFlag { get; set; }
        public double? HongLi { get; set; }
        public double? HongLiTimes { get; set; }
        public double? T5Amount { get; set; }
        public double? T5ERAmount { get; set; }
        [StringLength(20)]
        public string T5ERGoodID { get; set; }
        [StringLength(1)]
        public string T5ERFlag { get; set; }
        public double? T5SendNum { get; set; }
        [StringLength(1)]
        public string T5SizeFlag { get; set; }
        public double? T4SendNum { get; set; }
        [StringLength(1)]
        public string T4chkGS { get; set; }
        [StringLength(1)]
        public string T5chkGS { get; set; }
        public double? T6MeetNum { get; set; }
        public double? T6SendNum { get; set; }
        [StringLength(1)]
        public string T6PriceSort { get; set; }
        [StringLength(1)]
        public string T3SendFlag { get; set; }
        [StringLength(1)]
        public string T5chkComply { get; set; }
        [StringLength(1)]
        public string A4PriceSort { get; set; }
        [StringLength(1)]
        public string AddAPjtFlag { get; set; }
        public int? LVOrder { get; set; }
        [StringLength(1)]
        public string Alone { get; set; }
        public double? T4Discount { get; set; }
        public double? T6SendDiscount { get; set; }
        public double? T5AllocationFlag { get; set; }
        public double? T5ThresholdMey { get; set; }
        [StringLength(1)]
        public string A1PriceSort { get; set; }
        [StringLength(1)]
        public string T5limitOne { get; set; }
    }
}