// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    public partial class APjtT3Set
    {
        [Key]
        [StringLength(15)]
        public string PjtID { get; set; }
        [Key]
        public int Item { get; set; }
        public double? SNum { get; set; }
        public double? ENum { get; set; }
        public double? Discount { get; set; }
        public double? Price { get; set; }
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [StringLength(4)]
        public string ChangePerson { get; set; }
        [StringLength(1)]
        public string T3chkAmount { get; set; }
        public double? T3SendNum { get; set; }
    }
}