// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    public partial class APjtDetail
    {
        [Key]
        [StringLength(15)]
        public string PjtID { get; set; }
        [Key]
        [StringLength(2)]
        public string TypeName { get; set; }
        [Key]
        [StringLength(20)]
        public string GoodID { get; set; }
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [StringLength(4)]
        public string ChangePerson { get; set; }
        [StringLength(100)]
        public string GoodName { get; set; }
        [StringLength(100)]
        public string FactoryName { get; set; }
        [StringLength(80)]
        public string BrandName { get; set; }
        [StringLength(80)]
        public string Sort01Name { get; set; }
        [StringLength(80)]
        public string Sort02Name { get; set; }
        public double? Discount { get; set; }
    }
}