// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Keyless]
    [Index(nameof(RowID), Name = "ArchivesDelete_Index_RowID")]
    [Index(nameof(DeleteTime), nameof(ChangePerson), Name = "ArchivesDelete_Index_TimePerson")]
    public partial class ArchivesDelete
    {
        [Required]
        [StringLength(13)]
        public string SerialID { get; set; }
        [Required]
        [StringLength(8)]
        public string OccDate { get; set; }
        [Required]
        [StringLength(4)]
        public string EmpID { get; set; }
        [Required]
        [StringLength(8)]
        public string SourceDept { get; set; }
        [Required]
        [StringLength(8)]
        public string ObjectDept { get; set; }
        [Required]
        [StringLength(8)]
        public string ExecuteDate { get; set; }
        [Required]
        [StringLength(2000)]
        public string Content { get; set; }
        [Required]
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [Required]
        [StringLength(4)]
        public string ChangePerson { get; set; }
        [StringLength(1)]
        public string CheckFlag { get; set; }
        [StringLength(20)]
        public string Sort { get; set; }
        [StringLength(200)]
        public string Remark { get; set; }
        [StringLength(1)]
        public string ReCheckFlag { get; set; }
        [StringLength(8)]
        public string ReCheckPerson { get; set; }
        [StringLength(20)]
        public string DeleteTime { get; set; }
        [StringLength(50)]
        public string RowID { get; set; }
    }
}