// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Keyless]
    [Index(nameof(RowID), Name = "ArchivesObjectListDelete_Index_RowID")]
    public partial class ArchivesObjectListDelete
    {
        [Required]
        [StringLength(13)]
        public string SerialID { get; set; }
        [Required]
        [StringLength(8)]
        public string StoreID { get; set; }
        [Required]
        [StringLength(1)]
        public string SureFlag { get; set; }
        [Required]
        [StringLength(20)]
        public string extField1 { get; set; }
        [Required]
        [StringLength(20)]
        public string extField2 { get; set; }
        [StringLength(50)]
        public string RowID { get; set; }
    }
}