// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    public partial class ArchivesConfigList
    {
        [Key]
        [StringLength(15)]
        public string SerialID { get; set; }
        [Key]
        public int Item { get; set; }
        [Required]
        [StringLength(8)]
        public string StoreID { get; set; }
        [Required]
        [StringLength(8)]
        public string EmpID { get; set; }
        [Required]
        [StringLength(20)]
        public string ConfigTime { get; set; }
        [Required]
        [StringLength(500)]
        public string Remark { get; set; }
        [Required]
        [StringLength(20)]
        public string extField1 { get; set; }
        [Required]
        [StringLength(20)]
        public string extField2 { get; set; }
    }
}