// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Keyless]
    public partial class AreaCode
    {
        [Column("AreaCode")]
        [StringLength(6)]
        public string AreaCode1 { get; set; }
        [StringLength(6)]
        public string Area { get; set; }
        [StringLength(10)]
        public string City { get; set; }
    }
}