// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    public partial class AutoTransferSet
    {
        [Key]
        [StringLength(200)]
        public string TableName { get; set; }
        [Required]
        [StringLength(1)]
        public string OverWriteFlag { get; set; }
        [Required]
        [StringLength(20)]
        public string BranchFld { get; set; }
        [StringLength(1)]
        public string IsTranIn { get; set; }
        [StringLength(1)]
        public string IsTranOut { get; set; }
        [StringLength(1)]
        public string IsReceive { get; set; }
        [StringLength(1)]
        public string IsSend { get; set; }
    }
}