// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    public partial class Bank
    {
        [Key]
        [StringLength(20)]
        public string BankID { get; set; }
        [StringLength(60)]
        public string BankName { get; set; }
        [StringLength(14)]
        public string TelPhone { get; set; }
        [StringLength(20)]
        public string UnderTakePerson { get; set; }
        [StringLength(8)]
        public string BalanceDate { get; set; }
        public double? Balance { get; set; }
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [StringLength(4)]
        public string ChangePerson { get; set; }
        [StringLength(10)]
        public string BankNo { get; set; }
    }
}