// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    public partial class BranchMoney
    {
        [Key]
        [StringLength(15)]
        public string BranchID { get; set; }
        [Key]
        [StringLength(8)]
        public string BranchDate { get; set; }
        public double? SellAmount { get; set; }
        public double? Cash { get; set; }
        public double? CardAmount { get; set; }
        public double? Fund { get; set; }
        public double? TranferAmount { get; set; }
        public double? OtherAmount { get; set; }
        public double? TotalAmount { get; set; }
        public double? SellCost { get; set; }
        public double? TranferCost { get; set; }
        public double? Benefit { get; set; }
        public double? Salary { get; set; }
        public double? ToolFate { get; set; }
        public double? MailFate { get; set; }
        public double? FixRate { get; set; }
        public double? AdRate { get; set; }
        public double? WERate { get; set; }
        public double? RentRate { get; set; }
        public double? DV20 { get; set; }
        public double? MessRate { get; set; }
        public double? LabourRate { get; set; }
        public double? HealthyRate { get; set; }
        public double? TravelRate { get; set; }
        public double? Premiun { get; set; }
        public double? Lost { get; set; }
        public double? Tax { get; set; }
        public double? SignCardRate { get; set; }
        public double? OtherRate1 { get; set; }
        public double? OtherRate2 { get; set; }
        public double? OtherRate3 { get; set; }
        public double? TotalOtherRate { get; set; }
        public double? Profit { get; set; }
        public double? CashIncome { get; set; }
        public double? CashPayout { get; set; }
        public double? BankAmount { get; set; }
        public double? CashLeft { get; set; }
        [StringLength(100)]
        public string Remark { get; set; }
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [StringLength(4)]
        public string ChangePerson { get; set; }
        public double? People { get; set; }
    }
}