// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    public partial class BrandCust
    {
        [Key]
        [StringLength(10)]
        public string BrandID { get; set; }
        [Key]
        [StringLength(15)]
        public string CustID { get; set; }
        [Key]
        [StringLength(4)]
        public string OperationID { get; set; }
        public double? ProphaseNoIncome { get; set; }
        public double? ProphaseIncome { get; set; }
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [StringLength(4)]
        public string ChangePerson { get; set; }
        public double? Discount { get; set; }
        [StringLength(1)]
        public string Type { get; set; }
        [Required]
        [StringLength(20)]
        public string Rem1 { get; set; }
        [Required]
        [StringLength(20)]
        public string Rem2 { get; set; }
    }
}