// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    public partial class Branch_Gather
    {
        [Key]
        [StringLength(13)]
        public string SerialID { get; set; }
        [Required]
        [StringLength(8)]
        public string OccDate { get; set; }
        [Required]
        [StringLength(4)]
        public string Person { get; set; }
        [Required]
        [StringLength(20)]
        public string BankID { get; set; }
        [Required]
        [StringLength(8)]
        public string BranchID { get; set; }
        [Required]
        [StringLength(8)]
        public string SellMonth { get; set; }
        public double GatherAmt { get; set; }
        [Required]
        [StringLength(200)]
        public string Remark { get; set; }
        [Required]
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [Required]
        [StringLength(4)]
        public string ChangePerson { get; set; }
        [StringLength(1)]
        public string Type { get; set; }
        [StringLength(20)]
        public string PayBank { get; set; }
        [StringLength(20)]
        public string BillNo { get; set; }
        [StringLength(8)]
        public string TermDate { get; set; }
    }
}