// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    public partial class Card
    {
        [Key]
        [StringLength(3)]
        public string CardID { get; set; }
        [StringLength(40)]
        public string CardName { get; set; }
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [StringLength(50)]
        public string ChangePerson { get; set; }
    }
}