// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    public partial class ClientDealMode
    {
        [Key]
        [StringLength(8)]
        public string DealModeID { get; set; }
        [Required]
        [StringLength(200)]
        public string DealModeName { get; set; }
        public int ShipMode { get; set; }
        [Required]
        public bool? IsCanMaiDuan { get; set; }
        [Required]
        public bool? IsCanJiMai { get; set; }
        [Required]
        public bool? IsCanShipContinue { get; set; }
        [Required]
        public bool? IsCanReturnContinue { get; set; }
        [Required]
        [StringLength(1000)]
        public string Remark { get; set; }
        [Required]
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [Required]
        [StringLength(4)]
        public string ChangePerson { get; set; }
    }
}