// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    public partial class ClosingSetup
    {
        [Key]
        public int ClosingID { get; set; }
        public int Item { get; set; }
        [Required]
        [StringLength(20)]
        public string ClosingName { get; set; }
        [Required]
        [StringLength(20)]
        public string ClosingType { get; set; }
        [Required]
        [StringLength(100)]
        public string Remark { get; set; }
        [Required]
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [Required]
        [StringLength(4)]
        public string ChangePerson { get; set; }
    }
}