// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    public partial class DeviceInfo
    {
        [Key]
        [StringLength(100)]
        public string DeviceID { get; set; }
        [StringLength(200)]
        public string DeviceName { get; set; }
        [StringLength(20)]
        public string ClientID { get; set; }
        [StringLength(200)]
        public string ServerName { get; set; }
        [StringLength(200)]
        public string UserName { get; set; }
        [StringLength(200)]
        public string DatabaseName { get; set; }
        [StringLength(200)]
        public string Password { get; set; }
    }
}