// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    public partial class DistributePoint
    {
        [Key]
        [StringLength(13)]
        public string SerialID { get; set; }
        [Required]
        [StringLength(8)]
        public string OccDate { get; set; }
        [Required]
        [StringLength(8)]
        public string FillPerson { get; set; }
        [Required]
        [StringLength(20)]
        public string MemberID { get; set; }
        public int Point { get; set; }
        [Required]
        [StringLength(100)]
        public string Remark { get; set; }
        [Required]
        [StringLength(20)]
        public string SellId { get; set; }
        [Required]
        [StringLength(4)]
        public string SellItem { get; set; }
        [Required]
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [Required]
        [StringLength(4)]
        public string ChangePerson { get; set; }
        [StringLength(1)]
        public string Mode { get; set; }
        public double? SellMey { get; set; }
    }
}