// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    public partial class DistributeGoods
    {
        [Key]
        [StringLength(20)]
        public string SerialID { get; set; }
        [Required]
        [StringLength(8)]
        public string OccDate { get; set; }
        [Required]
        [StringLength(4)]
        public string EntryPerson { get; set; }
        [Required]
        [StringLength(1)]
        public string FinishFlag { get; set; }
        [Key]
        [StringLength(4)]
        public string Item { get; set; }
        [Required]
        [StringLength(20)]
        public string GoodID { get; set; }
        [Required]
        [StringLength(1)]
        public string SizeNo { get; set; }
        [Required]
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [Required]
        [StringLength(4)]
        public string ChangePerson { get; set; }
        [Required]
        [StringLength(20)]
        public string BeginGoodID { get; set; }
        [Required]
        [StringLength(20)]
        public string EndGoodID { get; set; }
        [Required]
        [StringLength(15)]
        public string BeginStore { get; set; }
        [Required]
        [StringLength(15)]
        public string EndStore { get; set; }
        [Required]
        [StringLength(8)]
        public string BeginDate { get; set; }
        [Required]
        [StringLength(8)]
        public string EndDate { get; set; }
    }
}