// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    public partial class EInvShipNoMain
    {
        [StringLength(10)]
        public string Version { get; set; }
        [Key]
        [StringLength(100)]
        public string AppID { get; set; }
        [StringLength(10)]
        public string Serial { get; set; }
        [StringLength(8)]
        public string SysDate { get; set; }
        [StringLength(6)]
        public string SysTime { get; set; }
        [StringLength(1)]
        public string InvFrom { get; set; }
        [StringLength(20)]
        public string PosOrderNo { get; set; }
        [Key]
        [StringLength(5)]
        public string InvTerm { get; set; }
        [Key]
        [StringLength(10)]
        public string InvNum { get; set; }
        [StringLength(8)]
        public string InvDate { get; set; }
        [StringLength(6)]
        public string InvTime { get; set; }
        [StringLength(8)]
        public string CustomerIdentifier { get; set; }
        [StringLength(200)]
        public string CustomerName { get; set; }
        [StringLength(50)]
        public string CustomerTel { get; set; }
        [StringLength(200)]
        public string CustomerAddr { get; set; }
        [StringLength(200)]
        public string CustomerEmail { get; set; }
        [StringLength(1)]
        public string ClearanceMark { get; set; }
        [StringLength(2)]
        public string InvType { get; set; }
        [StringLength(1)]
        public string Donation { get; set; }
        [StringLength(1)]
        public string CarrierType { get; set; }
        [StringLength(16)]
        public string CarrierNum { get; set; }
        [StringLength(1)]
        public string PrintMark { get; set; }
        [StringLength(7)]
        public string LoveCode { get; set; }
        [StringLength(8)]
        public string CustomerID { get; set; }
        [StringLength(4)]
        public string RandomNum { get; set; }
        public int? SalesAmount { get; set; }
        [StringLength(1)]
        public string TaxType { get; set; }
        [StringLength(1)]
        public string TaxRate { get; set; }
        public int? TaxAmount { get; set; }
        public int? TotalAmount { get; set; }
        [StringLength(100)]
        public string CheckMacValue { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreateDate { get; set; }
        [StringLength(10)]
        public string CreatePerson { get; set; }
        [StringLength(20)]
        public string Code { get; set; }
        [StringLength(100)]
        public string Msg { get; set; }
        [StringLength(2000)]
        public string JSONstr { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? SendDate { get; set; }
        [StringLength(10)]
        public string SendPerson { get; set; }
        [StringLength(20)]
        public string CardNum { get; set; }
        [StringLength(200)]
        public string Remark1 { get; set; }
        [StringLength(200)]
        public string Remark2 { get; set; }
        [StringLength(200)]
        public string Remark3 { get; set; }
        [StringLength(200)]
        public string Remark4 { get; set; }
        [StringLength(200)]
        public string Remark5 { get; set; }
        public int? FreeTaxSaleAmount { get; set; }
        public int? ZeroTaxSaleAmount { get; set; }
        public int? FreeTaxSalesAmount { get; set; }
        public int? ZeroTaxSalesAmount { get; set; }
    }
}