// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    public partial class EInvAllowanceMain
    {
        [Key]
        [StringLength(20)]
        public string SerialID { get; set; }
        [StringLength(8)]
        public string OccDate { get; set; }
        [StringLength(10)]
        public string Identifier { get; set; }
        [StringLength(60)]
        public string Name { get; set; }
        [StringLength(10)]
        public string CustomerIdentifier { get; set; }
        [StringLength(60)]
        public string CustomerName { get; set; }
        [StringLength(1)]
        public string AllowanceType { get; set; }
        [StringLength(30)]
        public string CompanyBAN { get; set; }
        public int? TaxAmount { get; set; }
        public int? TotalAmount { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreateDate { get; set; }
        [StringLength(10)]
        public string CreatePerson { get; set; }
        [StringLength(20)]
        public string Code { get; set; }
        [StringLength(100)]
        public string Msg { get; set; }
        [StringLength(2000)]
        public string JSONstr { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? SendDate { get; set; }
        [StringLength(10)]
        public string SendPerson { get; set; }
        [StringLength(10)]
        public string Version { get; set; }
        [StringLength(100)]
        public string AppID { get; set; }
        [StringLength(10)]
        public string Serial { get; set; }
        [StringLength(8)]
        public string SysDate { get; set; }
        [StringLength(6)]
        public string SysTime { get; set; }
        [StringLength(100)]
        public string CheckMacValue { get; set; }
        [StringLength(1)]
        public string InvFrom { get; set; }
    }
}