// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    public partial class EmpClockInMonth
    {
        [Key]
        [StringLength(8)]
        public string ClockMonth { get; set; }
        [Key]
        [StringLength(8)]
        public string EmpID { get; set; }
        [Key]
        [StringLength(8)]
        public string ClockStore { get; set; }
        [StringLength(4)]
        public string Day1 { get; set; }
        [StringLength(8)]
        public string InTime1 { get; set; }
        [StringLength(8)]
        public string OutTime1 { get; set; }
        [StringLength(8)]
        public string StOnDutyTime1 { get; set; }
        [StringLength(8)]
        public string StOffDutyTime1 { get; set; }
        public double? LateHours1 { get; set; }
        public double? MorningOutHours1 { get; set; }
        public double? AwayHours1 { get; set; }
        public double? OverHours1 { get; set; }
        public double? OnDuty1 { get; set; }
        [StringLength(4)]
        public string Day2 { get; set; }
        [StringLength(8)]
        public string InTime2 { get; set; }
        [StringLength(8)]
        public string OutTime2 { get; set; }
        [StringLength(8)]
        public string StOnDutyTime2 { get; set; }
        [StringLength(8)]
        public string StOffDutyTime2 { get; set; }
        public double? LateHours2 { get; set; }
        public double? MorningOutHours2 { get; set; }
        public double? AwayHours2 { get; set; }
        public double? OverHours2 { get; set; }
        public double? OnDuty2 { get; set; }
        [StringLength(4)]
        public string Day3 { get; set; }
        [StringLength(8)]
        public string InTime3 { get; set; }
        [StringLength(8)]
        public string OutTime3 { get; set; }
        [StringLength(8)]
        public string StOnDutyTime3 { get; set; }
        [StringLength(8)]
        public string StOffDutyTime3 { get; set; }
        public double? LateHours3 { get; set; }
        public double? MorningOutHours3 { get; set; }
        public double? AwayHours3 { get; set; }
        public double? OverHours3 { get; set; }
        public double? OnDuty3 { get; set; }
        [StringLength(4)]
        public string Day4 { get; set; }
        [StringLength(8)]
        public string InTime4 { get; set; }
        [StringLength(8)]
        public string OutTime4 { get; set; }
        [StringLength(8)]
        public string StOnDutyTime4 { get; set; }
        [StringLength(8)]
        public string StOffDutyTime4 { get; set; }
        public double? LateHours4 { get; set; }
        public double? MorningOutHours4 { get; set; }
        public double? AwayHours4 { get; set; }
        public double? OverHours4 { get; set; }
        public double? OnDuty4 { get; set; }
        [StringLength(4)]
        public string Day5 { get; set; }
        [StringLength(8)]
        public string InTime5 { get; set; }
        [StringLength(8)]
        public string OutTime5 { get; set; }
        [StringLength(8)]
        public string StOnDutyTime5 { get; set; }
        [StringLength(8)]
        public string StOffDutyTime5 { get; set; }
        public double? LateHours5 { get; set; }
        public double? MorningOutHours5 { get; set; }
        public double? AwayHours5 { get; set; }
        public double? OverHours5 { get; set; }
        public double? OnDuty5 { get; set; }
        [StringLength(4)]
        public string Day6 { get; set; }
        [StringLength(8)]
        public string InTime6 { get; set; }
        [StringLength(8)]
        public string OutTime6 { get; set; }
        [StringLength(8)]
        public string StOnDutyTime6 { get; set; }
        [StringLength(8)]
        public string StOffDutyTime6 { get; set; }
        public double? LateHours6 { get; set; }
        public double? MorningOutHours6 { get; set; }
        public double? AwayHours6 { get; set; }
        public double? OverHours6 { get; set; }
        public double? OnDuty6 { get; set; }
        [StringLength(4)]
        public string Day7 { get; set; }
        [StringLength(8)]
        public string InTime7 { get; set; }
        [StringLength(8)]
        public string OutTime7 { get; set; }
        [StringLength(8)]
        public string StOnDutyTime7 { get; set; }
        [StringLength(8)]
        public string StOffDutyTime7 { get; set; }
        public double? LateHours7 { get; set; }
        public double? MorningOutHours7 { get; set; }
        public double? AwayHours7 { get; set; }
        public double? OverHours7 { get; set; }
        public double? OnDuty7 { get; set; }
        [StringLength(4)]
        public string Day8 { get; set; }
        [StringLength(8)]
        public string InTime8 { get; set; }
        [StringLength(8)]
        public string OutTime8 { get; set; }
        [StringLength(8)]
        public string StOnDutyTime8 { get; set; }
        [StringLength(8)]
        public string StOffDutyTime8 { get; set; }
        public double? LateHours8 { get; set; }
        public double? MorningOutHours8 { get; set; }
        public double? AwayHours8 { get; set; }
        public double? OverHours8 { get; set; }
        public double? OnDuty8 { get; set; }
        [StringLength(4)]
        public string Day9 { get; set; }
        [StringLength(8)]
        public string InTime9 { get; set; }
        [StringLength(8)]
        public string OutTime9 { get; set; }
        [StringLength(8)]
        public string StOnDutyTime9 { get; set; }
        [StringLength(8)]
        public string StOffDutyTime9 { get; set; }
        public double? LateHours9 { get; set; }
        public double? MorningOutHours9 { get; set; }
        public double? AwayHours9 { get; set; }
        public double? OverHours9 { get; set; }
        public double? OnDuty9 { get; set; }
        [StringLength(4)]
        public string Day10 { get; set; }
        [StringLength(8)]
        public string InTime10 { get; set; }
        [StringLength(8)]
        public string OutTime10 { get; set; }
        [StringLength(8)]
        public string StOnDutyTime10 { get; set; }
        [StringLength(8)]
        public string StOffDutyTime10 { get; set; }
        public double? LateHours10 { get; set; }
        public double? MorningOutHours10 { get; set; }
        public double? AwayHours10 { get; set; }
        public double? OverHours10 { get; set; }
        public double? OnDuty10 { get; set; }
        [StringLength(4)]
        public string Day11 { get; set; }
        [StringLength(8)]
        public string InTime11 { get; set; }
        [StringLength(8)]
        public string OutTime11 { get; set; }
        [StringLength(8)]
        public string StOnDutyTime11 { get; set; }
        [StringLength(8)]
        public string StOffDutyTime11 { get; set; }
        public double? LateHours11 { get; set; }
        public double? MorningOutHours11 { get; set; }
        public double? AwayHours11 { get; set; }
        public double? OverHours11 { get; set; }
        public double? OnDuty11 { get; set; }
        [StringLength(4)]
        public string Day12 { get; set; }
        [StringLength(8)]
        public string InTime12 { get; set; }
        [StringLength(8)]
        public string OutTime12 { get; set; }
        [StringLength(8)]
        public string StOnDutyTime12 { get; set; }
        [StringLength(8)]
        public string StOffDutyTime12 { get; set; }
        public double? LateHours12 { get; set; }
        public double? MorningOutHours12 { get; set; }
        public double? AwayHours12 { get; set; }
        public double? OverHours12 { get; set; }
        public double? OnDuty12 { get; set; }
        [StringLength(4)]
        public string Day13 { get; set; }
        [StringLength(8)]
        public string InTime13 { get; set; }
        [StringLength(8)]
        public string OutTime13 { get; set; }
        [StringLength(8)]
        public string StOnDutyTime13 { get; set; }
        [StringLength(8)]
        public string StOffDutyTime13 { get; set; }
        public double? LateHours13 { get; set; }
        public double? MorningOutHours13 { get; set; }
        public double? AwayHours13 { get; set; }
        public double? OverHours13 { get; set; }
        public double? OnDuty13 { get; set; }
        [StringLength(4)]
        public string Day14 { get; set; }
        [StringLength(8)]
        public string InTime14 { get; set; }
        [StringLength(8)]
        public string OutTime14 { get; set; }
        [StringLength(8)]
        public string StOnDutyTime14 { get; set; }
        [StringLength(8)]
        public string StOffDutyTime14 { get; set; }
        public double? LateHours14 { get; set; }
        public double? MorningOutHours14 { get; set; }
        public double? AwayHours14 { get; set; }
        public double? OverHours14 { get; set; }
        public double? OnDuty14 { get; set; }
        [StringLength(4)]
        public string Day15 { get; set; }
        [StringLength(8)]
        public string InTime15 { get; set; }
        [StringLength(8)]
        public string OutTime15 { get; set; }
        [StringLength(8)]
        public string StOnDutyTime15 { get; set; }
        [StringLength(8)]
        public string StOffDutyTime15 { get; set; }
        public double? LateHours15 { get; set; }
        public double? MorningOutHours15 { get; set; }
        public double? AwayHours15 { get; set; }
        public double? OverHours15 { get; set; }
        public double? OnDuty15 { get; set; }
        [StringLength(4)]
        public string Day16 { get; set; }
        [StringLength(8)]
        public string InTime16 { get; set; }
        [StringLength(8)]
        public string OutTime16 { get; set; }
        [StringLength(8)]
        public string StOnDutyTime16 { get; set; }
        [StringLength(8)]
        public string StOffDutyTime16 { get; set; }
        public double? LateHours16 { get; set; }
        public double? MorningOutHours16 { get; set; }
        public double? AwayHours16 { get; set; }
        public double? OverHours16 { get; set; }
        public double? OnDuty16 { get; set; }
        [StringLength(4)]
        public string Day17 { get; set; }
        [StringLength(8)]
        public string InTime17 { get; set; }
        [StringLength(8)]
        public string OutTime17 { get; set; }
        [StringLength(8)]
        public string StOnDutyTime17 { get; set; }
        [StringLength(8)]
        public string StOffDutyTime17 { get; set; }
        public double? LateHours17 { get; set; }
        public double? MorningOutHours17 { get; set; }
        public double? AwayHours17 { get; set; }
        public double? OverHours17 { get; set; }
        public double? OnDuty17 { get; set; }
        [StringLength(4)]
        public string Day18 { get; set; }
        [StringLength(8)]
        public string InTime18 { get; set; }
        [StringLength(8)]
        public string OutTime18 { get; set; }
        [StringLength(8)]
        public string StOnDutyTime18 { get; set; }
        [StringLength(8)]
        public string StOffDutyTime18 { get; set; }
        public double? LateHours18 { get; set; }
        public double? MorningOutHours18 { get; set; }
        public double? AwayHours18 { get; set; }
        public double? OverHours18 { get; set; }
        public double? OnDuty18 { get; set; }
        [StringLength(4)]
        public string Day19 { get; set; }
        [StringLength(8)]
        public string InTime19 { get; set; }
        [StringLength(8)]
        public string OutTime19 { get; set; }
        [StringLength(8)]
        public string StOnDutyTime19 { get; set; }
        [StringLength(8)]
        public string StOffDutyTime19 { get; set; }
        public double? LateHours19 { get; set; }
        public double? MorningOutHours19 { get; set; }
        public double? AwayHours19 { get; set; }
        public double? OverHours19 { get; set; }
        public double? OnDuty19 { get; set; }
        [StringLength(4)]
        public string Day20 { get; set; }
        [StringLength(8)]
        public string InTime20 { get; set; }
        [StringLength(8)]
        public string OutTime20 { get; set; }
        [StringLength(8)]
        public string StOnDutyTime20 { get; set; }
        [StringLength(8)]
        public string StOffDutyTime20 { get; set; }
        public double? LateHours20 { get; set; }
        public double? MorningOutHours20 { get; set; }
        public double? AwayHours20 { get; set; }
        public double? OverHours20 { get; set; }
        public double? OnDuty20 { get; set; }
        [StringLength(4)]
        public string Day21 { get; set; }
        [StringLength(8)]
        public string InTime21 { get; set; }
        [StringLength(8)]
        public string OutTime21 { get; set; }
        [StringLength(8)]
        public string StOnDutyTime21 { get; set; }
        [StringLength(8)]
        public string StOffDutyTime21 { get; set; }
        public double? LateHours21 { get; set; }
        public double? MorningOutHours21 { get; set; }
        public double? AwayHours21 { get; set; }
        public double? OverHours21 { get; set; }
        public double? OnDuty21 { get; set; }
        [StringLength(4)]
        public string Day22 { get; set; }
        [StringLength(8)]
        public string InTime22 { get; set; }
        [StringLength(8)]
        public string OutTime22 { get; set; }
        [StringLength(8)]
        public string StOnDutyTime22 { get; set; }
        [StringLength(8)]
        public string StOffDutyTime22 { get; set; }
        public double? LateHours22 { get; set; }
        public double? MorningOutHours22 { get; set; }
        public double? AwayHours22 { get; set; }
        public double? OverHours22 { get; set; }
        public double? OnDuty22 { get; set; }
        [StringLength(4)]
        public string Day23 { get; set; }
        [StringLength(8)]
        public string InTime23 { get; set; }
        [StringLength(8)]
        public string OutTime23 { get; set; }
        [StringLength(8)]
        public string StOnDutyTime23 { get; set; }
        [StringLength(8)]
        public string StOffDutyTime23 { get; set; }
        public double? LateHours23 { get; set; }
        public double? MorningOutHours23 { get; set; }
        public double? AwayHours23 { get; set; }
        public double? OverHours23 { get; set; }
        public double? OnDuty23 { get; set; }
        [StringLength(4)]
        public string Day24 { get; set; }
        [StringLength(8)]
        public string InTime24 { get; set; }
        [StringLength(8)]
        public string OutTime24 { get; set; }
        [StringLength(8)]
        public string StOnDutyTime24 { get; set; }
        [StringLength(8)]
        public string StOffDutyTime24 { get; set; }
        public double? LateHours24 { get; set; }
        public double? MorningOutHours24 { get; set; }
        public double? AwayHours24 { get; set; }
        public double? OverHours24 { get; set; }
        public double? OnDuty24 { get; set; }
        [StringLength(4)]
        public string Day25 { get; set; }
        [StringLength(8)]
        public string InTime25 { get; set; }
        [StringLength(8)]
        public string OutTime25 { get; set; }
        [StringLength(8)]
        public string StOnDutyTime25 { get; set; }
        [StringLength(8)]
        public string StOffDutyTime25 { get; set; }
        public double? LateHours25 { get; set; }
        public double? MorningOutHours25 { get; set; }
        public double? AwayHours25 { get; set; }
        public double? OverHours25 { get; set; }
        public double? OnDuty25 { get; set; }
        [StringLength(4)]
        public string Day26 { get; set; }
        [StringLength(8)]
        public string InTime26 { get; set; }
        [StringLength(8)]
        public string OutTime26 { get; set; }
        [StringLength(8)]
        public string StOnDutyTime26 { get; set; }
        [StringLength(8)]
        public string StOffDutyTime26 { get; set; }
        public double? LateHours26 { get; set; }
        public double? MorningOutHours26 { get; set; }
        public double? AwayHours26 { get; set; }
        public double? OverHours26 { get; set; }
        public double? OnDuty26 { get; set; }
        [StringLength(4)]
        public string Day27 { get; set; }
        [StringLength(8)]
        public string InTime27 { get; set; }
        [StringLength(8)]
        public string OutTime27 { get; set; }
        [StringLength(8)]
        public string StOnDutyTime27 { get; set; }
        [StringLength(8)]
        public string StOffDutyTime27 { get; set; }
        public double? LateHours27 { get; set; }
        public double? MorningOutHours27 { get; set; }
        public double? AwayHours27 { get; set; }
        public double? OverHours27 { get; set; }
        public double? OnDuty27 { get; set; }
        [StringLength(4)]
        public string Day28 { get; set; }
        [StringLength(8)]
        public string InTime28 { get; set; }
        [StringLength(8)]
        public string OutTime28 { get; set; }
        [StringLength(8)]
        public string StOnDutyTime28 { get; set; }
        [StringLength(8)]
        public string StOffDutyTime28 { get; set; }
        public double? LateHours28 { get; set; }
        public double? MorningOutHours28 { get; set; }
        public double? AwayHours28 { get; set; }
        public double? OverHours28 { get; set; }
        public double? OnDuty28 { get; set; }
        [StringLength(4)]
        public string Day29 { get; set; }
        [StringLength(8)]
        public string InTime29 { get; set; }
        [StringLength(8)]
        public string OutTime29 { get; set; }
        [StringLength(8)]
        public string StOnDutyTime29 { get; set; }
        [StringLength(8)]
        public string StOffDutyTime29 { get; set; }
        public double? LateHours29 { get; set; }
        public double? MorningOutHours29 { get; set; }
        public double? AwayHours29 { get; set; }
        public double? OverHours29 { get; set; }
        public double? OnDuty29 { get; set; }
        [StringLength(4)]
        public string Day30 { get; set; }
        [StringLength(8)]
        public string InTime30 { get; set; }
        [StringLength(8)]
        public string OutTime30 { get; set; }
        [StringLength(8)]
        public string StOnDutyTime30 { get; set; }
        [StringLength(8)]
        public string StOffDutyTime30 { get; set; }
        public double? LateHours30 { get; set; }
        public double? MorningOutHours30 { get; set; }
        public double? AwayHours30 { get; set; }
        public double? OverHours30 { get; set; }
        public double? OnDuty30 { get; set; }
        [StringLength(4)]
        public string Day31 { get; set; }
        [StringLength(8)]
        public string InTime31 { get; set; }
        [StringLength(8)]
        public string OutTime31 { get; set; }
        [StringLength(8)]
        public string StOnDutyTime31 { get; set; }
        [StringLength(8)]
        public string StOffDutyTime31 { get; set; }
        public double? LateHours31 { get; set; }
        public double? MorningOutHours31 { get; set; }
        public double? AwayHours31 { get; set; }
        public double? OverHours31 { get; set; }
        public double? OnDuty31 { get; set; }
        public double? LateHoursTot { get; set; }
        public double? MorningOutHoursTot { get; set; }
        public double? AwayHoursTot { get; set; }
        public double? OverHoursTot { get; set; }
        public double? OnDutyTot { get; set; }
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [StringLength(8)]
        public string ChangePerson { get; set; }
    }
}