// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Keyless]
    public partial class EmpCheckDetail
    {
        [Required]
        [StringLength(20)]
        public string EmpID { get; set; }
        [Required]
        [StringLength(20)]
        public string ProgramName { get; set; }
        [Required]
        [StringLength(1)]
        public string IsSelect { get; set; }
        [Required]
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [Required]
        [StringLength(4)]
        public string ChangePerson { get; set; }
    }
}