// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Keyless]
    public partial class EmpDutyTypeSetUp
    {
        [Required]
        [StringLength(2)]
        public string DutyID { get; set; }
        [Required]
        [StringLength(8)]
        public string DutyName { get; set; }
        [Required]
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [Required]
        [StringLength(4)]
        public string ChangePerson { get; set; }
        [StringLength(8)]
        public string StOnDutyTime { get; set; }
        [StringLength(8)]
        public string StOffDutyTime { get; set; }
    }
}