// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Index(nameof(EmpName), Name = "D200B")]
    [Index(nameof(Department), Name = "D200C")]
    [Index(nameof(IdCard), Name = "IdCard")]
    public partial class Employee
    {
        [Key]
        [StringLength(4)]
        public string EmpID { get; set; }
        [StringLength(20)]
        public string EmpName { get; set; }
        [StringLength(20)]
        public string IdCard { get; set; }
        [StringLength(16)]
        public string Department { get; set; }
        [StringLength(16)]
        public string WorkStation { get; set; }
        [StringLength(20)]
        public string TelPhone { get; set; }
        [StringLength(8)]
        public string BirthDay { get; set; }
        [StringLength(8)]
        public string WorkDay { get; set; }
        [StringLength(8)]
        public string SafetyDay { get; set; }
        [StringLength(100)]
        public string FamilyAddr01 { get; set; }
        [StringLength(20)]
        public string FamilyAddr02 { get; set; }
        [StringLength(20)]
        public string FamilyAddr03 { get; set; }
        [StringLength(20)]
        public string FamilyAddr04 { get; set; }
        [StringLength(100)]
        public string ContactAddr01 { get; set; }
        [StringLength(20)]
        public string ContactAddr02 { get; set; }
        [StringLength(20)]
        public string ContactAddr03 { get; set; }
        [StringLength(20)]
        public string ContactAddr04 { get; set; }
        [StringLength(40)]
        public string ExigencePeason { get; set; }
        [StringLength(14)]
        public string ExigenceTel { get; set; }
        public double? MonthSuccess01 { get; set; }
        public double? MonthSuccess02 { get; set; }
        public double? MonthSuccess03 { get; set; }
        public double? MonthSuccess04 { get; set; }
        public double? MonthSuccess05 { get; set; }
        public double? MonthSuccess06 { get; set; }
        public double? MonthSuccess07 { get; set; }
        public double? MonthSuccess08 { get; set; }
        public double? MonthSuccess09 { get; set; }
        public double? MonthSuccess10 { get; set; }
        public double? MonthSuccess11 { get; set; }
        public double? MonthSuccess12 { get; set; }
        [StringLength(100)]
        public string Remark01 { get; set; }
        [StringLength(100)]
        public string Remark02 { get; set; }
        [StringLength(8)]
        public string OpenDate { get; set; }
        public double? SafetyAmount { get; set; }
        public double? Maintenance { get; set; }
        public double? FamilyPeason { get; set; }
        [StringLength(100)]
        public string PicturePath { get; set; }
        [StringLength(6)]
        public string ZipCode01 { get; set; }
        [StringLength(6)]
        public string ZipCode02 { get; set; }
        [StringLength(3)]
        public string DisposeBrand { get; set; }
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [StringLength(4)]
        public string ChangePeason { get; set; }
        [StringLength(100)]
        public string Email { get; set; }
        [StringLength(1)]
        public string Display { get; set; }
        [StringLength(20)]
        public string Mobil { get; set; }
        [StringLength(8)]
        public string DimissionDate { get; set; }
    }
}