// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    public partial class EmpOnDuty
    {
        [Required]
        [StringLength(4)]
        public string EmpID { get; set; }
        [Required]
        [StringLength(20)]
        public string EmpName { get; set; }
        [Required]
        [StringLength(15)]
        public string DepID { get; set; }
        [Required]
        [StringLength(20)]
        public string DepName { get; set; }
        [Key]
        [StringLength(6)]
        public string YearMonth { get; set; }
        [Key]
        public int Item { get; set; }
        [Required]
        [StringLength(1)]
        public string Day1 { get; set; }
        [Required]
        [StringLength(1)]
        public string Day2 { get; set; }
        [Required]
        [StringLength(1)]
        public string Day3 { get; set; }
        [Required]
        [StringLength(1)]
        public string Day4 { get; set; }
        [Required]
        [StringLength(1)]
        public string Day5 { get; set; }
        [Required]
        [StringLength(1)]
        public string Day6 { get; set; }
        [Required]
        [StringLength(1)]
        public string Day7 { get; set; }
        [Required]
        [StringLength(1)]
        public string Day8 { get; set; }
        [Required]
        [StringLength(1)]
        public string Day9 { get; set; }
        [Required]
        [StringLength(1)]
        public string Day10 { get; set; }
        [Required]
        [StringLength(1)]
        public string Day11 { get; set; }
        [Required]
        [StringLength(1)]
        public string Day12 { get; set; }
        [Required]
        [StringLength(1)]
        public string Day13 { get; set; }
        [Required]
        [StringLength(1)]
        public string Day14 { get; set; }
        [Required]
        [StringLength(1)]
        public string Day15 { get; set; }
        [Required]
        [StringLength(1)]
        public string Day16 { get; set; }
        [Required]
        [StringLength(1)]
        public string Day17 { get; set; }
        [Required]
        [StringLength(1)]
        public string Day18 { get; set; }
        [Required]
        [StringLength(1)]
        public string Day19 { get; set; }
        [Required]
        [StringLength(1)]
        public string Day20 { get; set; }
        [Required]
        [StringLength(1)]
        public string Day21 { get; set; }
        [Required]
        [StringLength(1)]
        public string Day22 { get; set; }
        [Required]
        [StringLength(1)]
        public string Day23 { get; set; }
        [Required]
        [StringLength(1)]
        public string Day24 { get; set; }
        [Required]
        [StringLength(1)]
        public string Day25 { get; set; }
        [Required]
        [StringLength(1)]
        public string Day26 { get; set; }
        [Required]
        [StringLength(1)]
        public string Day27 { get; set; }
        [Required]
        [StringLength(1)]
        public string Day28 { get; set; }
        [Required]
        [StringLength(1)]
        public string Day29 { get; set; }
        [Required]
        [StringLength(1)]
        public string Day30 { get; set; }
        [Required]
        [StringLength(1)]
        public string Day31 { get; set; }
        public byte TotalMorning { get; set; }
        public byte TotalNoon { get; set; }
        public byte TotalAllDay { get; set; }
        public byte TotalBreak { get; set; }
        [Required]
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [Required]
        [StringLength(4)]
        public string ChangePerson { get; set; }
        [StringLength(1)]
        public string Flag { get; set; }
        [StringLength(4)]
        public string CheckEmpID { get; set; }
        [StringLength(8)]
        public string CheckDate { get; set; }
        [StringLength(8)]
        public string DepID1 { get; set; }
        [StringLength(8)]
        public string DepID2 { get; set; }
        [StringLength(8)]
        public string DepID3 { get; set; }
        [StringLength(8)]
        public string DepID4 { get; set; }
        [StringLength(8)]
        public string DepID5 { get; set; }
        [StringLength(8)]
        public string DepID6 { get; set; }
        [StringLength(8)]
        public string DepID7 { get; set; }
        [StringLength(8)]
        public string DepID8 { get; set; }
        [StringLength(8)]
        public string DepID9 { get; set; }
        [StringLength(8)]
        public string DepID10 { get; set; }
        [StringLength(8)]
        public string DepID11 { get; set; }
        [StringLength(8)]
        public string DepID12 { get; set; }
        [StringLength(8)]
        public string DepID13 { get; set; }
        [StringLength(8)]
        public string DepID14 { get; set; }
        [StringLength(8)]
        public string DepID15 { get; set; }
        [StringLength(8)]
        public string DepID16 { get; set; }
        [StringLength(8)]
        public string DepID17 { get; set; }
        [StringLength(8)]
        public string DepID18 { get; set; }
        [StringLength(8)]
        public string DepID19 { get; set; }
        [StringLength(8)]
        public string DepID20 { get; set; }
        [StringLength(8)]
        public string DepID21 { get; set; }
        [StringLength(8)]
        public string DepID22 { get; set; }
        [StringLength(8)]
        public string DepID23 { get; set; }
        [StringLength(8)]
        public string DepID24 { get; set; }
        [StringLength(8)]
        public string DepID25 { get; set; }
        [StringLength(8)]
        public string DepID26 { get; set; }
        [StringLength(8)]
        public string DepID27 { get; set; }
        [StringLength(8)]
        public string DepID28 { get; set; }
        [StringLength(8)]
        public string DepID29 { get; set; }
        [StringLength(8)]
        public string DepID30 { get; set; }
        [StringLength(8)]
        public string DepID31 { get; set; }
    }
}