// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Keyless]
    public partial class EmpTXClock
    {
        [StringLength(5)]
        public string EmpID { get; set; }
        [StringLength(8)]
        public string ClockStore { get; set; }
        [StringLength(8)]
        public string ClockDate { get; set; }
        [StringLength(20)]
        public string ClockTime { get; set; }
        [StringLength(1)]
        public string SortFlag { get; set; }
        [StringLength(20)]
        public string ChangeTime { get; set; }
        [StringLength(20)]
        public string UPDATETime { get; set; }
    }
}