// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Keyless]
    public partial class ExcelGoods
    {
        [StringLength(255)]
        public string 型號 { get; set; }
        [StringLength(255)]
        public string 條碼 { get; set; }
        [StringLength(255)]
        public string 品名規格 { get; set; }
        [StringLength(255)]
        public string 品牌 { get; set; }
        [StringLength(255)]
        public string 廠號 { get; set; }
        [StringLength(255)]
        public string 起始進價 { get; set; }
        [StringLength(255)]
        public string 建議售價 { get; set; }
        [StringLength(255)]
        public string 廠商 { get; set; }
        [StringLength(255)]
        public string 類別一 { get; set; }
        [StringLength(255)]
        public string 類別二 { get; set; }
        [StringLength(255)]
        public string 類別三 { get; set; }
        [StringLength(255)]
        public string 類別四 { get; set; }
        [StringLength(255)]
        public string 顏色 { get; set; }
        [StringLength(255)]
        public string 季別 { get; set; }
        [StringLength(255)]
        public string 尺1 { get; set; }
        [StringLength(255)]
        public string 尺寸別 { get; set; }
        [StringLength(255)]
        public string 特價 { get; set; }
        [StringLength(255)]
        public string 批價 { get; set; }
        [StringLength(255)]
        public string 建檔日 { get; set; }
        [StringLength(255)]
        public string 備註 { get; set; }
        [StringLength(255)]
        public string 歸屬編號 { get; set; }
        [StringLength(255)]
        public string 材質一 { get; set; }
        [StringLength(255)]
        public string 材質二 { get; set; }
        [StringLength(255)]
        public string 材質三 { get; set; }
        [StringLength(255)]
        public string 材質四 { get; set; }
        [StringLength(255)]
        public string 產地 { get; set; }
    }
}