// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Keyless]
    public partial class ExcelSpecial
    {
        [Required]
        [StringLength(4)]
        public string TabelName { get; set; }
        [Required]
        [StringLength(4)]
        public string Start { get; set; }
        [Required]
        [StringLength(20)]
        public string GoodID { get; set; }
        [Required]
        [StringLength(4)]
        public string SpecialPrice { get; set; }
        [StringLength(4)]
        public string Discount { get; set; }
        public int? UnitProcess { get; set; }
    }
}