// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Index(nameof(ClassID), Name = "ClassID")]
    [Index(nameof(CountryID), Name = "CountryID")]
    [Index(nameof(FactoryName), Name = "D300B")]
    [Index(nameof(TelPhone01), Name = "D300C")]
    [Index(nameof(UniteID), Name = "UniteID")]
    public partial class Factory
    {
        [Key]
        [StringLength(10)]
        public string FactoryID { get; set; }
        [StringLength(80)]
        public string FactoryName { get; set; }
        [StringLength(40)]
        public string FactoryShort { get; set; }
        [StringLength(40)]
        public string Principal { get; set; }
        [StringLength(40)]
        public string ContactPerson { get; set; }
        [StringLength(8)]
        public string UniteID { get; set; }
        [StringLength(20)]
        public string TelPhone01 { get; set; }
        [StringLength(20)]
        public string TelPhone02 { get; set; }
        [StringLength(20)]
        public string Fax { get; set; }
        [StringLength(160)]
        public string InvoiceAddr01 { get; set; }
        [StringLength(160)]
        public string InvoiceAddr02 { get; set; }
        [StringLength(160)]
        public string InvoiceAddr03 { get; set; }
        [StringLength(160)]
        public string InvoiceAddr04 { get; set; }
        [StringLength(160)]
        public string ComAddr01 { get; set; }
        [StringLength(160)]
        public string ComAddr02 { get; set; }
        [StringLength(160)]
        public string ComAddr03 { get; set; }
        [StringLength(160)]
        public string ComAddr04 { get; set; }
        public double? TaxRate { get; set; }
        public double? Rebate { get; set; }
        public double? Ticket { get; set; }
        public double? MonthAmount01 { get; set; }
        public double? MonthAmount02 { get; set; }
        public double? MonthAmount03 { get; set; }
        public double? MonthAmount04 { get; set; }
        public double? MonthAmount05 { get; set; }
        public double? MonthAmount06 { get; set; }
        public double? MonthAmount07 { get; set; }
        public double? MonthAmount08 { get; set; }
        public double? MonthAmount09 { get; set; }
        public double? MonthAmount10 { get; set; }
        public double? MonthAmount11 { get; set; }
        public double? MonthAmount12 { get; set; }
        [StringLength(400)]
        public string Remark01 { get; set; }
        [StringLength(100)]
        public string Remark02 { get; set; }
        [StringLength(8)]
        public string OpenDate { get; set; }
        [StringLength(8)]
        public string ChangeDate { get; set; }
        public double? BeforeCope { get; set; }
        public double? AdvanceAmount { get; set; }
        [StringLength(6)]
        public string ZipCode01 { get; set; }
        [StringLength(6)]
        public string ZipCode02 { get; set; }
        [StringLength(4)]
        public string ChangePerson { get; set; }
        [StringLength(2)]
        public string ClassID { get; set; }
        [StringLength(10)]
        public string CountryID { get; set; }
        [StringLength(1)]
        public string Display { get; set; }
        [StringLength(100)]
        public string Email { get; set; }
        [StringLength(20)]
        public string Mobil { get; set; }
        [StringLength(1)]
        public string TaxMode { get; set; }
    }
}