// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Index(nameof(EmpID), Name = "TP011")]
    [Index(nameof(GoodID), Name = "TP02")]
    [Index(nameof(Date), Name = "TP03")]
    public partial class Fonus
    {
        [Key]
        [StringLength(4)]
        public string EmpID { get; set; }
        [Key]
        [StringLength(20)]
        public string GoodID { get; set; }
        [Key]
        [StringLength(8)]
        public string Date { get; set; }
        public double? Num { get; set; }
        public double? Amount { get; set; }
        [StringLength(15)]
        public string Branch { get; set; }
        [StringLength(8)]
        public string Major { get; set; }
        [StringLength(3)]
        public string Brand { get; set; }
    }
}