// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Index(nameof(CheckID), Name = "CheckID")]
    [Index(nameof(GatherID), Name = "DNA01")]
    public partial class GatherDetail
    {
        [Key]
        [StringLength(11)]
        public string GatherID { get; set; }
        [StringLength(20)]
        public string ShipID { get; set; }
        [StringLength(1)]
        public string GatherMode { get; set; }
        [StringLength(8)]
        public string ShipDate { get; set; }
        [StringLength(10)]
        public string CheckID { get; set; }
        [Column(TypeName = "money")]
        public decimal? DNA06 { get; set; }
        [Column(TypeName = "money")]
        public decimal? DNA07 { get; set; }
        [Column(TypeName = "money")]
        public decimal? DNA08 { get; set; }
        [Column(TypeName = "money")]
        public decimal? DNA09 { get; set; }
        [StringLength(3)]
        public string Brand { get; set; }
        [Key]
        [StringLength(5)]
        public string Item { get; set; }
        [StringLength(100)]
        public string Remark { get; set; }
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [StringLength(4)]
        public string ChangePerson { get; set; }
        public double? TTGatherMoney { get; set; }
        public double? TTNoGatherMoney { get; set; }
    }
}