// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    public partial class GBSMSMaintain
    {
        [Key]
        [StringLength(50)]
        public string BillCode { get; set; }
        [Key]
        [StringLength(20)]
        public string SerialID { get; set; }
    }
}