// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Index(nameof(SEQ_NO), Name = "IX_GBSMS")]
    public partial class GBSMS
    {
        [Key]
        [StringLength(20)]
        public string SerialID { get; set; }
        [StringLength(20)]
        public string Account { get; set; }
        [StringLength(20)]
        public string Password { get; set; }
        [StringLength(20)]
        public string Mobile { get; set; }
        [StringLength(200)]
        public string Msg { get; set; }
        [StringLength(20)]
        public string RES { get; set; }
        [StringLength(200)]
        public string RESMsg { get; set; }
        [StringLength(20)]
        public string SEQ_NO { get; set; }
        [StringLength(20)]
        public string SmsgoID { get; set; }
        [StringLength(20)]
        public string BillCode { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreateDate { get; set; }
    }
}