// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    public partial class GMobileUserProgram
    {
        [Key]
        [StringLength(4)]
        public string UserID { get; set; }
        [Key]
        public Guid ID { get; set; }
        [Required]
        [StringLength(1)]
        public string Checked { get; set; }
    }
}