// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    public partial class GMobileUsers
    {
        [Key]
        [StringLength(4)]
        public string UserID { get; set; }
        [Required]
        [StringLength(10)]
        public string UserPW { get; set; }
        [StringLength(15)]
        public string StoreID { get; set; }
    }
}