// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Index(nameof(GoodsID), nameof(SizeNo), nameof(Position), Name = "_1")]
    public partial class GoodsBar
    {
        [Key]
        [StringLength(50)]
        public string Bar { get; set; }
        [StringLength(20)]
        public string GoodsID { get; set; }
        [StringLength(1)]
        public string SizeNo { get; set; }
        [StringLength(2)]
        public string Position { get; set; }
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [StringLength(4)]
        public string ChangePerson { get; set; }
        public double? LimitNum { get; set; }
        [StringLength(30)]
        public string Bar1 { get; set; }
    }
}