// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Index(nameof(CardID), Name = "CardID")]
    [Index(nameof(GoodsID), nameof(Date), Name = "DAB0A")]
    [Index(nameof(Date), nameof(GoodsID), Name = "DAB0B")]
    public partial class GoodSpecial
    {
        [Key]
        [StringLength(20)]
        public string GoodsID { get; set; }
        [Key]
        [StringLength(15)]
        public string Branch { get; set; }
        [Key]
        [StringLength(8)]
        public string Date { get; set; }
        [Key]
        [StringLength(2)]
        public string CardID { get; set; }
        public double? Discount { get; set; }
        public double? SpecialPrice { get; set; }
        [StringLength(2)]
        public string DeleteSign { get; set; }
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [StringLength(4)]
        public string ChangePerson { get; set; }
        [StringLength(8)]
        public string EndDate { get; set; }
    }
}