// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Keyless]
    public partial class GoodSamplePicture
    {
        [StringLength(20)]
        public string GoodID { get; set; }
        [Column(TypeName = "image")]
        public byte[] Picture { get; set; }
    }
}