// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Index(nameof(GoodName), Name = "DA00B")]
    [Index(nameof(Brand), Name = "DA00C")]
    [Index(nameof(FactoryGoodID), Name = "FactoryGoodID")]
    public partial class Goods
    {
        [Key]
        [StringLength(20)]
        public string GoodID { get; set; }
        [StringLength(80)]
        public string GoodName { get; set; }
        [Required]
        [StringLength(10)]
        public string Brand { get; set; }
        public double? IntoPrice { get; set; }
        public double? Cost { get; set; }
        public double? Price { get; set; }
        public double? S_Ply { get; set; }
        public double? SpecialPrice { get; set; }
        public double? AdvicePrice { get; set; }
        [StringLength(1)]
        public string SizeNo1 { get; set; }
        [StringLength(1)]
        public string SizeNo2 { get; set; }
        [StringLength(1)]
        public string SizeNo3 { get; set; }
        [StringLength(8)]
        public string OpenDate { get; set; }
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [StringLength(10)]
        public string Factory { get; set; }
        [StringLength(150)]
        public string PicturePath { get; set; }
        [StringLength(8)]
        public string Sort01 { get; set; }
        [StringLength(8)]
        public string Sort02 { get; set; }
        [StringLength(8)]
        public string Sort03 { get; set; }
        [StringLength(8)]
        public string Sort04 { get; set; }
        [StringLength(8)]
        public string Sort05 { get; set; }
        [StringLength(1)]
        public string BuyMode { get; set; }
        [StringLength(4)]
        public string ChangePerson { get; set; }
        [StringLength(8)]
        public string CheapenPrice { get; set; }
        [StringLength(100)]
        public string Remark { get; set; }
        [StringLength(5)]
        public string Season { get; set; }
        [StringLength(125)]
        public string Material { get; set; }
        [StringLength(125)]
        public string InsideMaterial { get; set; }
        [StringLength(125)]
        public string FactoryGoodID { get; set; }
        [StringLength(10)]
        public string Currency { get; set; }
        public double? CurrencyRate { get; set; }
        [StringLength(1)]
        public string Display { get; set; }
        public double? I_Ply { get; set; }
        public double? BusinessChouCheng { get; set; }
        public double? shoesprice { get; set; }
        public double? otherprice { get; set; }
        public double? shly { get; set; }
        public double? oly { get; set; }
        public double? HongLiTimes { get; set; }
        [StringLength(20)]
        public string ParentID { get; set; }
        [StringLength(3)]
        public string Unit { get; set; }
        [StringLength(50)]
        public string P_StyleA { get; set; }
        [StringLength(50)]
        public string P_StyleB { get; set; }
        [StringLength(50)]
        public string P_StyleC { get; set; }
        [StringLength(50)]
        public string P_StyleD { get; set; }
        [StringLength(50)]
        public string P_StyleE { get; set; }
        [StringLength(100)]
        public string Material2 { get; set; }
        [StringLength(100)]
        public string Material3 { get; set; }
        [StringLength(100)]
        public string Material1 { get; set; }
        [StringLength(100)]
        public string Production { get; set; }
        [StringLength(24)]
        public string StDate { get; set; }
        [StringLength(100)]
        public string BrandMADE { get; set; }
        [StringLength(1)]
        public string IsSample { get; set; }
        [StringLength(10)]
        public string weight { get; set; }
        [StringLength(150)]
        public string PicturePath1 { get; set; }
        [StringLength(150)]
        public string PicturePath2 { get; set; }
        [StringLength(150)]
        public string PicturePath3 { get; set; }
        [StringLength(150)]
        public string openfile1 { get; set; }
        [StringLength(150)]
        public string openfile2 { get; set; }
        [StringLength(200)]
        public string GoodsFormat { get; set; }
        [StringLength(2)]
        public string CheckSize1 { get; set; }
        [StringLength(2)]
        public string CheckSize2 { get; set; }
        [StringLength(50)]
        public string P_StyleF { get; set; }
        [StringLength(100)]
        public string Da_StyleA { get; set; }
        [StringLength(100)]
        public string Da_StyleB { get; set; }
        [StringLength(100)]
        public string Da_StyleC { get; set; }
        [StringLength(100)]
        public string Da_StyleD { get; set; }
        [StringLength(100)]
        public string Da_StyleE { get; set; }
        [StringLength(100)]
        public string Da_StyleF { get; set; }
        [StringLength(1)]
        public string IsStruct { get; set; }
        [StringLength(100)]
        public string Material4 { get; set; }
        [StringLength(1)]
        public string NoWebFlag { get; set; }
        [StringLength(100)]
        public string P_StyleG { get; set; }
        [StringLength(100)]
        public string P_StyleH { get; set; }
        [StringLength(1)]
        public string DelayFlag { get; set; }
        [StringLength(20)]
        public string DelayGoods { get; set; }
        [StringLength(8)]
        public string DelayDate { get; set; }
        [StringLength(1)]
        public string EmpFlag { get; set; }
        [StringLength(100)]
        public string Da_StyleG { get; set; }
        [StringLength(70)]
        public string WayNo { get; set; }
        [StringLength(20)]
        public string WayNo_A { get; set; }
        [StringLength(20)]
        public string WayNo_B { get; set; }
        [StringLength(20)]
        public string WayNo_C { get; set; }
        [StringLength(20)]
        public string WayNo_D { get; set; }
        [StringLength(1)]
        public string CheckCost { get; set; }
        [Column(TypeName = "decimal(18, 6)")]
        public decimal? TradePrice1 { get; set; }
        [Column(TypeName = "decimal(18, 6)")]
        public decimal? TradePrice2 { get; set; }
        [Column(TypeName = "decimal(18, 6)")]
        public decimal? TradePrice3 { get; set; }
        public double? ply { get; set; }
        public double? PriceA { get; set; }
        public double? PriceB { get; set; }
        public double? PriceC { get; set; }
        public double? PriceD { get; set; }
        public double? PriceE { get; set; }
        public double? ActivePrice { get; set; }
        [StringLength(200)]
        public string RemarkNew { get; set; }
    }
}