// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Index(nameof(GoodName), Name = "DA00B")]
    [Index(nameof(Brand), Name = "DA00C")]
    [Index(nameof(FactoryGoodID), Name = "FactoryGoodID")]
    public partial class GoodsSample
    {
        [Key]
        [StringLength(20)]
        public string GoodID { get; set; }
        [StringLength(80)]
        public string GoodName { get; set; }
        [StringLength(10)]
        public string Brand { get; set; }
        public double? IntoPrice { get; set; }
        public double? Cost { get; set; }
        public double? Price { get; set; }
        public double? Ply { get; set; }
        public double? SpecialPrice { get; set; }
        public double? AdvicePrice { get; set; }
        [StringLength(1)]
        public string SizeNo1 { get; set; }
        [StringLength(1)]
        public string SizeNo2 { get; set; }
        [StringLength(1)]
        public string SizeNo3 { get; set; }
        [StringLength(8)]
        public string OpenDate { get; set; }
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [StringLength(10)]
        public string Factory { get; set; }
        [StringLength(50)]
        public string PicturePath { get; set; }
        [StringLength(8)]
        public string Sort01 { get; set; }
        [StringLength(8)]
        public string Sort02 { get; set; }
        [StringLength(8)]
        public string Sort03 { get; set; }
        [StringLength(8)]
        public string Sort04 { get; set; }
        [StringLength(8)]
        public string Sort05 { get; set; }
        [StringLength(1)]
        public string BuyMode { get; set; }
        [StringLength(4)]
        public string ChangePerson { get; set; }
        [StringLength(8)]
        public string CheapenPrice { get; set; }
        [StringLength(100)]
        public string Remark { get; set; }
        [StringLength(5)]
        public string Season { get; set; }
        [StringLength(10)]
        public string Material { get; set; }
        [StringLength(20)]
        public string InsideMaterial { get; set; }
        [StringLength(20)]
        public string FactoryGoodID { get; set; }
        [StringLength(10)]
        public string Currency { get; set; }
        public double? CurrencyRate { get; set; }
        [StringLength(1)]
        public string Sign { get; set; }
        [StringLength(1)]
        public string Display { get; set; }
    }
}