// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    public partial class Infonation
    {
        [Required]
        [StringLength(20)]
        public string OccDate { get; set; }
        [Required]
        [StringLength(400)]
        public string InfoText { get; set; }
        [Required]
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [Required]
        [StringLength(4)]
        public string ChangePerson { get; set; }
        [Key]
        public int InfoID { get; set; }
        [Required]
        [StringLength(8)]
        public string SDate { get; set; }
        [Required]
        [StringLength(8)]
        public string EDate { get; set; }
        [Required]
        [StringLength(15)]
        public string RStoreID { get; set; }
    }
}