// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    public partial class InvoiceSet
    {
        [Required]
        [StringLength(11)]
        public string SerialID { get; set; }
        [Key]
        [StringLength(6)]
        public string InvoiceMonth { get; set; }
        [Required]
        [StringLength(20)]
        public string Store { get; set; }
        [Required]
        [StringLength(2)]
        public string OBU { get; set; }
        [Key]
        [StringLength(8)]
        public string MinInvoice { get; set; }
        [Required]
        [StringLength(8)]
        public string MaxInvoice { get; set; }
        [Column(TypeName = "decimal(18, 0)")]
        public decimal Curls { get; set; }
        [StringLength(8)]
        public string InvoiceID { get; set; }
        [Required]
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [Required]
        [StringLength(4)]
        public string ChangePerson { get; set; }
        [StringLength(1)]
        public string MachineNo { get; set; }
        [StringLength(1)]
        public string MachineID { get; set; }
        [StringLength(10)]
        public string Version { get; set; }
        [StringLength(100)]
        public string qrApiKey { get; set; }
        [StringLength(100)]
        public string AppID { get; set; }
        [StringLength(5)]
        public string InvTerm { get; set; }
    }
}