// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    public partial class KTJTitle
    {
        [Key]
        [StringLength(8)]
        public string SDate { get; set; }
        [Key]
        [StringLength(9)]
        public string IDOld { get; set; }
        [Required]
        [StringLength(10)]
        public string IDNew { get; set; }
        public float Item { get; set; }
        [Required]
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [Required]
        [StringLength(4)]
        public string ChangePerson { get; set; }
    }
}