// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Keyless]
    public partial class LogOutEInvALLCancelNo
    {
        [Required]
        [StringLength(20)]
        public string InvNum { get; set; }
        [Required]
        [StringLength(20)]
        public string SellID { get; set; }
        public double Mey { get; set; }
        [Required]
        [StringLength(200)]
        public string Remark { get; set; }
        [Required]
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [Required]
        [StringLength(8)]
        public string ChangePerson { get; set; }
    }
}