// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Index(nameof(CommID), Name = "CommID")]
    [Index(nameof(FactoryID), Name = "FactoryID")]
    [Index(nameof(InStoreID), Name = "InSotreID")]
    [Index(nameof(MaterialID), Name = "MaterialID")]
    [Index(nameof(CommDate), Name = "P703")]
    [Index(nameof(FactoryName), Name = "P705")]
    [Index(nameof(ProcessID), Name = "ProcessID")]
    [Index(nameof(ProduceID), Name = "ProduceID")]
    public partial class MCommInStore
    {
        [Key]
        [StringLength(13)]
        public string CommID { get; set; }
        [StringLength(1)]
        public string CommMode { get; set; }
        [StringLength(8)]
        public string CommDate { get; set; }
        [StringLength(10)]
        public string FactoryID { get; set; }
        [StringLength(50)]
        public string FactoryName { get; set; }
        [Key]
        [StringLength(3)]
        public string Item { get; set; }
        [StringLength(20)]
        public string MaterialID { get; set; }
        [StringLength(50)]
        public string MaterialName { get; set; }
        [StringLength(4)]
        public string FillPerson { get; set; }
        [StringLength(2)]
        public string SizeNo { get; set; }
        public double? CommNum01 { get; set; }
        public double? CommNum02 { get; set; }
        public double? CommNum03 { get; set; }
        public double? CommNum04 { get; set; }
        public double? CommNum05 { get; set; }
        public double? CommNum06 { get; set; }
        public double? CommNum07 { get; set; }
        public double? CommNum08 { get; set; }
        public double? CommNum09 { get; set; }
        public double? CommNum10 { get; set; }
        public double? CommNum11 { get; set; }
        public double? CommNum12 { get; set; }
        public double? CommNum13 { get; set; }
        public double? CommNum14 { get; set; }
        public double? CommNum15 { get; set; }
        public double? CommNum16 { get; set; }
        public double? CommNum17 { get; set; }
        public double? CommNumTotal { get; set; }
        public double? Price { get; set; }
        public double? CommAmount { get; set; }
        [StringLength(13)]
        public string ProduceID { get; set; }
        [StringLength(3)]
        public string ProduceItem { get; set; }
        [StringLength(2)]
        public string ProcessID { get; set; }
        [StringLength(50)]
        public string ProcessName { get; set; }
        [StringLength(4)]
        public string ChangePerson { get; set; }
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [StringLength(20)]
        public string InStoreID { get; set; }
    }
}