// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Index(nameof(ProduceDate), Name = "DXD02")]
    [Index(nameof(GoodID), Name = "DXD03")]
    [Index(nameof(FactoryID), Name = "FactoryID")]
    [Index(nameof(OutStore), Name = "P705")]
    [Index(nameof(Item), Name = "P8A25")]
    [Index(nameof(PreProduceID), Name = "PreProduceID")]
    [Index(nameof(ProcessID), Name = "ProcessID")]
    [Index(nameof(ProduceID), Name = "ProduceID")]
    [Index(nameof(SortID), Name = "SortID")]
    public partial class MCommProduce
    {
        [Key]
        [StringLength(13)]
        public string ProduceID { get; set; }
        [StringLength(8)]
        public string ProduceDate { get; set; }
        [StringLength(20)]
        public string GoodID { get; set; }
        [StringLength(2)]
        public string SizeNO { get; set; }
        public double? ProduceNum01 { get; set; }
        public double? ProduceNum02 { get; set; }
        public double? ProduceNum03 { get; set; }
        public double? ProduceNum04 { get; set; }
        public double? ProduceNum05 { get; set; }
        public double? ProduceNum06 { get; set; }
        public double? ProduceNum07 { get; set; }
        public double? ProduceNum08 { get; set; }
        public double? ProduceNum09 { get; set; }
        public double? ProduceNum10 { get; set; }
        public double? ProduceNum11 { get; set; }
        public double? ProduceNum12 { get; set; }
        public double? ProduceNum13 { get; set; }
        public double? ProduceNum14 { get; set; }
        public double? ProduceNum15 { get; set; }
        public double? ProduceNum16 { get; set; }
        public double? ProduceNum17 { get; set; }
        public double? ProduceNumTotal { get; set; }
        [StringLength(20)]
        public string Remark { get; set; }
        [StringLength(1)]
        public string FinishFlag { get; set; }
        [Key]
        [StringLength(3)]
        public string Item { get; set; }
        [StringLength(4)]
        public string ChangePerson { get; set; }
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [StringLength(15)]
        public string OutStore { get; set; }
        [StringLength(4)]
        public string FillPerson { get; set; }
        [StringLength(13)]
        public string ProduceUnit { get; set; }
        [StringLength(20)]
        public string FactoryID { get; set; }
        [StringLength(13)]
        public string PreProduceID { get; set; }
        [StringLength(50)]
        public string FactoryName { get; set; }
        [StringLength(8)]
        public string SendDate { get; set; }
        [StringLength(8)]
        public string EstDate { get; set; }
        [StringLength(1)]
        public string ProduceFlag { get; set; }
        [StringLength(2)]
        public string ProcessID { get; set; }
        [StringLength(20)]
        public string ProcessName { get; set; }
        [StringLength(1)]
        public string SendFlag { get; set; }
        [StringLength(1)]
        public string InStoreFlag { get; set; }
        public double? ProPrice { get; set; }
        [StringLength(3)]
        public string SortID { get; set; }
    }
}