// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    public partial class MemberLv
    {
        [Key]
        [StringLength(20)]
        public string MemberID { get; set; }
        [Key]
        [StringLength(8)]
        public string SellDate { get; set; }
        [Key]
        [StringLength(10)]
        public string Mode { get; set; }
        [Required]
        [StringLength(5)]
        public string CardID { get; set; }
        [Required]
        [StringLength(5)]
        public string CardIDNew { get; set; }
        [Required]
        [StringLength(8)]
        public string contactaddr4 { get; set; }
        [Required]
        [StringLength(8)]
        public string effectdate { get; set; }
        [Required]
        [StringLength(8)]
        public string contactaddr4New { get; set; }
        [Required]
        [StringLength(8)]
        public string effectdateNew { get; set; }
        public double AmountNew { get; set; }
    }
}