// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Index(nameof(CardID), Name = "CardID")]
    public partial class MemberCard
    {
        [Key]
        [StringLength(2)]
        public string CardID { get; set; }
        [StringLength(20)]
        public string CardName { get; set; }
        public double? Discount { get; set; }
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [StringLength(4)]
        public string ChangePerson { get; set; }
        public double? Amount { get; set; }
        [StringLength(10)]
        public string BrandID { get; set; }
        [StringLength(1)]
        public string Mode { get; set; }
        [StringLength(1)]
        public string PointMode { get; set; }
        public double? SingleAmount { get; set; }
        public double? ContinueAmount { get; set; }
        [StringLength(20)]
        public string WayCardID { get; set; }
        [StringLength(1)]
        public string BirthMode { get; set; }
        [StringLength(1)]
        public string BirthWay { get; set; }
        [StringLength(1)]
        public string BirthSort { get; set; }
        public double? BirthDiscount { get; set; }
        public double? BirthAmount { get; set; }
        public double? BirthCount { get; set; }
        public double? BirthUseAmount { get; set; }
        [StringLength(20)]
        public string Card91ID { get; set; }
    }
}