// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Index(nameof(Date), Name = "DXD02")]
    [Index(nameof(GoodID), Name = "DXD03")]
    [Index(nameof(StoreID), Name = "P705")]
    public partial class MemberWork
    {
        [Key]
        [StringLength(13)]
        public string WorkID { get; set; }
        [StringLength(8)]
        public string Date { get; set; }
        [StringLength(20)]
        public string GoodID { get; set; }
        [StringLength(2)]
        public string SizeNo { get; set; }
        public double? WorkNum01 { get; set; }
        public double? WorkNum02 { get; set; }
        public double? WorkNum03 { get; set; }
        public double? WorkNum04 { get; set; }
        public double? WorkNum05 { get; set; }
        public double? WorkNum06 { get; set; }
        public double? WorkNum07 { get; set; }
        public double? WorkNum08 { get; set; }
        public double? WorkNum09 { get; set; }
        public double? WorkNum10 { get; set; }
        public double? WorkNum11 { get; set; }
        public double? WorkNum12 { get; set; }
        public double? WorkNum13 { get; set; }
        public double? WorkNum14 { get; set; }
        public double? WorkNum15 { get; set; }
        public double? WorkNum16 { get; set; }
        public double? WorkNum17 { get; set; }
        public double? WorkTotalNum { get; set; }
        [StringLength(20)]
        public string Remark { get; set; }
        [StringLength(1)]
        public string FinishMode { get; set; }
        [Key]
        [StringLength(3)]
        public string Item { get; set; }
        [StringLength(4)]
        public string ChangePerson { get; set; }
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [StringLength(15)]
        public string StoreID { get; set; }
        [StringLength(4)]
        public string FillPerson { get; set; }
        [StringLength(13)]
        public string WorkSpace { get; set; }
        [StringLength(1)]
        public string WordMode { get; set; }
        [StringLength(2)]
        public string P832 { get; set; }
        [StringLength(20)]
        public string P833 { get; set; }
        [StringLength(1)]
        public string OrderMode { get; set; }
        [StringLength(1)]
        public string IntoMode { get; set; }
        public double? Price { get; set; }
        [StringLength(20)]
        public string WorkPersonID { get; set; }
        [StringLength(8)]
        public string SortID { get; set; }
        [StringLength(13)]
        public string PreWorkID { get; set; }
        [StringLength(50)]
        public string WorkPerson { get; set; }
        [StringLength(8)]
        public string OrderDate { get; set; }
        [StringLength(8)]
        public string PreWorkDate { get; set; }
        [StringLength(1)]
        public string Sign { get; set; }
    }
}