// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Index(nameof(PurchaseID), Name = "DFA0A")]
    [Index(nameof(GoodID), Name = "DFA0B")]
    public partial class MemberOrder
    {
        [Key]
        [StringLength(20)]
        public string PurchaseID { get; set; }
        [StringLength(20)]
        public string MemberID { get; set; }
        [StringLength(40)]
        public string MemberName { get; set; }
        [StringLength(20)]
        public string GoodID { get; set; }
        [StringLength(1)]
        public string SizeNo { get; set; }
        [StringLength(8)]
        public string SizeName { get; set; }
        public int? SizePosition { get; set; }
        public double? OrderNum1 { get; set; }
        public int? OrderNum2 { get; set; }
        public int? OrderNum3 { get; set; }
        public int? OrderNum4 { get; set; }
        public int? OrderNum5 { get; set; }
        public int? OrderNum6 { get; set; }
        public int? OrderNum7 { get; set; }
        public int? OrderNum8 { get; set; }
        public int? OrderNum9 { get; set; }
        public int? OrderNum10 { get; set; }
        public int? OrderNum11 { get; set; }
        public int? OrderNum12 { get; set; }
        public int? OrderNum13 { get; set; }
        public int? OrderNum14 { get; set; }
        public int? OrderNum15 { get; set; }
        public int? OrderNum16 { get; set; }
        public int? OrderNum17 { get; set; }
        public int? TotalOrderNum { get; set; }
        public int? TakeNum { get; set; }
        public int? OrderPrice { get; set; }
        public double? OrderAmount { get; set; }
        [StringLength(1)]
        public string DealFlag { get; set; }
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [StringLength(50)]
        public string ChangePerson { get; set; }
        [StringLength(3)]
        public string SellItem { get; set; }
        [Key]
        [StringLength(3)]
        public string PurchaseItem { get; set; }
        public double? OrderNoPay { get; set; }
        public double? Discount { get; set; }
        public double? GetAmt { get; set; }
        [StringLength(8)]
        public string OrderID { get; set; }
    }
}