// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Index(nameof(MemberName), Name = "D400B")]
    [Index(nameof(TelPhone01), Name = "D400C")]
    public partial class Member
    {
        [Key]
        [StringLength(20)]
        public string MemberID { get; set; }
        [StringLength(1)]
        public string Sex { get; set; }
        [StringLength(20)]
        public string MemberName { get; set; }
        [StringLength(8)]
        public string Brith { get; set; }
        [StringLength(15)]
        public string FirstStore { get; set; }
        [StringLength(20)]
        public string TelPhone01 { get; set; }
        [StringLength(20)]
        public string TelPhone02 { get; set; }
        [StringLength(160)]
        public string ContactAddr1 { get; set; }
        [StringLength(160)]
        public string ContactAddr2 { get; set; }
        [StringLength(160)]
        public string ContactAddr3 { get; set; }
        [StringLength(160)]
        public string ContactAddr4 { get; set; }
        [StringLength(160)]
        public string CensusAddr1 { get; set; }
        [StringLength(160)]
        public string CensusAddr2 { get; set; }
        [StringLength(160)]
        public string CensusAddr3 { get; set; }
        [StringLength(160)]
        public string CensusAddr4 { get; set; }
        [StringLength(8)]
        public string OpenDate { get; set; }
        [StringLength(8)]
        public string EffectDate { get; set; }
        [StringLength(100)]
        public string Remark { get; set; }
        [StringLength(10)]
        public string Brand01 { get; set; }
        [StringLength(10)]
        public string Brand02 { get; set; }
        [StringLength(10)]
        public string Brand03 { get; set; }
        public double? Amount { get; set; }
        public double? Tax { get; set; }
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [StringLength(6)]
        public string ZipID01 { get; set; }
        [StringLength(6)]
        public string ZipID02 { get; set; }
        [StringLength(4)]
        public string ChangePerson { get; set; }
        [StringLength(100)]
        public string Email { get; set; }
        [StringLength(2)]
        public string CardClass { get; set; }
        [StringLength(20)]
        public string Major { get; set; }
        [StringLength(1)]
        public string PrintFlag { get; set; }
        [StringLength(1)]
        public string Display { get; set; }
        public double? CreditLimit { get; set; }
        [StringLength(20)]
        public string IdCard { get; set; }
        [StringLength(20)]
        public string Mobil { get; set; }
        public short? Son { get; set; }
        public short? Daughter { get; set; }
        [StringLength(2)]
        public string Married { get; set; }
        [StringLength(8)]
        public string ShowDate { get; set; }
        [StringLength(10)]
        public string SDName1 { get; set; }
        [StringLength(8)]
        public string SDBirthday1 { get; set; }
        [StringLength(10)]
        public string SDName2 { get; set; }
        [StringLength(8)]
        public string SDBirthday2 { get; set; }
        [StringLength(10)]
        public string SDName3 { get; set; }
        [StringLength(8)]
        public string SDBirthday3 { get; set; }
        [StringLength(10)]
        public string SDName4 { get; set; }
        [StringLength(8)]
        public string SDBirthday4 { get; set; }
        [StringLength(6)]
        public string EduLevel { get; set; }
        [StringLength(7)]
        public string BrandKnow { get; set; }
        [StringLength(6)]
        public string BuyGood { get; set; }
        [StringLength(2)]
        public string BuyMode { get; set; }
        [StringLength(7)]
        public string WhereToBuy { get; set; }
        [StringLength(6)]
        public string WhichToAdd { get; set; }
        [StringLength(5)]
        public string Advice { get; set; }
        [StringLength(8)]
        public string CheckDate { get; set; }
        [StringLength(6)]
        public string Condition { get; set; }
        [StringLength(10)]
        public string CardPerson { get; set; }
        public double? HongLi { get; set; }
        public double? SubHongLi { get; set; }
        public double? PeriodAmount { get; set; }
        [StringLength(20)]
        public string MemEmpID { get; set; }
        [StringLength(20)]
        public string Card91ID { get; set; }
    }
}