// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Index(nameof(EmpID), Name = "EmpID")]
    [Index(nameof(MaterialID), Name = "MaterialID")]
    [Index(nameof(EmpInDate), Name = "P703")]
    [Index(nameof(EmpName), Name = "P705")]
    [Index(nameof(ProcessID), Name = "ProcessID")]
    [Index(nameof(ProduceID), Name = "ProduceID")]
    [Index(nameof(StoreID), Name = "StoreID")]
    public partial class MEmpInStore
    {
        [Key]
        [StringLength(13)]
        public string EmpInID { get; set; }
        [StringLength(1)]
        public string EmpInMode { get; set; }
        [StringLength(8)]
        public string EmpInDate { get; set; }
        [StringLength(8)]
        public string EmpID { get; set; }
        [StringLength(8)]
        public string EmpName { get; set; }
        [Key]
        [StringLength(3)]
        public string Item { get; set; }
        [StringLength(20)]
        public string MaterialID { get; set; }
        [StringLength(4)]
        public string FillPerson { get; set; }
        [StringLength(2)]
        public string SizeNo { get; set; }
        public double? EmpInNum01 { get; set; }
        public double? EmpInNum02 { get; set; }
        public double? EmpInNum03 { get; set; }
        public double? EmpInNum04 { get; set; }
        public double? EmpInNum05 { get; set; }
        public double? EmpInNum06 { get; set; }
        public double? EmpInNum07 { get; set; }
        public double? EmpInNum08 { get; set; }
        public double? EmpInNum09 { get; set; }
        public double? EmpInNum10 { get; set; }
        public double? EmpInNum11 { get; set; }
        public double? EmpInNum12 { get; set; }
        public double? EmpInNum13 { get; set; }
        public double? EmpInNum14 { get; set; }
        public double? EmpInNum15 { get; set; }
        public double? EmpInNum16 { get; set; }
        public double? EmpInNum17 { get; set; }
        public double? EmpInNumTotal { get; set; }
        public double? EmpInPrice { get; set; }
        public double? EmpInAmount { get; set; }
        [StringLength(13)]
        public string ProduceID { get; set; }
        [StringLength(3)]
        public string ProduceItem { get; set; }
        [StringLength(2)]
        public string ProcessID { get; set; }
        [StringLength(50)]
        public string ProcessName { get; set; }
        [StringLength(4)]
        public string ChangePerson { get; set; }
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [StringLength(15)]
        public string StoreID { get; set; }
        [StringLength(50)]
        public string MaterialName { get; set; }
    }
}