// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Index(nameof(CheckID), Name = "CheckID")]
    [Index(nameof(GatherDate), Name = "DN02")]
    [Index(nameof(CustID), Name = "DN03")]
    [Index(nameof(DN05), Name = "DN05")]
    [Index(nameof(GatherPerson), Name = "DN08")]
    [Index(nameof(EndBrandID), Name = "EndBrandID")]
    [Index(nameof(StartBrandID), Name = "StartBrandID")]
    public partial class MGather
    {
        [Key]
        [StringLength(11)]
        public string GatherID { get; set; }
        [StringLength(8)]
        public string GatherDate { get; set; }
        [StringLength(15)]
        public string CustID { get; set; }
        [StringLength(9)]
        public string CheckID { get; set; }
        [StringLength(8)]
        public string DN05 { get; set; }
        [Column(TypeName = "money")]
        public decimal? DN06 { get; set; }
        [Column(TypeName = "money")]
        public decimal? DN07 { get; set; }
        [StringLength(4)]
        public string GatherPerson { get; set; }
        [StringLength(30)]
        public string GatherBank { get; set; }
        [StringLength(40)]
        public string GatherAccount { get; set; }
        [Column(TypeName = "money")]
        public decimal? DN11 { get; set; }
        [Column(TypeName = "money")]
        public decimal? DN12 { get; set; }
        [Column(TypeName = "money")]
        public decimal? DN13 { get; set; }
        [Column(TypeName = "money")]
        public decimal? DN14 { get; set; }
        [Column(TypeName = "money")]
        public decimal? DN15 { get; set; }
        [StringLength(10)]
        public string StartBrandID { get; set; }
        [StringLength(10)]
        public string EndBrandID { get; set; }
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [StringLength(4)]
        public string ChangePerson { get; set; }
        [StringLength(100)]
        public string Remark { get; set; }
    }
}