// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Keyless]
    public partial class MidPov232Tmp
    {
        [StringLength(15)]
        public string ClientID { get; set; }
        [StringLength(80)]
        public string ClientName { get; set; }
        [StringLength(20)]
        public string SellID { get; set; }
        [StringLength(16)]
        public string CreditID { get; set; }
        [StringLength(15)]
        public string UniteID { get; set; }
        [StringLength(1)]
        public string CancelFlag { get; set; }
        [StringLength(15)]
        public string BranchID { get; set; }
        [StringLength(20)]
        public string InvoiceID { get; set; }
        [StringLength(8)]
        public string InvoiceDate { get; set; }
        [StringLength(10)]
        public string Kind { get; set; }
        [StringLength(2)]
        public string KindID { get; set; }
        public double? NoTax { get; set; }
        public double? Tax { get; set; }
        public double? TotalAmount { get; set; }
        public double? TotalCash { get; set; }
        public double? TotalCard { get; set; }
        public double? TotalGift { get; set; }
    }
}