// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Keyless]
    public partial class MidShipTableATmp
    {
        [StringLength(20)]
        public string GoodID { get; set; }
        [StringLength(80)]
        public string GoodName { get; set; }
        [StringLength(15)]
        public string StoreID { get; set; }
        [StringLength(80)]
        public string StoreName { get; set; }
        [StringLength(8)]
        public string Class1ID { get; set; }
        [StringLength(40)]
        public string Class1Name { get; set; }
        [StringLength(8)]
        public string Class2ID { get; set; }
        [StringLength(40)]
        public string Class2Name { get; set; }
        [StringLength(8)]
        public string Class3ID { get; set; }
        [StringLength(40)]
        public string Class3Name { get; set; }
        [StringLength(8)]
        public string Class4ID { get; set; }
        [StringLength(40)]
        public string Class4Name { get; set; }
        [StringLength(8)]
        public string Class5ID { get; set; }
        [StringLength(40)]
        public string Class5Name { get; set; }
        [StringLength(10)]
        public string BrandID { get; set; }
        [StringLength(100)]
        public string BrandName { get; set; }
        [Required]
        [StringLength(1)]
        public string Flag { get; set; }
        public double? ShipDiscount { get; set; }
        public int SellNum { get; set; }
        public double SellAmount { get; set; }
        [StringLength(6)]
        public string FormName { get; set; }
        [StringLength(12)]
        public string UserID { get; set; }
    }
}