// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Index(nameof(SizeNo), Name = "ShelfID")]
    public partial class MMaterialStore
    {
        [Key]
        [StringLength(20)]
        public string MaterialID { get; set; }
        [Key]
        [StringLength(15)]
        public string StoreID { get; set; }
        [Key]
        [StringLength(5)]
        public string SizeNo { get; set; }
        public double? StorageNum01 { get; set; }
        public double? StorageNum02 { get; set; }
        public double? StorageNum03 { get; set; }
        public double? StorageNum04 { get; set; }
        public double? StorageNum05 { get; set; }
        public double? StorageNum06 { get; set; }
        public double? StorageNum07 { get; set; }
        public double? StorageNum08 { get; set; }
        public double? StorageNum09 { get; set; }
        public double? StorageNum10 { get; set; }
        public double? StorageNum11 { get; set; }
        public double? StorageNum12 { get; set; }
        public double? StorageNum13 { get; set; }
        public double? StorageNum14 { get; set; }
        public double? StorageNum15 { get; set; }
        public double? StorageNum16 { get; set; }
        public double? StorageNum17 { get; set; }
        public double? StorageNumTotal { get; set; }
        public double? StockNum01 { get; set; }
        public double? StockNum02 { get; set; }
        public double? StockNum03 { get; set; }
        public double? StockNum04 { get; set; }
        public double? StockNum05 { get; set; }
        public double? StockNum06 { get; set; }
        public double? StockNum07 { get; set; }
        public double? StockNum08 { get; set; }
        public double? StockNum09 { get; set; }
        public double? StockNum10 { get; set; }
        public double? StockNum11 { get; set; }
        public double? StockNum12 { get; set; }
        public double? StockNum13 { get; set; }
        public double? StockNum14 { get; set; }
        public double? StockNum15 { get; set; }
        public double? StockNum16 { get; set; }
        public double? StockNum17 { get; set; }
        public double? StockTotalNum { get; set; }
        [StringLength(15)]
        public string Store { get; set; }
        [StringLength(1)]
        public string StorageSign { get; set; }
        [StringLength(5)]
        public string StoreShelfID { get; set; }
    }
}