// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Index(nameof(FactoryID), Name = "FactoryID")]
    [Index(nameof(ProcessID), Name = "ProcessID")]
    [Index(nameof(SortID), Name = "SortID")]
    public partial class MMaterialStruct
    {
        [Key]
        [StringLength(25)]
        public string MainMaterialID { get; set; }
        [StringLength(1)]
        public string SizeNo { get; set; }
        [StringLength(2)]
        public string SizeX { get; set; }
        [Key]
        [StringLength(20)]
        public string MaterialID { get; set; }
        public double? MaterialNum { get; set; }
        public double? Price { get; set; }
        public double? Amount { get; set; }
        [StringLength(10)]
        public string FactoryID { get; set; }
        [StringLength(4)]
        public string ProcessID { get; set; }
        public double? Size01 { get; set; }
        public double? Size02 { get; set; }
        public double? Size03 { get; set; }
        public double? Size04 { get; set; }
        public double? Size05 { get; set; }
        public double? Size06 { get; set; }
        public double? Size07 { get; set; }
        public double? Size08 { get; set; }
        public double? Size09 { get; set; }
        public double? Size10 { get; set; }
        public double? Size11 { get; set; }
        public double? Size12 { get; set; }
        public double? Size13 { get; set; }
        public double? Size14 { get; set; }
        public double? Size15 { get; set; }
        public double? Size16 { get; set; }
        public double? Size17 { get; set; }
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [StringLength(4)]
        public string ChangePerson { get; set; }
        [StringLength(8)]
        public string SortID { get; set; }
        [StringLength(10)]
        public string Remark { get; set; }
    }
}