// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Keyless]
    public partial class Mms208Tmp
    {
        [StringLength(1)]
        public string Flag { get; set; }
        [StringLength(15)]
        public string ClientID { get; set; }
        [StringLength(15)]
        public string StoreID { get; set; }
        [StringLength(20)]
        public string GoodID { get; set; }
        [StringLength(1)]
        public string SizeNo { get; set; }
        public double? Num01 { get; set; }
        public double? Num02 { get; set; }
        public double? Num03 { get; set; }
        public double? Num04 { get; set; }
        public double? Num05 { get; set; }
        public double? Num06 { get; set; }
        public double? Num07 { get; set; }
        public double? Num08 { get; set; }
        public double? Num09 { get; set; }
        public double? Num10 { get; set; }
        public double? Num11 { get; set; }
        public double? Num12 { get; set; }
        public double? Num13 { get; set; }
        public double? Num14 { get; set; }
        public double? Num15 { get; set; }
        public double? Num16 { get; set; }
        public double? Num17 { get; set; }
        public double? TotalNum { get; set; }
        public double? Price { get; set; }
        public double? Discount { get; set; }
        public double? OrderPrice { get; set; }
        [StringLength(1)]
        public string OrderMode { get; set; }
        [StringLength(4)]
        public string Operation { get; set; }
        [StringLength(13)]
        public string OrderID { get; set; }
        [StringLength(3)]
        public string OrderItem { get; set; }
        [StringLength(13)]
        public string FootID { get; set; }
        [StringLength(3)]
        public string FinishFlag { get; set; }
        public double? BeforeAcc { get; set; }
        [StringLength(8)]
        public string DealDate { get; set; }
        [StringLength(10)]
        public string UserID { get; set; }
        [StringLength(9)]
        public string R1 { get; set; }
        [StringLength(20)]
        public string CNAME { get; set; }
        [StringLength(1)]
        public string CancelFlag { get; set; }
        [StringLength(1)]
        public string TaxMode { get; set; }
        public double? TaxPercent { get; set; }
        public double? Non_Tax { get; set; }
        [StringLength(8)]
        public string DealModeID { get; set; }
        [StringLength(100)]
        public string GoodName { get; set; }
    }
}