// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Keyless]
    public partial class Mms302Temp
    {
        [Required]
        [StringLength(20)]
        public string GoodID { get; set; }
        public double? Num1 { get; set; }
        public double? Num2 { get; set; }
        public double? Num3 { get; set; }
        public double? Num4 { get; set; }
        public double? Num5 { get; set; }
        public double? Num6 { get; set; }
        public double? Num7 { get; set; }
        public double? Num8 { get; set; }
        public double? Num9 { get; set; }
        public double? Num10 { get; set; }
        public double? Num11 { get; set; }
        public double? Num12 { get; set; }
        public double? Num13 { get; set; }
        public double? Num14 { get; set; }
        public double? Num15 { get; set; }
        public double? Num16 { get; set; }
        public double? Num17 { get; set; }
        public double? NumTotal { get; set; }
        [Required]
        [StringLength(4)]
        public string UserID { get; set; }
    }
}