// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Keyless]
    public partial class Mms5082Detailtmp
    {
        [StringLength(10)]
        public string UserID { get; set; }
        public int? SortID { get; set; }
        [StringLength(10)]
        public string TP01 { get; set; }
        [StringLength(8)]
        public string TP02 { get; set; }
        [StringLength(13)]
        public string TP03 { get; set; }
        public int? TP04 { get; set; }
        [Column(TypeName = "money")]
        public decimal? TP05 { get; set; }
        [Column(TypeName = "money")]
        public decimal? TP06 { get; set; }
        [StringLength(100)]
        public string TP07 { get; set; }
        public Guid? AutoID { get; set; }
    }
}