// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Keyless]
    public partial class Mms611Temp
    {
        [StringLength(50)]
        public string Names { get; set; }
        public double? Month1Money { get; set; }
        public double? Month2Money { get; set; }
        public double? Month3Money { get; set; }
        public double? Month4Money { get; set; }
        public double? Month5Money { get; set; }
        public double? Month6Money { get; set; }
        public double? Month7Money { get; set; }
        public double? Month8Money { get; set; }
        public double? Month9Money { get; set; }
        public double? Month10Money { get; set; }
        public double? Month11Money { get; set; }
        public double? Month12Money { get; set; }
        public double? TotalMoney { get; set; }
        [StringLength(1)]
        public string Kind { get; set; }
        [StringLength(1)]
        public string ClassID { get; set; }
        [StringLength(4)]
        public string UserID { get; set; }
        [StringLength(50)]
        public string OrderID { get; set; }
    }
}