// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Keyless]
    public partial class Mms609Temp
    {
        [StringLength(50)]
        public string Names { get; set; }
        public int? Week1Count { get; set; }
        public double? Week1Money { get; set; }
        public int? Week2Count { get; set; }
        public double? Week2Money { get; set; }
        public int? Week3Count { get; set; }
        public double? Week3Money { get; set; }
        public int? Week4Count { get; set; }
        public double? Week4Money { get; set; }
        public int? TotalCount { get; set; }
        public double? TotalMoney { get; set; }
        [StringLength(1)]
        public string Kind { get; set; }
        [StringLength(1)]
        public string ClassID { get; set; }
        [StringLength(4)]
        public string UserID { get; set; }
        [StringLength(50)]
        public string OrderID { get; set; }
    }
}