// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Keyless]
    public partial class Mms610Temp
    {
        [StringLength(50)]
        public string Names { get; set; }
        public int? Month1Count { get; set; }
        public double? Month1Money { get; set; }
        public int? Month2Count { get; set; }
        public double? Month2Money { get; set; }
        public int? Month3Count { get; set; }
        public double? Month3Money { get; set; }
        public int? TotalCount { get; set; }
        public double? TotalMoney { get; set; }
        public double? GapMoney { get; set; }
        public double? Gross { get; set; }
        public double? GetMoney { get; set; }
        public double? CostMoney { get; set; }
        [StringLength(1)]
        public string Kind { get; set; }
        [StringLength(1)]
        public string ClassID { get; set; }
        [StringLength(4)]
        public string UserID { get; set; }
        [StringLength(50)]
        public string OrderID { get; set; }
    }
}