// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Index(nameof(GoodID), Name = "GoodID")]
    [Index(nameof(GoodID), Name = "IX_Modify")]
    public partial class Modify
    {
        [Key]
        [StringLength(13)]
        public string ModifyID { get; set; }
        [StringLength(8)]
        public string ModifyDate { get; set; }
        [StringLength(15)]
        public string ModifyStore { get; set; }
        [StringLength(4)]
        public string FillPerson { get; set; }
        [StringLength(20)]
        public string GoodID { get; set; }
        [StringLength(1)]
        public string SizeNo { get; set; }
        public double? ModifyNum1 { get; set; }
        public double? ModifyNum2 { get; set; }
        public double? ModifyNum3 { get; set; }
        public double? ModifyNum4 { get; set; }
        public double? ModifyNum5 { get; set; }
        public double? ModifyNum6 { get; set; }
        public double? ModifyNum7 { get; set; }
        public double? ModifyNum8 { get; set; }
        public double? ModifyNum9 { get; set; }
        public double? ModifyNum10 { get; set; }
        public double? ModifyNum11 { get; set; }
        public double? ModifyNum12 { get; set; }
        public double? ModifyNum13 { get; set; }
        public double? ModifyNum14 { get; set; }
        public double? ModifyNum15 { get; set; }
        public double? ModifyNum16 { get; set; }
        public double? ModifyNum17 { get; set; }
        public double? TotalModifyNum { get; set; }
        [StringLength(100)]
        public string Remark { get; set; }
        public double? DiffNum1 { get; set; }
        public double? DiffNum2 { get; set; }
        public double? DiffNum3 { get; set; }
        public double? DiffNum4 { get; set; }
        public double? DiffNum5 { get; set; }
        public double? DiffNum6 { get; set; }
        public double? DiffNum7 { get; set; }
        public double? DiffNum8 { get; set; }
        public double? DiffNum9 { get; set; }
        public double? DiffNum10 { get; set; }
        public double? DiffNum11 { get; set; }
        public double? DiffNum12 { get; set; }
        public double? DiffNum13 { get; set; }
        public double? DiffNum14 { get; set; }
        public double? DiffNum15 { get; set; }
        public double? DiffNum16 { get; set; }
        public double? DiffNum17 { get; set; }
        public double? TotalDiffNum { get; set; }
        [StringLength(1)]
        public string ModifyFlag { get; set; }
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [StringLength(10)]
        public string Brand { get; set; }
        [StringLength(10)]
        public string Factory { get; set; }
        public double? ModifyCost { get; set; }
        [StringLength(4)]
        public string ChangePerson { get; set; }
        [Key]
        [StringLength(4)]
        public string Item { get; set; }
    }
}