// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Index(nameof(OrderDate), Name = "DK00B")]
    [Index(nameof(CustID), Name = "DK00C")]
    [Index(nameof(MaterialID), Name = "DK00D")]
    [Index(nameof(ProduceID), Name = "DK50")]
    [Index(nameof(StoreID), Name = "DK51")]
    public partial class MOrders
    {
        [Key]
        [StringLength(13)]
        public string OrderID { get; set; }
        [Key]
        [StringLength(50)]
        public string Item { get; set; }
        [StringLength(8)]
        public string OrderDate { get; set; }
        [StringLength(15)]
        public string CustID { get; set; }
        [StringLength(20)]
        public string MaterialID { get; set; }
        public double? OrderNum01 { get; set; }
        public double? OrderNum02 { get; set; }
        public double? OrderNum03 { get; set; }
        public double? OrderNum04 { get; set; }
        public double? OrderNum05 { get; set; }
        public double? OrderNum06 { get; set; }
        public double? OrderNum07 { get; set; }
        public double? OrderNum08 { get; set; }
        public int? OrderNum09 { get; set; }
        public double? OrderNum10 { get; set; }
        public double? OrderNum11 { get; set; }
        public double? OrderNum12 { get; set; }
        public double? OrderNum13 { get; set; }
        public double? OrderNum14 { get; set; }
        public double? OrderNum15 { get; set; }
        public double? OrderNum16 { get; set; }
        public int? OrderNum17 { get; set; }
        public double? OrderNumTotal { get; set; }
        public double? Price { get; set; }
        public double? Discount { get; set; }
        public double? OrderPrice { get; set; }
        public double? OrderAmount { get; set; }
        [StringLength(8)]
        public string PreDealDate { get; set; }
        [StringLength(1)]
        public string DealFlag { get; set; }
        [StringLength(10)]
        public string Brand { get; set; }
        [StringLength(100)]
        public string Remark { get; set; }
        [StringLength(4)]
        public string Operation { get; set; }
        [StringLength(4)]
        public string FillPerson { get; set; }
        [StringLength(1)]
        public string CancelFlag { get; set; }
        [StringLength(2)]
        public string SizeNo { get; set; }
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [StringLength(4)]
        public string ChangePerson { get; set; }
        public double? ShipNum01 { get; set; }
        public double? ShipNum02 { get; set; }
        public double? ShipNum03 { get; set; }
        public double? ShipNum04 { get; set; }
        public double? ShipNum05 { get; set; }
        public double? ShipNum06 { get; set; }
        public double? ShipNum07 { get; set; }
        public double? ShipNum08 { get; set; }
        public double? ShipNum09 { get; set; }
        public double? ShipNum10 { get; set; }
        public double? ShipNum11 { get; set; }
        public double? ShipNum12 { get; set; }
        public double? ShipNum13 { get; set; }
        public double? ShipNum14 { get; set; }
        public double? ShipNum15 { get; set; }
        public double? ShipNum16 { get; set; }
        public double? ShipNum17 { get; set; }
        public double? ShipNumTotal { get; set; }
        [StringLength(13)]
        public string ProduceID { get; set; }
        [StringLength(15)]
        public string StoreID { get; set; }
    }
}