// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Index(nameof(CheckID), Name = "CheckID")]
    [Index(nameof(StockID), Name = "StockID")]
    public partial class MPayDetail
    {
        [Key]
        [StringLength(11)]
        public string PayID { get; set; }
        [StringLength(20)]
        public string StockID { get; set; }
        [StringLength(1)]
        public string Mode { get; set; }
        [StringLength(8)]
        public string StockDate { get; set; }
        [StringLength(10)]
        public string CheckID { get; set; }
        [Column(TypeName = "money")]
        public decimal? UnstrikedAmount { get; set; }
        [Column(TypeName = "money")]
        public decimal? AllowAmount { get; set; }
        [Column(TypeName = "money")]
        public decimal? OtherAmount { get; set; }
        [Column(TypeName = "money")]
        public decimal? StrikedAmount { get; set; }
        [StringLength(10)]
        public string Brand { get; set; }
        [Key]
        [StringLength(3)]
        public string Item { get; set; }
        [StringLength(100)]
        public string Remark { get; set; }
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [StringLength(4)]
        public string ChangePerson { get; set; }
    }
}