// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Index(nameof(CheckID), Name = "CheckID")]
    [Index(nameof(PayDate), Name = "DM00B", IsUnique = true)]
    [Index(nameof(FactoryID), Name = "DM00C")]
    [Index(nameof(EndDate), Name = "DM00D")]
    [Index(nameof(PayPerson), Name = "DM00E")]
    [Index(nameof(EndBrandID), Name = "EndBrandID")]
    [Index(nameof(StartBrandID), Name = "StartBrandID")]
    public partial class MPay
    {
        [Key]
        [StringLength(11)]
        public string PayID { get; set; }
        [StringLength(8)]
        public string PayDate { get; set; }
        [StringLength(10)]
        public string FactoryID { get; set; }
        [StringLength(9)]
        public string CheckID { get; set; }
        [StringLength(8)]
        public string EndDate { get; set; }
        [Column(TypeName = "money")]
        public decimal? PayAmount { get; set; }
        [Column(TypeName = "money")]
        public decimal? PayCash { get; set; }
        [StringLength(4)]
        public string PayPerson { get; set; }
        [StringLength(16)]
        public string PayBank { get; set; }
        [StringLength(20)]
        public string Account { get; set; }
        [Column(TypeName = "money")]
        public decimal? UsedPrePay { get; set; }
        [Column(TypeName = "money")]
        public decimal? TotalPrePay { get; set; }
        [Column(TypeName = "money")]
        public decimal? PayBalance { get; set; }
        [Column(TypeName = "money")]
        public decimal? PrePayBalance { get; set; }
        [Column(TypeName = "money")]
        public decimal? TotalAccount { get; set; }
        [StringLength(10)]
        public string StartBrandID { get; set; }
        [StringLength(10)]
        public string EndBrandID { get; set; }
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [StringLength(4)]
        public string ChangePerson { get; set; }
        [StringLength(100)]
        public string Remark { get; set; }
    }
}