// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Index(nameof(PreDate), Name = "DXD02")]
    [Index(nameof(GoodID), Name = "DXD03")]
    public partial class MPreProduct
    {
        [Key]
        [StringLength(13)]
        public string PreProductID { get; set; }
        [StringLength(8)]
        public string PreDate { get; set; }
        [StringLength(20)]
        public string GoodID { get; set; }
        [StringLength(2)]
        public string SizeNo { get; set; }
        public double? SizeNum01 { get; set; }
        public double? SizeNum02 { get; set; }
        public double? SizeNum03 { get; set; }
        public double? SizeNum04 { get; set; }
        public double? SizeNum05 { get; set; }
        public double? SizeNum06 { get; set; }
        public double? SizeNum07 { get; set; }
        public double? SizeNum08 { get; set; }
        public double? SizeNum09 { get; set; }
        public double? SizeNum10 { get; set; }
        public double? SizeNum11 { get; set; }
        public double? SizeNum12 { get; set; }
        public double? SizeNum13 { get; set; }
        public double? SizeNum14 { get; set; }
        public double? SizeNum15 { get; set; }
        public double? SizeNum16 { get; set; }
        public double? SizeNum17 { get; set; }
        public double? SizeTotalNum { get; set; }
        [StringLength(20)]
        public string Remark { get; set; }
        [StringLength(2)]
        public string FinishFlag { get; set; }
        [Key]
        [StringLength(3)]
        public string Item { get; set; }
        [StringLength(4)]
        public string ChangePerson { get; set; }
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [StringLength(8)]
        public string OutStore { get; set; }
        [StringLength(1)]
        public string FaceFlag { get; set; }
    }
}