// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    public partial class MProcess
    {
        [Key]
        [StringLength(2)]
        public string ProcessID { get; set; }
        [StringLength(20)]
        public string ProcessName { get; set; }
        [StringLength(255)]
        public string Remark { get; set; }
    }
}