// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Index(nameof(PurchaseDate), Name = "DO02")]
    [Index(nameof(PurchaseStore), Name = "DO03")]
    [Index(nameof(PurchaseFactory), Name = "DO04")]
    [Index(nameof(MaterialID), Name = "DO05")]
    public partial class MPurchase
    {
        [Key]
        [StringLength(20)]
        public string PurchaseID { get; set; }
        [StringLength(8)]
        public string PurchaseDate { get; set; }
        [StringLength(15)]
        public string PurchaseStore { get; set; }
        [StringLength(10)]
        public string PurchaseFactory { get; set; }
        [StringLength(20)]
        public string MaterialID { get; set; }
        public double? PurchaseNum1 { get; set; }
        public double? PurchaseNum2 { get; set; }
        public double? PurchaseNum3 { get; set; }
        public double? PurchaseNum4 { get; set; }
        public double? PurchaseNum5 { get; set; }
        public double? PurchaseNum6 { get; set; }
        public double? PurchaseNum7 { get; set; }
        public double? PurchaseNum8 { get; set; }
        public double? PurchaseNum9 { get; set; }
        public double? PurchaseNum10 { get; set; }
        public double? PurchaseNum11 { get; set; }
        public double? PurchaseNum12 { get; set; }
        public double? PurchaseNum13 { get; set; }
        public double? PurchaseNum14 { get; set; }
        public double? PurchaseNum15 { get; set; }
        public double? PurchaseNum16 { get; set; }
        public double? PurchaseNum17 { get; set; }
        public double? TotalPurchaseNum { get; set; }
        public double? PurchasePrice { get; set; }
        public double? PurchaseAmount { get; set; }
        [StringLength(8)]
        public string PreDealDate { get; set; }
        [StringLength(1)]
        public string DealFlag { get; set; }
        [StringLength(10)]
        public string Brand { get; set; }
        [StringLength(60)]
        public string Remark { get; set; }
        [StringLength(4)]
        public string FillPerson { get; set; }
        [StringLength(1)]
        public string CancelFlag { get; set; }
        [StringLength(2)]
        public string SizeNo { get; set; }
        public double? ShipNum1 { get; set; }
        public double? ShipNum2 { get; set; }
        public double? ShipNum3 { get; set; }
        public double? ShipNum4 { get; set; }
        public double? ShipNum5 { get; set; }
        public double? ShipNum6 { get; set; }
        public double? ShipNum7 { get; set; }
        public double? ShipNum8 { get; set; }
        public double? ShipNum9 { get; set; }
        public double? ShipNum10 { get; set; }
        public double? ShipNum11 { get; set; }
        public double? ShipNum12 { get; set; }
        public double? ShipNum13 { get; set; }
        public double? ShipNum14 { get; set; }
        public double? ShipNum15 { get; set; }
        public double? ShipNum16 { get; set; }
        public double? ShipNum17 { get; set; }
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [StringLength(4)]
        public string ChangePerson { get; set; }
        [Key]
        [StringLength(3)]
        public string Item { get; set; }
    }
}