// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Index(nameof(ShipID), Name = "DLA01", IsUnique = true)]
    public partial class MShip
    {
        [Key]
        [StringLength(20)]
        public string ShipID { get; set; }
        [StringLength(4)]
        public string FillPerson { get; set; }
        [StringLength(8)]
        public string ShipDate { get; set; }
        [StringLength(15)]
        public string CustID { get; set; }
        [StringLength(6)]
        public string CloseMonth { get; set; }
        [StringLength(1)]
        public string ShipMode { get; set; }
        [StringLength(15)]
        public string ShipStore { get; set; }
        [StringLength(4)]
        public string Operation { get; set; }
        public double? DealAmount { get; set; }
        public double? TaxPercent { get; set; }
        public double? Tax { get; set; }
        public double? ShipDiscountPercent { get; set; }
        public double? ShipDiscount { get; set; }
        public double? DiscountAmount { get; set; }
        public double? OtherAmount { get; set; }
        public double? ChargeAmount { get; set; }
        [StringLength(1)]
        public string ChargeFlag { get; set; }
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [StringLength(4)]
        public string ChangePerson { get; set; }
    }
}