// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Index(nameof(ShipID), Name = "DL00A")]
    [Index(nameof(CustID), nameof(ShipDate), Name = "DL00B")]
    [Index(nameof(MaterialID), nameof(ShipDate), Name = "DL00C")]
    [Index(nameof(ShipStore), Name = "DL05")]
    [Index(nameof(OrderID), Name = "OrderID")]
    public partial class MShipDetail
    {
        [Key]
        [StringLength(20)]
        public string ShipID { get; set; }
        [StringLength(1)]
        public string ShipMode { get; set; }
        [StringLength(8)]
        public string ShipDate { get; set; }
        [StringLength(15)]
        public string CustID { get; set; }
        [StringLength(15)]
        public string ShipStore { get; set; }
        [StringLength(6)]
        public string CloseMonth { get; set; }
        [StringLength(4)]
        public string Operation { get; set; }
        [StringLength(4)]
        public string FillPerson { get; set; }
        [StringLength(20)]
        public string MaterialID { get; set; }
        public double? ShipNum01 { get; set; }
        public double? ShipNum02 { get; set; }
        public double? ShipNum03 { get; set; }
        public double? ShipNum04 { get; set; }
        public double? ShipNum05 { get; set; }
        public double? ShipNum06 { get; set; }
        public double? ShipNum07 { get; set; }
        public double? ShipNum08 { get; set; }
        public double? ShipNum09 { get; set; }
        public double? ShipNum10 { get; set; }
        public double? ShipNum11 { get; set; }
        public double? ShipNum12 { get; set; }
        public double? ShipNum13 { get; set; }
        public double? ShipNum14 { get; set; }
        public double? ShipNum15 { get; set; }
        public double? ShipNum16 { get; set; }
        public double? ShipNum17 { get; set; }
        public double? ShipNumTotal { get; set; }
        public double? SellPrice { get; set; }
        public double? Discount { get; set; }
        public double? Price { get; set; }
        public double? Amount { get; set; }
        [StringLength(13)]
        public string OrderID { get; set; }
        [StringLength(10)]
        public string Brand { get; set; }
        [StringLength(2)]
        public string SizeNo { get; set; }
        [Key]
        [StringLength(3)]
        public string Item { get; set; }
        [StringLength(3)]
        public string OrderItem { get; set; }
        public double? ShipCost { get; set; }
    }
}