// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Index(nameof(Brand), nameof(CheckDate), nameof(CheckStore), nameof(MaterialID), nameof(SizeNo), Name = "_412")]
    public partial class MStgCheck
    {
        [Key]
        [StringLength(8)]
        public string CheckDate { get; set; }
        [Key]
        [StringLength(15)]
        public string CheckStore { get; set; }
        [Key]
        [StringLength(20)]
        public string MaterialID { get; set; }
        [Key]
        [StringLength(1)]
        public string SizeNo { get; set; }
        public double? CheckNum01 { get; set; }
        public double? CheckNum02 { get; set; }
        public double? CheckNum03 { get; set; }
        public double? CheckNum04 { get; set; }
        public double? CheckNum05 { get; set; }
        public double? CheckNum06 { get; set; }
        public double? CheckNum07 { get; set; }
        public double? CheckNum08 { get; set; }
        public double? CheckNum09 { get; set; }
        public double? CheckNum10 { get; set; }
        public double? CheckNum11 { get; set; }
        public double? CheckNum12 { get; set; }
        public double? CheckNum13 { get; set; }
        public double? CheckNum14 { get; set; }
        public double? CheckNum15 { get; set; }
        public double? CheckNum16 { get; set; }
        public double? CheckNum17 { get; set; }
        public double? TotalCheckNum { get; set; }
        public double? OldNum01 { get; set; }
        public double? OldNum02 { get; set; }
        public double? OldNum03 { get; set; }
        public double? OldNum04 { get; set; }
        public double? OldNum05 { get; set; }
        public double? OldNum06 { get; set; }
        public double? OldNum07 { get; set; }
        public double? OldNum08 { get; set; }
        public double? OldNum09 { get; set; }
        public double? OldNum10 { get; set; }
        public double? OldNum11 { get; set; }
        public double? OldNum12 { get; set; }
        public double? OldNum13 { get; set; }
        public double? OldNum14 { get; set; }
        public double? OldNum15 { get; set; }
        public double? OldNum16 { get; set; }
        public double? OldNum17 { get; set; }
        public double? TotalOldNum { get; set; }
        [StringLength(1)]
        public string CheckFlag { get; set; }
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [StringLength(10)]
        public string Brand { get; set; }
        [StringLength(10)]
        public string Factory { get; set; }
        [StringLength(4)]
        public string FillPerson { get; set; }
        [StringLength(4)]
        public string ChangePerson { get; set; }
    }
}