// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Index(nameof(FactoryID), Name = "FactoryID")]
    [Index(nameof(FactoryStockID), Name = "FactoryStockID")]
    [Index(nameof(StoreID), Name = "StoreID")]
    public partial class MStock
    {
        [Key]
        [StringLength(13)]
        public string StockID { get; set; }
        [StringLength(11)]
        public string FactoryStockID { get; set; }
        [StringLength(8)]
        public string StockDate { get; set; }
        [StringLength(10)]
        public string FactoryID { get; set; }
        [StringLength(6)]
        public string CloseMonth { get; set; }
        [StringLength(1)]
        public string StockMode { get; set; }
        [StringLength(15)]
        public string StoreID { get; set; }
        [StringLength(4)]
        public string FillPerson { get; set; }
        public double? ShouldAmount { get; set; }
        public double? TaxPercent { get; set; }
        public double? Tax { get; set; }
        public double? DiscountPercent { get; set; }
        public double? Discount { get; set; }
        public double? DiscountAmount { get; set; }
        public double? OtherAmount { get; set; }
        public double? ChargeAmount { get; set; }
        [StringLength(1)]
        public string ChargeMode { get; set; }
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [StringLength(4)]
        public string ChangePerson { get; set; }
    }
}