// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Index(nameof(FactoryStockID), Name = "DP02")]
    [Index(nameof(StockDate), Name = "DP03")]
    [Index(nameof(FactoryID), Name = "DP04")]
    [Index(nameof(StoreID), Name = "DP07")]
    [Index(nameof(MaterialID), Name = "DP09")]
    [Index(nameof(PurchaseID), Name = "PurchaseID")]
    public partial class MStockDetail
    {
        [Key]
        [StringLength(20)]
        public string StockID { get; set; }
        [StringLength(11)]
        public string FactoryStockID { get; set; }
        [StringLength(8)]
        public string StockDate { get; set; }
        [StringLength(10)]
        public string FactoryID { get; set; }
        [StringLength(6)]
        public string CloseMoth { get; set; }
        [StringLength(1)]
        public string StockMode { get; set; }
        [StringLength(15)]
        public string StoreID { get; set; }
        [StringLength(4)]
        public string FillPerson { get; set; }
        [StringLength(20)]
        public string MaterialID { get; set; }
        public double? StockNum01 { get; set; }
        public double? StockNum02 { get; set; }
        public double? StockNum03 { get; set; }
        public double? StockNum04 { get; set; }
        public double? StockNum05 { get; set; }
        public double? StockNum06 { get; set; }
        public double? StockNum07 { get; set; }
        public double? StockNum08 { get; set; }
        public double? StockNum09 { get; set; }
        public double? StockNum10 { get; set; }
        public double? StockNum11 { get; set; }
        public double? StockNum12 { get; set; }
        public double? StockNum13 { get; set; }
        public double? StockNum14 { get; set; }
        public double? StockNum15 { get; set; }
        public double? StockNum16 { get; set; }
        public double? StockNum17 { get; set; }
        public double? StockNumTotal { get; set; }
        public double? Price { get; set; }
        public double? Cost { get; set; }
        public double? StockAmount { get; set; }
        [StringLength(20)]
        public string PurchaseID { get; set; }
        [StringLength(2)]
        public string SizeNo { get; set; }
        [Key]
        [StringLength(3)]
        public string Item { get; set; }
        [StringLength(10)]
        public string Brand { get; set; }
        [StringLength(50)]
        public string Remark { get; set; }
        [StringLength(3)]
        public string PurchaseItem { get; set; }
    }
}