// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    public partial class NikeTab1
    {
        [Key]
        [StringLength(2)]
        public string TB01 { get; set; }
        [Key]
        [StringLength(1)]
        public string TB02 { get; set; }
        [StringLength(2)]
        public string TB03 { get; set; }
    }
}