// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    public partial class OldGoodSpecialA
    {
        [Required]
        [StringLength(25)]
        public string StartGoodID { get; set; }
        [Required]
        [StringLength(25)]
        public string EndGoodID { get; set; }
        [Required]
        [StringLength(15)]
        public string StartStoreID { get; set; }
        [Required]
        [StringLength(15)]
        public string EndStoreID { get; set; }
        [Required]
        [StringLength(12)]
        public string StartDate { get; set; }
        [Required]
        [StringLength(12)]
        public string EndDate { get; set; }
        [Required]
        [StringLength(8)]
        public string StartSort01ID { get; set; }
        [Required]
        [StringLength(8)]
        public string EndSort01ID { get; set; }
        [Required]
        [StringLength(10)]
        public string StartBrandID { get; set; }
        [Required]
        [StringLength(10)]
        public string EndBrandID { get; set; }
        [Required]
        [StringLength(8)]
        public string StartCardID { get; set; }
        [Required]
        [StringLength(8)]
        public string EndCardID { get; set; }
        public double Discount { get; set; }
        public double SpecialPrice { get; set; }
        [Key]
        [StringLength(50)]
        public string SerialID { get; set; }
        public double NumLimit { get; set; }
        [Required]
        [StringLength(100)]
        public string StartTime { get; set; }
        [Required]
        [StringLength(100)]
        public string EndTime { get; set; }
        public double StartPrice { get; set; }
        public double EndPrice { get; set; }
        public double SellNum { get; set; }
        public double PriorLevel { get; set; }
        [Required]
        [StringLength(8)]
        public string StartSeason { get; set; }
        [Required]
        [StringLength(8)]
        public string EndSeason { get; set; }
        [Required]
        [StringLength(15)]
        public string KStoreID { get; set; }
        [Required]
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [Required]
        [StringLength(4)]
        public string ChangePerson { get; set; }
        [StringLength(10)]
        public string StartFactoryID { get; set; }
        [StringLength(10)]
        public string EndFactoryID { get; set; }
        [StringLength(100)]
        public string KDate { get; set; }
        [StringLength(100)]
        public string KRemark { get; set; }
        public double? HongLi { get; set; }
        public double? HongLiTimes { get; set; }
    }
}