// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Index(nameof(OrderID), Name = "DG00A")]
    [Index(nameof(CustID), nameof(OrderID), Name = "DG00B")]
    [Index(nameof(GoodID), nameof(OrderID), Name = "DG00C")]
    [Index(nameof(FootWorkID), Name = "FootWorkID")]
    [Index(nameof(GoodID), Name = "GoodID")]
    [Index(nameof(HeadWorkID), Name = "HeadWorkID")]
    [Index(nameof(WorkID), Name = "WorkID")]
    public partial class Orders
    {
        [Key]
        [StringLength(20)]
        public string OrderID { get; set; }
        [StringLength(8)]
        public string OrderDate { get; set; }
        [StringLength(15)]
        public string CustID { get; set; }
        [StringLength(20)]
        public string GoodID { get; set; }
        [StringLength(1)]
        public string SizeNo { get; set; }
        public double? OrderNum1 { get; set; }
        public double? OrderNum2 { get; set; }
        public double? OrderNum3 { get; set; }
        public double? OrderNum4 { get; set; }
        public double? OrderNum5 { get; set; }
        public double? OrderNum6 { get; set; }
        public double? OrderNum7 { get; set; }
        public double? OrderNum8 { get; set; }
        public double? OrderNum9 { get; set; }
        public double? OrderNum10 { get; set; }
        public double? OrderNum11 { get; set; }
        public double? OrderNum12 { get; set; }
        public double? OrderNum13 { get; set; }
        public double? OrderNum14 { get; set; }
        public double? OrderNum15 { get; set; }
        public double? OrderNum16 { get; set; }
        public double? OrderNum17 { get; set; }
        public double? TotalOrderNum { get; set; }
        public double? Price { get; set; }
        public double? Discount { get; set; }
        public double? OrderPrice { get; set; }
        public double? OrderAmount { get; set; }
        [StringLength(1)]
        public string OrderMode { get; set; }
        [StringLength(8)]
        public string PreDealDate { get; set; }
        [StringLength(1)]
        public string DealFlag { get; set; }
        [StringLength(100)]
        public string Remark { get; set; }
        [StringLength(4)]
        public string Operation { get; set; }
        [StringLength(4)]
        public string FillPerson { get; set; }
        [StringLength(1)]
        public string CancelFlag { get; set; }
        [StringLength(10)]
        public string Brand { get; set; }
        [StringLength(10)]
        public string Factory { get; set; }
        [StringLength(1)]
        public string DealMode { get; set; }
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [StringLength(4)]
        public string ChangePerson { get; set; }
        [Key]
        [StringLength(3)]
        public string Item { get; set; }
        [StringLength(13)]
        public string WorkID { get; set; }
        [StringLength(3)]
        public string WorkItem { get; set; }
        [StringLength(1)]
        public string TaxMode { get; set; }
        public double? TaxPercent { get; set; }
        public double? Tax { get; set; }
        public double? AmountAfterTax { get; set; }
        [StringLength(13)]
        public string HeadWorkID { get; set; }
        [StringLength(13)]
        public string FootWorkID { get; set; }
        [StringLength(2)]
        public string IntoSign { get; set; }
        public double? Non_Tax { get; set; }
        [StringLength(20)]
        public string ClientOrderID { get; set; }
        [StringLength(200)]
        public string ClientGoodID { get; set; }
        [StringLength(15)]
        public string OrderStore { get; set; }
        [StringLength(50)]
        public string CompanyName { get; set; }
        [StringLength(20)]
        public string PurchaseID { get; set; }
        [StringLength(4)]
        public string PurchaseItem { get; set; }
        [StringLength(8)]
        public string DealModeID { get; set; }
        [StringLength(100)]
        public string GoodName { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? NewTaxAmt { get; set; }
        [StringLength(1)]
        public string IsCheck { get; set; }
        [StringLength(8)]
        public string CheckDate { get; set; }
        [StringLength(1)]
        public string Type { get; set; }
        [StringLength(20)]
        public string P_StyleC { get; set; }
        [StringLength(4)]
        public string CurrencyID { get; set; }
        public double? CurrencyRate { get; set; }
        public double? ForeignPrice { get; set; }
    }
}