// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    public partial class OtherProc
    {
        [Key]
        [StringLength(15)]
        public string ClientID { get; set; }
        [Required]
        [StringLength(100)]
        public string ClientShort { get; set; }
        [Key]
        [StringLength(15)]
        public string Reside { get; set; }
        [Required]
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [Required]
        [StringLength(4)]
        public string ChangePerson { get; set; }
        [StringLength(1)]
        public string Display { get; set; }
    }
}