// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Index(nameof(BranchID), Name = "BranchID")]
    public partial class OutWork
    {
        [Key]
        [StringLength(8)]
        public string OutWorkDate { get; set; }
        [Key]
        [StringLength(8)]
        public string EmpID { get; set; }
        [StringLength(40)]
        public string EmpName { get; set; }
        [StringLength(8)]
        public string BranchID { get; set; }
        [StringLength(20)]
        public string BranchName { get; set; }
        [StringLength(50)]
        public string OutDay { get; set; }
        [Key]
        [StringLength(50)]
        public string BackDay { get; set; }
        [StringLength(100)]
        public string Resean { get; set; }
    }
}