// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    public partial class PaperSetup
    {
        [Key]
        [StringLength(12)]
        public string PaperName { get; set; }
        public double PaperWidth { get; set; }
        public double PaperHeight { get; set; }
        public double? LeftMargin { get; set; }
        public double? RightMargin { get; set; }
        public double? TopMargin { get; set; }
        public double? BottonMargin { get; set; }
        [StringLength(5)]
        public string ChangePerson { get; set; }
        [StringLength(8)]
        public string ChangeDate { get; set; }
    }
}