// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    public partial class Pay
    {
        [Key]
        [StringLength(11)]
        public string PayID { get; set; }
        [StringLength(8)]
        public string PayDate { get; set; }
        [StringLength(10)]
        public string FactoryID { get; set; }
        [StringLength(9)]
        public string CheckID { get; set; }
        [StringLength(8)]
        public string EndDate { get; set; }
        public double? PayAmount { get; set; }
        public double? PayCash { get; set; }
        [StringLength(4)]
        public string PayPerson { get; set; }
        [StringLength(16)]
        public string PayBank { get; set; }
        [StringLength(20)]
        public string Account { get; set; }
        public double? UsedPrePay { get; set; }
        public double? TotalPrePay { get; set; }
        public double? PayBalance { get; set; }
        public double? PrePayBalance { get; set; }
        public double? TotalAccount { get; set; }
        [StringLength(10)]
        public string StartBrandID { get; set; }
        [StringLength(10)]
        public string EndBrandID { get; set; }
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [StringLength(4)]
        public string ChangePerson { get; set; }
        [StringLength(100)]
        public string Remark { get; set; }
    }
}