// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Index(nameof(ChangID), Name = "ChangID")]
    public partial class Phrase
    {
        [Key]
        [StringLength(6)]
        public string PhraseNo { get; set; }
        [Column("Phrase")]
        [StringLength(40)]
        public string Phrase1 { get; set; }
        [StringLength(100)]
        public string Note { get; set; }
        [StringLength(10)]
        public string ChangDate { get; set; }
        [StringLength(20)]
        public string ChangID { get; set; }
    }
}