// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Keyless]
    public partial class Pov133Temp
    {
        [StringLength(20)]
        public string GoodID1 { get; set; }
        [StringLength(15)]
        public string Branch1 { get; set; }
        [StringLength(8)]
        public string OpenDate1 { get; set; }
        [StringLength(20)]
        public string Value1 { get; set; }
        [StringLength(20)]
        public string Value2 { get; set; }
        [StringLength(20)]
        public string GoodID2 { get; set; }
        [StringLength(15)]
        public string Branch2 { get; set; }
        [StringLength(8)]
        public string OpenDate2 { get; set; }
        [StringLength(20)]
        public string Value3 { get; set; }
        [StringLength(20)]
        public string Value4 { get; set; }
        [StringLength(4)]
        public string UserID { get; set; }
    }
}