// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Keyless]
    public partial class pov107Temp
    {
        [StringLength(1)]
        public string Name { get; set; }
        [StringLength(4)]
        public string Size { get; set; }
        [StringLength(50)]
        public string Bar { get; set; }
        [StringLength(2)]
        public string AutoID { get; set; }
        [StringLength(4)]
        public string UserID { get; set; }
    }
}