// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Keyless]
    public partial class pov1075Temp
    {
        [StringLength(15)]
        public string Month { get; set; }
        public int? Week1 { get; set; }
        public int? Week2 { get; set; }
        public int? Week3 { get; set; }
        public int? Week4 { get; set; }
        public int? Total { get; set; }
        [StringLength(1)]
        public string Kind { get; set; }
        [StringLength(50)]
        public string UserID { get; set; }
    }
}