// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Keyless]
    public partial class Pov108BTemp
    {
        [StringLength(20)]
        public string GoodID { get; set; }
        [StringLength(15)]
        public string Branch { get; set; }
        [StringLength(8)]
        public string OpenDate { get; set; }
        [StringLength(2)]
        public string CardID { get; set; }
        [StringLength(8)]
        public string Date { get; set; }
        public int AutoID { get; set; }
        [StringLength(4)]
        public string UserID { get; set; }
    }
}