// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Keyless]
    public partial class Pov217Tmp
    {
        [StringLength(8)]
        public string ID { get; set; }
        [StringLength(8)]
        public string Date { get; set; }
        public double? People { get; set; }
        [StringLength(12)]
        public string UserID { get; set; }
    }
}