// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Keyless]
    [Index(nameof(FactoryID), Name = "FactoryID")]
    [Index(nameof(GoodID), Name = "GoodID")]
    [Index(nameof(PurchaseID), Name = "PurchaseID")]
    [Index(nameof(Sort01ID), Name = "Sort01ID")]
    [Index(nameof(Sort02ID), Name = "Sort02ID")]
    [Index(nameof(Sort03ID), Name = "Sort03ID")]
    [Index(nameof(Sort04ID), Name = "Sort04ID")]
    [Index(nameof(Sort05ID), Name = "Sort05ID")]
    [Index(nameof(SortID), Name = "SortID")]
    [Index(nameof(UserID), Name = "UserID")]
    public partial class Pov210DetailTmp
    {
        [StringLength(20)]
        public string GoodID { get; set; }
        [StringLength(80)]
        public string GoodName { get; set; }
        [StringLength(10)]
        public string FactoryID { get; set; }
        [StringLength(80)]
        public string FactoryName { get; set; }
        [StringLength(13)]
        public string PurchaseID { get; set; }
        [StringLength(8)]
        public string PurchaseDate { get; set; }
        [StringLength(8)]
        public string PurchaseStore { get; set; }
        [StringLength(8)]
        public string Sort01ID { get; set; }
        [StringLength(40)]
        public string Sort01Name { get; set; }
        [StringLength(8)]
        public string Sort02ID { get; set; }
        [StringLength(40)]
        public string Sort02Name { get; set; }
        [StringLength(8)]
        public string Sort03ID { get; set; }
        [StringLength(40)]
        public string Sort03Name { get; set; }
        [StringLength(8)]
        public string Sort04ID { get; set; }
        [StringLength(40)]
        public string Sort04Name { get; set; }
        [StringLength(8)]
        public string Sort05ID { get; set; }
        [StringLength(40)]
        public string Sort05Name { get; set; }
        [StringLength(8)]
        public string SortID { get; set; }
        [StringLength(40)]
        public string SortName { get; set; }
        [StringLength(40)]
        public string PriceL { get; set; }
        [StringLength(2)]
        public string SizeNo { get; set; }
        [StringLength(50)]
        public string Num1 { get; set; }
        [StringLength(50)]
        public string Num2 { get; set; }
        [StringLength(50)]
        public string Num3 { get; set; }
        [StringLength(50)]
        public string Num4 { get; set; }
        [StringLength(50)]
        public string Num5 { get; set; }
        [StringLength(50)]
        public string Num6 { get; set; }
        [StringLength(50)]
        public string Num7 { get; set; }
        [StringLength(50)]
        public string Num8 { get; set; }
        [StringLength(50)]
        public string Num9 { get; set; }
        [StringLength(50)]
        public string Num10 { get; set; }
        [StringLength(50)]
        public string Num11 { get; set; }
        [StringLength(50)]
        public string Num12 { get; set; }
        [StringLength(50)]
        public string Num13 { get; set; }
        [StringLength(50)]
        public string Num14 { get; set; }
        [StringLength(50)]
        public string Num15 { get; set; }
        [StringLength(50)]
        public string Num16 { get; set; }
        [StringLength(50)]
        public string Num17 { get; set; }
        [StringLength(50)]
        public string TotalNum { get; set; }
        [StringLength(50)]
        public string Amount { get; set; }
        [StringLength(1)]
        public string PurchaseMode { get; set; }
        [StringLength(5)]
        public string UserID { get; set; }
        [StringLength(8)]
        public string FormName { get; set; }
        [Column(TypeName = "decimal(18, 0)")]
        public decimal FindID { get; set; }
        public double? Price { get; set; }
        [StringLength(8)]
        public string PreDealDate { get; set; }
    }
}