// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Keyless]
    [Index(nameof(FactoryID), Name = "ClientID")]
    [Index(nameof(GoodID), Name = "GoodID")]
    [Index(nameof(StockID), Name = "ShipID")]
    [Index(nameof(UserID), Name = "UserID")]
    public partial class Pov208Tmp
    {
        [StringLength(10)]
        public string FactoryID { get; set; }
        [StringLength(50)]
        public string FactoryName { get; set; }
        [StringLength(20)]
        public string GoodID { get; set; }
        [StringLength(50)]
        public string GoodName { get; set; }
        [StringLength(15)]
        public string StoreID { get; set; }
        [StringLength(50)]
        public string StoreName { get; set; }
        [StringLength(13)]
        public string StockID { get; set; }
        [StringLength(8)]
        public string StockDate { get; set; }
        public double? StockPrice { get; set; }
        public double? StockTotalNum { get; set; }
        public double? StockAmount { get; set; }
        public double? Non_Tax { get; set; }
        public double? Tax { get; set; }
        [StringLength(8)]
        public string StockMode { get; set; }
        [StringLength(4)]
        public string UserID { get; set; }
        [StringLength(10)]
        public string FormName { get; set; }
        [StringLength(8)]
        public string fid { get; set; }
    }
}