// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Keyless]
    [Index(nameof(ClientID), Name = "ClientID")]
    [Index(nameof(GoodID), Name = "EmpID")]
    [Index(nameof(OrderID), Name = "ShipID")]
    [Index(nameof(UserID), Name = "UserID")]
    public partial class Pov224Tmp
    {
        [StringLength(15)]
        public string ClientID { get; set; }
        [StringLength(50)]
        public string ClientName { get; set; }
        [StringLength(20)]
        public string GoodID { get; set; }
        [StringLength(40)]
        public string GoodName { get; set; }
        [StringLength(4)]
        public string EmpID { get; set; }
        [StringLength(50)]
        public string EmpName { get; set; }
        [StringLength(13)]
        public string OrderID { get; set; }
        [StringLength(8)]
        public string OrderDate { get; set; }
        public double? OrderPrice { get; set; }
        public double? OrderDiscount { get; set; }
        public double? TotalOrderNum { get; set; }
        public double? OrderAmount { get; set; }
        public double? Non_Tax { get; set; }
        public double? Tax { get; set; }
        public double? IntoPrice { get; set; }
        [StringLength(1)]
        public string OrderMode { get; set; }
        [StringLength(4)]
        public string UserID { get; set; }
        [StringLength(8)]
        public string FormName { get; set; }
    }
}