// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Keyless]
    [Index(nameof(CustID), Name = "FactoryID")]
    [Index(nameof(GoodID), Name = "GoodID")]
    [Index(nameof(OrderID), Name = "PurchaseID")]
    [Index(nameof(Sort01ID), Name = "Sort01ID")]
    [Index(nameof(Sort02ID), Name = "Sort02ID")]
    [Index(nameof(Sort03ID), Name = "Sort03ID")]
    [Index(nameof(Sort04ID), Name = "Sort04ID")]
    [Index(nameof(Sort05ID), Name = "Sort05ID")]
    [Index(nameof(UserID), Name = "UserID")]
    public partial class Pov213Tmp
    {
        [StringLength(20)]
        public string GoodID { get; set; }
        [StringLength(80)]
        public string GoodName { get; set; }
        [StringLength(15)]
        public string CustID { get; set; }
        [StringLength(80)]
        public string CustName { get; set; }
        [StringLength(13)]
        public string OrderID { get; set; }
        [StringLength(8)]
        public string OrderDate { get; set; }
        [StringLength(8)]
        public string PreDealDate { get; set; }
        [StringLength(8)]
        public string Sort01ID { get; set; }
        [StringLength(40)]
        public string Sort01Name { get; set; }
        [StringLength(8)]
        public string Sort02ID { get; set; }
        [StringLength(40)]
        public string Sort02Name { get; set; }
        [StringLength(8)]
        public string Sort03ID { get; set; }
        [StringLength(40)]
        public string Sort03Name { get; set; }
        [StringLength(8)]
        public string Sort04ID { get; set; }
        [StringLength(40)]
        public string Sort04Name { get; set; }
        [StringLength(8)]
        public string Sort05ID { get; set; }
        [StringLength(40)]
        public string Sort05Name { get; set; }
        [StringLength(2)]
        public string SizeNo { get; set; }
        public double? OrderNum1 { get; set; }
        public double? OrderNum2 { get; set; }
        public double? OrderNum3 { get; set; }
        public double? OrderNum4 { get; set; }
        public double? OrderNum5 { get; set; }
        public double? OrderNum6 { get; set; }
        public double? OrderNum7 { get; set; }
        public double? OrderNum8 { get; set; }
        public double? OrderNum9 { get; set; }
        public double? OrderNum10 { get; set; }
        public double? OrderNum11 { get; set; }
        public double? OrderNum12 { get; set; }
        public double? OrderNum13 { get; set; }
        public double? OrderNum14 { get; set; }
        public double? OrderNum15 { get; set; }
        public double? OrderNum16 { get; set; }
        public double? OrderNum17 { get; set; }
        public double? TotalOrderNum { get; set; }
        public double? OrderAmount { get; set; }
        [StringLength(1)]
        public string OrderMode { get; set; }
        [StringLength(5)]
        public string Item { get; set; }
        [StringLength(5)]
        public string UserID { get; set; }
        [StringLength(8)]
        public string FormName { get; set; }
        [StringLength(4)]
        public string EmpID { get; set; }
        [StringLength(50)]
        public string EmpName { get; set; }
        [StringLength(15)]
        public string ClientID { get; set; }
        [StringLength(50)]
        public string ClientShort { get; set; }
        [StringLength(5)]
        public string Season { get; set; }
    }
}