// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Keyless]
    public partial class Pov219temp
    {
        [StringLength(13)]
        public string ShipID { get; set; }
        [StringLength(10)]
        public string InvoiceID { get; set; }
        [StringLength(8)]
        public string ShipDate { get; set; }
        [StringLength(15)]
        public string CustID { get; set; }
        public double? DealAmount { get; set; }
        public double? InvoiceAmount { get; set; }
        public int? TotalSellNum { get; set; }
        [StringLength(1)]
        public string Prt { get; set; }
        [StringLength(10)]
        public string ChangDate { get; set; }
        [StringLength(20)]
        public string ChangID { get; set; }
    }
}