// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Keyless]
    public partial class Pov242Temp
    {
        [StringLength(20)]
        public string GoodID { get; set; }
        [StringLength(20)]
        public string MemberID { get; set; }
        [StringLength(15)]
        public string BuyClientID { get; set; }
        public double? TotalMoney { get; set; }
        [StringLength(4)]
        public string UserID { get; set; }
    }
}