// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Keyless]
    [Index(nameof(FactoryID), Name = "ClientID")]
    [Index(nameof(GoodID), Name = "GoodID")]
    [Index(nameof(PurchaseID), Name = "ShipID")]
    [Index(nameof(UserID), Name = "UserID")]
    public partial class Pov225Tmp
    {
        [StringLength(10)]
        public string FactoryID { get; set; }
        [StringLength(50)]
        public string FactoryName { get; set; }
        [StringLength(20)]
        public string GoodID { get; set; }
        [StringLength(50)]
        public string GoodName { get; set; }
        [StringLength(20)]
        public string PurchaseID { get; set; }
        [StringLength(8)]
        public string PurchaseDate { get; set; }
        public double? PurchasePrice { get; set; }
        public double? PurchaseTotalNum { get; set; }
        public double? PurchaseAmount { get; set; }
        public double? Non_Tax { get; set; }
        public double? Tax { get; set; }
        [StringLength(4)]
        public string UserID { get; set; }
        [StringLength(10)]
        public string FormName { get; set; }
    }
}