// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Keyless]
    public partial class Pov227Temp
    {
        [StringLength(13)]
        public string FactoryID { get; set; }
        [StringLength(20)]
        public string GoodID { get; set; }
        [StringLength(1)]
        public string SizeNo { get; set; }
        public int? Num1 { get; set; }
        public int? Num2 { get; set; }
        public int? Num3 { get; set; }
        public int? Num4 { get; set; }
        public int? Num5 { get; set; }
        public int? Num6 { get; set; }
        public int? Num7 { get; set; }
        public int? Num8 { get; set; }
        public int? Num9 { get; set; }
        public int? Num10 { get; set; }
        public int? Num11 { get; set; }
        public int? Num12 { get; set; }
        public int? Num13 { get; set; }
        public int? Num14 { get; set; }
        public int? Num15 { get; set; }
        public int? Num16 { get; set; }
        public int? Num17 { get; set; }
        public int? TotalNum { get; set; }
        [StringLength(4)]
        public string UserID { get; set; }
        [StringLength(1)]
        public string Kind { get; set; }
    }
}