// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Keyless]
    [Index(nameof(GoodID), Name = "DB00A")]
    [Index(nameof(SizeNo), Name = "DB00B")]
    [Index(nameof(StoreID), Name = "DB00C")]
    public partial class Pov414Tmp
    {
        [StringLength(20)]
        public string GoodID { get; set; }
        [StringLength(1)]
        public string SizeNo { get; set; }
        [StringLength(15)]
        public string StoreID { get; set; }
        public double? Num01 { get; set; }
        public double? Num02 { get; set; }
        public double? Num03 { get; set; }
        public double? Num04 { get; set; }
        public double? Num05 { get; set; }
        public double? Num06 { get; set; }
        public double? Num07 { get; set; }
        public double? Num08 { get; set; }
        public double? Num09 { get; set; }
        public double? Num10 { get; set; }
        public double? Num11 { get; set; }
        public double? Num12 { get; set; }
        public double? Num13 { get; set; }
        public double? Num14 { get; set; }
        public double? Num15 { get; set; }
        public double? Num16 { get; set; }
        public double? Num17 { get; set; }
        public double? TotalNum { get; set; }
        public double? IntoNum01 { get; set; }
        public double? IntoNum02 { get; set; }
        public double? IntoNum03 { get; set; }
        public double? IntoNum04 { get; set; }
        public double? IntoNum05 { get; set; }
        public double? IntoNum06 { get; set; }
        public double? IntoNum07 { get; set; }
        public double? IntoNum08 { get; set; }
        public double? IntoNum09 { get; set; }
        public double? IntoNum10 { get; set; }
        public double? IntoNum11 { get; set; }
        public double? IntoNum12 { get; set; }
        public double? IntoNum13 { get; set; }
        public double? IntoNum14 { get; set; }
        public double? IntoNum15 { get; set; }
        public double? IntoNum16 { get; set; }
        public double? IntoNum17 { get; set; }
        public double? TotalIntoNum { get; set; }
        [StringLength(4)]
        public string UserID { get; set; }
        [StringLength(5)]
        public string ShelfID { get; set; }
    }
}