// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Keyless]
    public partial class POV402Tmp
    {
        [Required]
        [StringLength(1)]
        public string Flag { get; set; }
        [StringLength(37)]
        public string Group1 { get; set; }
        [StringLength(50)]
        public string Group2 { get; set; }
        public double? Qty { get; set; }
        public double? Cost { get; set; }
        public double? ShouldSell { get; set; }
        public double? QtyPer { get; set; }
        public double? CostPer { get; set; }
        public double? AmtPer { get; set; }
        public int? GoodsCount { get; set; }
    }
}