// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Keyless]
    [Index(nameof(GoodID), Name = "GoodID")]
    [Index(nameof(SizeNo), Name = "KindID")]
    public partial class Pov418tmp
    {
        [StringLength(10)]
        public string UserID { get; set; }
        [Required]
        [StringLength(6)]
        public string Month { get; set; }
        [Required]
        [StringLength(20)]
        public string GoodID { get; set; }
        [Required]
        [StringLength(1)]
        public string SizeNo { get; set; }
        [Required]
        [StringLength(15)]
        public string Store { get; set; }
        public short? StorageNum01 { get; set; }
        public short? StorageNum02 { get; set; }
        public short? StorageNum03 { get; set; }
        public short? StorageNum04 { get; set; }
        public short? StorageNum05 { get; set; }
        public short? StorageNum06 { get; set; }
        public short? StorageNum07 { get; set; }
        public short? StorageNum08 { get; set; }
        public short? StorageNum09 { get; set; }
        public short? StorageNum10 { get; set; }
        public short? StorageNum11 { get; set; }
        public short? StorageNum12 { get; set; }
        public short? StorageNum13 { get; set; }
        public short? StorageNum14 { get; set; }
        public short? StorageNum15 { get; set; }
        public short? StorageNum16 { get; set; }
        public short? StorageNum17 { get; set; }
        public int? StorageTotalNum { get; set; }
        public float? MonthEndCost { get; set; }
        public float? MonthFirstCost { get; set; }
        public int? MonthFirstTotalNum { get; set; }
        public double? StockAmount { get; set; }
        public double? TaxStockAmount { get; set; }
        public int? StockTotalNum { get; set; }
        public int? ShipTotalNum { get; set; }
        public int? TransferTotalNum { get; set; }
        public int? SellTotalNum { get; set; }
        public double? AdjustTotalNum { get; set; }
        public int? TransferAmount { get; set; }
        public double? Cheapen { get; set; }
        public double? ShipAmount { get; set; }
        public double? SellAmount { get; set; }
    }
}