// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Keyless]
    public partial class Pov412temp
    {
        [StringLength(13)]
        public string TP01 { get; set; }
        [StringLength(40)]
        public string TP02 { get; set; }
        [Column(TypeName = "money")]
        public decimal? TP03 { get; set; }
        [Column(TypeName = "money")]
        public decimal? TP04 { get; set; }
        [Column(TypeName = "money")]
        public decimal? TP05 { get; set; }
        [Column(TypeName = "money")]
        public decimal? TP06 { get; set; }
        [Column(TypeName = "money")]
        public decimal? TP07 { get; set; }
        [Column(TypeName = "money")]
        public decimal? TP08 { get; set; }
        [Column(TypeName = "money")]
        public decimal? TP09 { get; set; }
        [Column(TypeName = "money")]
        public decimal? TP10 { get; set; }
        [Column(TypeName = "money")]
        public decimal? TP11 { get; set; }
        public int? TP12 { get; set; }
        public int? TP13 { get; set; }
        public int? TP14 { get; set; }
        public int? TP15 { get; set; }
        public int? TP16 { get; set; }
        public int? TP17 { get; set; }
        public int? TP18 { get; set; }
        [StringLength(4)]
        public string useID { get; set; }
    }
}