// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Keyless]
    [Index(nameof(UserID), Name = "UserID")]
    public partial class Pov415Tmp
    {
        [StringLength(50)]
        public string GoodID { get; set; }
        public double? IntoPrice { get; set; }
        public double? SellPrice { get; set; }
        [StringLength(50)]
        public string OpenDate { get; set; }
        public double? IntoNum { get; set; }
        public double? EndNum { get; set; }
        public double? Cost { get; set; }
        public double? CostNum { get; set; }
        public double? SellNum { get; set; }
        public double? PercentReturn { get; set; }
        public double? PreDate { get; set; }
        [StringLength(150)]
        public string Remark { get; set; }
        public double? AdvicePrice { get; set; }
        [StringLength(4)]
        public string UserID { get; set; }
    }
}