// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Keyless]
    public partial class Pov419Tmp
    {
        [StringLength(15)]
        public string StoreID { get; set; }
        [StringLength(50)]
        public string StoreName { get; set; }
        public double? FirstSort1Num { get; set; }
        public double? FirstSort1Amount { get; set; }
        public double? FirstSort2Num { get; set; }
        public double? FirstSort2Amount { get; set; }
        public double? FirstSort3Num { get; set; }
        public double? FirstSort3Amount { get; set; }
        public double? FirstSort4Num { get; set; }
        public double? FirstSort4Amount { get; set; }
        public double? StockSort1Num { get; set; }
        public double? StockSort1Amount { get; set; }
        public double? StockSort2Num { get; set; }
        public double? StockSort2Amount { get; set; }
        public double? StockSort3Num { get; set; }
        public double? StockSort3Amount { get; set; }
        public double? StockSort4Num { get; set; }
        public double? StockSort4Amount { get; set; }
        public double? SellSort1Num { get; set; }
        public double? SellSort1Amount { get; set; }
        public double? SellSort2Num { get; set; }
        public double? SellSort2Amount { get; set; }
        public double? SellSort3Num { get; set; }
        public double? SellSort3Amount { get; set; }
        public double? SellSort4Num { get; set; }
        public double? SellSort4Amount { get; set; }
        public double? EndSort1Num { get; set; }
        public double? EndSort1Amount { get; set; }
        public double? EndSort2Num { get; set; }
        public double? EndSort2Amount { get; set; }
        public double? EndSort3Num { get; set; }
        public double? EndSort3Amount { get; set; }
        public double? EndSort4Num { get; set; }
        public double? EndSort4Amount { get; set; }
        [StringLength(10)]
        public string UserID { get; set; }
    }
}