// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Keyless]
    public partial class Pov511Tmp
    {
        [StringLength(15)]
        public string BranchID { get; set; }
        [StringLength(50)]
        public string BranchName { get; set; }
        [StringLength(8)]
        public string ActiveMonth { get; set; }
        [StringLength(8)]
        public string CompareMonth { get; set; }
        public double? NowActive { get; set; }
        public double? PreActive { get; set; }
        public double? CompareActive { get; set; }
        public double? ResultActive { get; set; }
        public double? PercentActive { get; set; }
        public double? NowGain { get; set; }
        public double? PreGain { get; set; }
        public double? CompareGain { get; set; }
        public double? ResultGain { get; set; }
        public double? PercentGain { get; set; }
        public double? People { get; set; }
        [StringLength(9)]
        public string UserID { get; set; }
    }
}