// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Keyless]
    public partial class Pov502CalSort
    {
        [StringLength(1)]
        public string InFlag { get; set; }
        [StringLength(1)]
        public string OutFlag { get; set; }
        [StringLength(1)]
        public string SellFlag { get; set; }
        [StringLength(1)]
        public string ModiFlag { get; set; }
        [StringLength(1)]
        public string TranInFlag { get; set; }
        [StringLength(1)]
        public string TranOutFlag { get; set; }
        [StringLength(1)]
        public string StoreFlag { get; set; }
        [StringLength(1)]
        public string CheckFlag { get; set; }
        [StringLength(4)]
        public string UserID { get; set; }
        [StringLength(50)]
        public string Flag { get; set; }
    }
}