// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Keyless]
    public partial class Pov513Temp
    {
        [StringLength(15)]
        public string StoreID { get; set; }
        [StringLength(20)]
        public string GoodID { get; set; }
        [StringLength(50)]
        public string PriceLName { get; set; }
        public double? Price { get; set; }
        public double? CostMoney { get; set; }
        public double? TotalCount { get; set; }
        public double? AdvicePrice { get; set; }
        public double? SpecialPrice { get; set; }
        public double? StoreCount { get; set; }
        public double? TotalMoney { get; set; }
        public double? GrossProfit { get; set; }
        [StringLength(4)]
        public string UserID { get; set; }
        [StringLength(3)]
        public string Flag { get; set; }
    }
}