// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Keyless]
    public partial class Pov514Temp
    {
        [StringLength(30)]
        public string Names { get; set; }
        [StringLength(8)]
        public string Dates { get; set; }
        [StringLength(1)]
        public string Kind { get; set; }
        public int? Time1Count { get; set; }
        public double? Time1Money { get; set; }
        public int? Time2Count { get; set; }
        public double? Time2Money { get; set; }
        public int? Time3Count { get; set; }
        public double? Time3Money { get; set; }
        public int? Time4Count { get; set; }
        public double? Time4Money { get; set; }
        public int? Time5Count { get; set; }
        public double? Time5Money { get; set; }
        public int? Time6Count { get; set; }
        public double? Time6Money { get; set; }
        public int? Time7Count { get; set; }
        public double? Time7Money { get; set; }
        public int? Time8Count { get; set; }
        public double? Time8Money { get; set; }
        public int? Time9Count { get; set; }
        public double? Time9Money { get; set; }
        public int? Time10Count { get; set; }
        public double? Time10Money { get; set; }
        public int? Time11Count { get; set; }
        public double? Time11Money { get; set; }
        public int? Time12Count { get; set; }
        public double? Time12Money { get; set; }
        public int? Time13Count { get; set; }
        public double? Time13Money { get; set; }
        public int? TotalCount { get; set; }
        public double? TotalMoney { get; set; }
        public int? FirstCount { get; set; }
        public double? FirstMoney { get; set; }
        public int? TotalStock { get; set; }
        public int? TotalSell { get; set; }
        public double? TotalSellMoney { get; set; }
        public double? TotalCost { get; set; }
        public double? CheckMoney { get; set; }
        public int? TotalStorage { get; set; }
        public double? TotalStorageMoney { get; set; }
        [StringLength(15)]
        public string Branch { get; set; }
        [StringLength(20)]
        public string GoodID { get; set; }
        [StringLength(8)]
        public string Brand { get; set; }
        [StringLength(8)]
        public string Sort { get; set; }
        [StringLength(8)]
        public string Factory { get; set; }
        [StringLength(4)]
        public string Person { get; set; }
        public int? SellCount { get; set; }
        public double? SellMoney { get; set; }
        public int? Factory1Count { get; set; }
        public double? Factory1Money { get; set; }
        public int? Factory2Count { get; set; }
        public double? Factory2Money { get; set; }
        public int? Factory3Count { get; set; }
        public double? Factory3Money { get; set; }
        public int? Factory4Count { get; set; }
        public double? Factory4Money { get; set; }
        public int? Factory5Count { get; set; }
        public double? Factory5Money { get; set; }
        public double? SellCashMoney { get; set; }
        public double? SellCardMoney { get; set; }
        public double? SellGiftMoney { get; set; }
        public double? Sort1Money { get; set; }
        public double? Sort2Money { get; set; }
        public double? Sort3Money { get; set; }
        public double? Sort4Money { get; set; }
        public double? Sort5Money { get; set; }
        public double? GapMoney { get; set; }
        public double? OutMoney { get; set; }
        public double? InMoney { get; set; }
        [StringLength(50)]
        public string UserID { get; set; }
    }
}