// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Keyless]
    [Index(nameof(BrandID), Name = "BrandID")]
    [Index(nameof(UserID), Name = "UserID")]
    public partial class Pov512Tmp
    {
        [StringLength(10)]
        public string BrandID { get; set; }
        [StringLength(15)]
        public string SellBranch { get; set; }
        [StringLength(8)]
        public string SellDate { get; set; }
        public double? AmountTen { get; set; }
        public double? AmountNine { get; set; }
        public double? AmountEight { get; set; }
        public double? AmountSeven { get; set; }
        public double? AmountSix { get; set; }
        public double? AmountFive { get; set; }
        public double? AmountFour { get; set; }
        public double? AmountThree { get; set; }
        public double? SellAmount { get; set; }
        public double? AmountCard { get; set; }
        public double? SellCost { get; set; }
        public double? AmountTotal { get; set; }
        public double? TotalTen { get; set; }
        public double? TotalNine { get; set; }
        public double? TotalEight { get; set; }
        public double? TotalSeven { get; set; }
        public double? TotalSix { get; set; }
        public double? TotalFive { get; set; }
        public double? TotalFour { get; set; }
        public double? TotalThree { get; set; }
        public double? TotalSell { get; set; }
        public double? TotalCard { get; set; }
        [StringLength(5)]
        public string UserID { get; set; }
        public double? SellMoney { get; set; }
        public double? SellDis { get; set; }
        public double? AmountTwo { get; set; }
        public double? AmountOne { get; set; }
        public double? TotalTwo { get; set; }
        public double? TotalOne { get; set; }
        public double? UntaxCost { get; set; }
        public double? UntaxTotal { get; set; }
        public double? UntaxSell { get; set; }
        public double? UntaxCard { get; set; }
        public double? UntaxOne { get; set; }
        public double? UntaxTwo { get; set; }
        public double? UntaxThree { get; set; }
        public double? UntaxFour { get; set; }
        public double? UntaxFive { get; set; }
        public double? UntaxSix { get; set; }
        public double? UntaxSeven { get; set; }
        public double? UntaxEight { get; set; }
        public double? UntaxNine { get; set; }
        public double? UntaxTen { get; set; }
        public double? UntaxMoney { get; set; }
        public double? UntaxDis { get; set; }
    }
}