// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Keyless]
    public partial class Pov502Temp
    {
        [StringLength(12)]
        public string Kind { get; set; }
        [StringLength(20)]
        public string OrderID { get; set; }
        [StringLength(40)]
        public string StoreID { get; set; }
        public double? S1 { get; set; }
        public double? S2 { get; set; }
        public double? S3 { get; set; }
        public double? S4 { get; set; }
        public double? S5 { get; set; }
        public double? S6 { get; set; }
        public double? S7 { get; set; }
        public double? S8 { get; set; }
        public double? S9 { get; set; }
        public double? S10 { get; set; }
        public double? S11 { get; set; }
        public double? S12 { get; set; }
        public double? S13 { get; set; }
        public double? S14 { get; set; }
        public double? S15 { get; set; }
        public double? S16 { get; set; }
        public double? S17 { get; set; }
        public double? Total { get; set; }
        [StringLength(8)]
        public string Dates { get; set; }
        public double? Value { get; set; }
        [StringLength(255)]
        public string Remark { get; set; }
        [StringLength(20)]
        public string GoodID { get; set; }
        [StringLength(1)]
        public string SizeNo { get; set; }
        public int? KindID { get; set; }
        [StringLength(200)]
        public string GoodName { get; set; }
        [StringLength(1)]
        public string SizeNo1 { get; set; }
        [StringLength(1)]
        public string SizeNo2 { get; set; }
        [StringLength(1)]
        public string SizeNo3 { get; set; }
        [StringLength(8)]
        public string OpenDate { get; set; }
        [StringLength(10)]
        public string Factory { get; set; }
        [StringLength(4)]
        public string UserID { get; set; }
        [StringLength(2)]
        public string MySellFlagA { get; set; }
        [StringLength(2)]
        public string MySellFlagB { get; set; }
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [StringLength(8)]
        public string ChangePerson { get; set; }
    }
}