// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Keyless]
    public partial class Pov518Temp
    {
        [StringLength(50)]
        public string Names { get; set; }
        public double? Month1Count { get; set; }
        [Column(TypeName = "money")]
        public decimal? Month1Money { get; set; }
        public double? Month2Count { get; set; }
        [Column(TypeName = "money")]
        public decimal? Month2Money { get; set; }
        public double? Month3Count { get; set; }
        [Column(TypeName = "money")]
        public decimal? Month3Money { get; set; }
        public double? TotalCount { get; set; }
        [Column(TypeName = "money")]
        public decimal? TotalMoney { get; set; }
        [Column(TypeName = "money")]
        public decimal? GapMoney { get; set; }
        [Column(TypeName = "money")]
        public decimal? Gross { get; set; }
        [Column(TypeName = "money")]
        public decimal? GetMoney { get; set; }
        [Column(TypeName = "money")]
        public decimal? CostMoney { get; set; }
        [StringLength(1)]
        public string Kind { get; set; }
        [StringLength(1)]
        public string ClassID { get; set; }
        [StringLength(9)]
        public string UserID { get; set; }
        [StringLength(50)]
        public string OrderID { get; set; }
        [StringLength(50)]
        public string SortName { get; set; }
        [StringLength(15)]
        public string ClientID { get; set; }
    }
}