// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Keyless]
    public partial class Pov507Temp
    {
        [Required]
        [StringLength(50)]
        public string UserID { get; set; }
        [StringLength(50)]
        public string GoodID { get; set; }
        [StringLength(50)]
        public string GoodName { get; set; }
        [StringLength(50)]
        public string FactoryID { get; set; }
        [StringLength(50)]
        public string FactoryShort { get; set; }
        [StringLength(50)]
        public string BrandID { get; set; }
        [StringLength(50)]
        public string BrandName { get; set; }
        [StringLength(50)]
        public string Class1ID { get; set; }
        [StringLength(50)]
        public string Class1Name { get; set; }
        [StringLength(50)]
        public string Class2ID { get; set; }
        [StringLength(50)]
        public string Class2Name { get; set; }
        [StringLength(50)]
        public string Class3ID { get; set; }
        [StringLength(50)]
        public string Class3Name { get; set; }
        [StringLength(50)]
        public string Class4ID { get; set; }
        [StringLength(50)]
        public string Class4Name { get; set; }
        [StringLength(50)]
        public string Class5ID { get; set; }
        [StringLength(50)]
        public string Class5Name { get; set; }
        [StringLength(8)]
        public string OpenDate { get; set; }
        [StringLength(8)]
        public string FirstShipDate { get; set; }
        public double? SellNum { get; set; }
        public double? SellAmount { get; set; }
        public double? SellProfit { get; set; }
        public double? StockNum { get; set; }
        public double? MonthStockNum { get; set; }
        public double? MultiSellStock { get; set; }
        public double? MultiSellMonth { get; set; }
        public double? ProfitPercent { get; set; }
        public double? SellPercent { get; set; }
        public int? SellDay { get; set; }
        public int? NoSellDay { get; set; }
        public Guid? RowID { get; set; }
    }
}