// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Keyless]
    public partial class Pov504Temp
    {
        [StringLength(20)]
        public string GoodID { get; set; }
        [StringLength(1)]
        public string SizeNo { get; set; }
        [StringLength(20)]
        public string OrderID { get; set; }
        [StringLength(15)]
        public string ClientID { get; set; }
        [StringLength(40)]
        public string ClientName { get; set; }
        public double? TotalQty { get; set; }
        public double? TotalMny { get; set; }
        public double? TotalQty1 { get; set; }
        public double? TotalQty2 { get; set; }
        public double? TotalQty3 { get; set; }
        public double? TotalQty4 { get; set; }
        public double? TotalQty5 { get; set; }
        public double? TotalQty6 { get; set; }
        public double? TotalQty7 { get; set; }
        public double? TotalQty8 { get; set; }
        public double? TotalQty9 { get; set; }
        public double? TotalQty10 { get; set; }
        public double? TotalQty11 { get; set; }
        public double? TotalQty12 { get; set; }
        public double? TotalQty13 { get; set; }
        public double? TotalQty14 { get; set; }
        public double? TotalQty15 { get; set; }
        public double? TotalQty16 { get; set; }
        public double? TotalQty17 { get; set; }
        public double? TotalStore { get; set; }
        public double? TotalStore1 { get; set; }
        public double? TotalStore2 { get; set; }
        public double? TotalStore3 { get; set; }
        public double? TotalStore4 { get; set; }
        public double? TotalStore5 { get; set; }
        public double? TotalStore6 { get; set; }
        public double? TotalStore7 { get; set; }
        public double? TotalStore8 { get; set; }
        public double? TotalStore9 { get; set; }
        public double? TotalStore10 { get; set; }
        public double? TotalStore11 { get; set; }
        public double? TotalStore12 { get; set; }
        public double? TotalStore13 { get; set; }
        public double? TotalStore14 { get; set; }
        public double? TotalStore15 { get; set; }
        public double? TotalStore16 { get; set; }
        public double? TotalStore17 { get; set; }
        [StringLength(4)]
        public string UserID { get; set; }
        [StringLength(10)]
        public string FactoryID { get; set; }
        [StringLength(255)]
        public string FactoryName { get; set; }
        public double? TotalSell { get; set; }
        public double? TotalAllStore { get; set; }
        public double? TotalUnStock { get; set; }
        public double? TotalUnShip { get; set; }
        [StringLength(8)]
        public string StockDate { get; set; }
        [StringLength(2)]
        public string State { get; set; }
        [StringLength(10)]
        public string Sort01 { get; set; }
        [StringLength(10)]
        public string Sort02 { get; set; }
        [StringLength(10)]
        public string Sort03 { get; set; }
        [StringLength(10)]
        public string Sort04 { get; set; }
        [StringLength(10)]
        public string Sort05 { get; set; }
        public double? TotalCost { get; set; }
        public double? TotalGrain { get; set; }
        public double? OrderNoDeal { get; set; }
        public double? PurNoDeal { get; set; }
        [StringLength(200)]
        public string GoodName { get; set; }
        public double? MainStNum { get; set; }
    }
}