// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Keyless]
    public partial class Pov523Temp
    {
        [Required]
        [StringLength(50)]
        public string UserID { get; set; }
        [StringLength(50)]
        public string GoodID { get; set; }
        [StringLength(50)]
        public string GoodName { get; set; }
        [StringLength(50)]
        public string FactoryID { get; set; }
        [StringLength(50)]
        public string FactoryShort { get; set; }
        [StringLength(50)]
        public string BrandID { get; set; }
        [StringLength(50)]
        public string BrandName { get; set; }
        [StringLength(50)]
        public string Class1ID { get; set; }
        [StringLength(50)]
        public string Class1Name { get; set; }
        [StringLength(50)]
        public string Class2ID { get; set; }
        [StringLength(50)]
        public string Class2Name { get; set; }
        [StringLength(50)]
        public string Class3ID { get; set; }
        [StringLength(50)]
        public string Class3Name { get; set; }
        [StringLength(50)]
        public string Class4ID { get; set; }
        [StringLength(50)]
        public string Class4Name { get; set; }
        [StringLength(50)]
        public string Class5ID { get; set; }
        [StringLength(50)]
        public string Class5Name { get; set; }
        [StringLength(15)]
        public string StoreID { get; set; }
        [StringLength(80)]
        public string StoreName { get; set; }
        [StringLength(4)]
        public string EmpID { get; set; }
        [StringLength(50)]
        public string EmpName { get; set; }
        public double? StockNum { get; set; }
        public double? StockPercent { get; set; }
        public double? NoTaxAmount { get; set; }
        public double? TaxAmount { get; set; }
        public double? TotalAmount { get; set; }
        public double? AmountPercent { get; set; }
        public Guid RowID { get; set; }
        [StringLength(5)]
        public string Season { get; set; }
    }
}