// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Keyless]
    public partial class Pov581Tmp
    {
        [StringLength(15)]
        public string StoreID { get; set; }
        [StringLength(20)]
        public string GoodID { get; set; }
        [StringLength(15)]
        public string OccDate { get; set; }
        public int? PreNum { get; set; }
        public double? PreAmt { get; set; }
        public int? InNum { get; set; }
        public double? InAmt { get; set; }
        public int? TranInNum { get; set; }
        public double? TranInAmt { get; set; }
        public int? SellNum { get; set; }
        public double? SellAmt { get; set; }
        public int? TranOutNum { get; set; }
        public double? TranOutAmt { get; set; }
        public int? BackNum { get; set; }
        public double? BackAmt { get; set; }
        public int? DiffNum { get; set; }
        public double? DiffAmt { get; set; }
        public int? EndNum { get; set; }
        public double? EndAmt { get; set; }
        public int? PreTotalSellNum { get; set; }
        public double? PreTotalSellAmt { get; set; }
        public int? EndTotalSellNum { get; set; }
        public double? EndTotalSellAmt { get; set; }
        [StringLength(200)]
        public string Remark { get; set; }
        public int? IsMinDate { get; set; }
        public int? IsMaxDate { get; set; }
        [StringLength(9)]
        public string UserID { get; set; }
        public int? ShipNum { get; set; }
        public double? ShipAmt { get; set; }
        public int? ShipBackNum { get; set; }
        public double? ShipBackAmt { get; set; }
    }
}