// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Keyless]
    public partial class Pov576Tmp
    {
        [Required]
        [StringLength(10)]
        public string GroupFldID { get; set; }
        [Required]
        [StringLength(40)]
        public string GroupFldName { get; set; }
        [Required]
        [StringLength(15)]
        public string ClientID { get; set; }
        [Required]
        [StringLength(20)]
        public string ClientShort { get; set; }
        [Required]
        [StringLength(1)]
        public string Flag { get; set; }
        public int? InNum { get; set; }
        public double? InAmount { get; set; }
        public int? SellNum { get; set; }
        public double? SellAmount { get; set; }
        public double? SellCost { get; set; }
        public double? StockNum { get; set; }
        public double? StockAmount { get; set; }
        [Required]
        [StringLength(3)]
        public string UserID { get; set; }
    }
}