// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Keyless]
    public partial class pov536temp
    {
        public int? mode { get; set; }
        [StringLength(40)]
        public string sort01name { get; set; }
        [StringLength(40)]
        public string sort02name { get; set; }
        [StringLength(40)]
        public string sort03name { get; set; }
        [StringLength(40)]
        public string sort04name { get; set; }
        [StringLength(40)]
        public string sort05name { get; set; }
        public double? other { get; set; }
        public double? total { get; set; }
        public double? price1 { get; set; }
        public double? price2 { get; set; }
        public double? price3 { get; set; }
        public double? price4 { get; set; }
        public double? price5 { get; set; }
        public double? price6 { get; set; }
        public double? price7 { get; set; }
        public double? price8 { get; set; }
    }
}