// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Keyless]
    public partial class Pov516Temp
    {
        [StringLength(20)]
        public string GoodID { get; set; }
        [StringLength(15)]
        public string Store { get; set; }
        [StringLength(8)]
        public string InDate { get; set; }
        public int? InCount { get; set; }
        public double? InMoney { get; set; }
        public int? OutCount { get; set; }
        public double? OutMoney { get; set; }
        public int? StoreCount { get; set; }
        public double? StoreMoney { get; set; }
        [StringLength(4)]
        public string UserID { get; set; }
    }
}