// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Keyless]
    public partial class Pov5201ATemp
    {
        [StringLength(13)]
        public string Names { get; set; }
        [StringLength(8)]
        public string Sort01 { get; set; }
        [StringLength(8)]
        public string Sort02 { get; set; }
        [StringLength(8)]
        public string Sort03 { get; set; }
        [StringLength(8)]
        public string Sort04 { get; set; }
        [StringLength(8)]
        public string Sort05 { get; set; }
        public int? Week1OutCount { get; set; }
        public int? Week2OutCount { get; set; }
        public int? Week3OutCount { get; set; }
        public int? Week4OutCount { get; set; }
        public int? Week5OutCount { get; set; }
        public int? Week6OutCount { get; set; }
        public int? Week7OutCount { get; set; }
        public int? Week8OutCount { get; set; }
        public int? Week9OutCount { get; set; }
        public int? Week10OutCount { get; set; }
        public int? Week11OutCount { get; set; }
        public int? Week12OutCount { get; set; }
        public int? Week13OutCount { get; set; }
        public int? Week1InCount { get; set; }
        public int? Week2InCount { get; set; }
        public int? Week3InCount { get; set; }
        public int? Week4InCount { get; set; }
        public int? Week5InCount { get; set; }
        public int? Week6InCount { get; set; }
        public int? Week7InCount { get; set; }
        public int? Week8InCount { get; set; }
        public int? Week9InCount { get; set; }
        public int? Week10InCount { get; set; }
        public int? Week11InCount { get; set; }
        public int? Week12InCount { get; set; }
        public int? Week13InCount { get; set; }
        [StringLength(1)]
        public string Kind { get; set; }
        [StringLength(9)]
        public string UserID { get; set; }
        [StringLength(10)]
        public string FactoryID { get; set; }
        [StringLength(50)]
        public string FactoryName { get; set; }
    }
}