// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Keyless]
    public partial class pov534temp
    {
        [StringLength(9)]
        public string User_id { get; set; }
        [StringLength(4)]
        public string year { get; set; }
        [StringLength(6)]
        public string season { get; set; }
        [StringLength(40)]
        public string sort01 { get; set; }
        [StringLength(40)]
        public string sort02 { get; set; }
        [StringLength(40)]
        public string sort03 { get; set; }
        [StringLength(40)]
        public string sort04 { get; set; }
        [StringLength(40)]
        public string sort05 { get; set; }
        public double? st { get; set; }
        public double? sh { get; set; }
        public double? sg { get; set; }
    }
}