// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Keyless]
    public partial class Pov5202Temp
    {
        [StringLength(20)]
        public string Names { get; set; }
        public double? IntoPrice { get; set; }
        public double? Price { get; set; }
        public double? SpecialPrice { get; set; }
        [StringLength(8)]
        public string OpenDate { get; set; }
        public double? Week1OutCount { get; set; }
        public double? Week2OutCount { get; set; }
        public double? Week3OutCount { get; set; }
        public double? Week4OutCount { get; set; }
        public double? Week5OutCount { get; set; }
        public double? Week6OutCount { get; set; }
        public double? Week7OutCount { get; set; }
        public double? Week8OutCount { get; set; }
        public double? Week9OutCount { get; set; }
        public double? Week10OutCount { get; set; }
        public double? Week11OutCount { get; set; }
        public double? Week12OutCount { get; set; }
        public double? Week13OutCount { get; set; }
        public double? Week1InCount { get; set; }
        public double? Week2InCount { get; set; }
        public double? Week3InCount { get; set; }
        public double? Week4InCount { get; set; }
        public double? Week5InCount { get; set; }
        public double? Week6InCount { get; set; }
        public double? Week7InCount { get; set; }
        public double? Week8InCount { get; set; }
        public double? Week9InCount { get; set; }
        public double? Week10InCount { get; set; }
        public double? Week11InCount { get; set; }
        public double? Week12InCount { get; set; }
        public double? Week13InCount { get; set; }
        [StringLength(50)]
        public string Rotate1 { get; set; }
        [StringLength(50)]
        public string Rotate2 { get; set; }
        [StringLength(50)]
        public string Rotate3 { get; set; }
        [StringLength(50)]
        public string Rotate4 { get; set; }
        [StringLength(50)]
        public string Rotate5 { get; set; }
        [StringLength(50)]
        public string Rotate6 { get; set; }
        [StringLength(50)]
        public string Rotate7 { get; set; }
        [StringLength(50)]
        public string Rotate8 { get; set; }
        [StringLength(50)]
        public string Rotate9 { get; set; }
        [StringLength(50)]
        public string Rotate10 { get; set; }
        [StringLength(50)]
        public string Rotate11 { get; set; }
        [StringLength(50)]
        public string Rotate12 { get; set; }
        [StringLength(50)]
        public string Rotate13 { get; set; }
        public double? StorageCount { get; set; }
        [StringLength(20)]
        public string OrderID { get; set; }
        [StringLength(1)]
        public string Kind { get; set; }
        [StringLength(9)]
        public string UserID { get; set; }
        [StringLength(50)]
        public string SellDiscount { get; set; }
        public double? Total13InCount { get; set; }
        public double? Total13OutCount { get; set; }
        public double? OutMoney { get; set; }
        [StringLength(20)]
        public string OutID { get; set; }
    }
}