// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Keyless]
    public partial class Pov610temp
    {
        [Required]
        [StringLength(3)]
        public string TranInStore { get; set; }
        [Required]
        [StringLength(3)]
        public string TranOutStore { get; set; }
        [Required]
        [StringLength(20)]
        public string GoodID { get; set; }
        [Required]
        [StringLength(1)]
        public string SizeNo { get; set; }
        public double? TranNum1 { get; set; }
        public double? TranNum2 { get; set; }
        public double? TranNum3 { get; set; }
        public double? TranNum4 { get; set; }
        public double? TranNum5 { get; set; }
        public double? TranNum6 { get; set; }
        public double? TranNum7 { get; set; }
        public double? TranNum8 { get; set; }
        public double? TranNum9 { get; set; }
        public double? TranNum10 { get; set; }
        public double? TranNum11 { get; set; }
        public double? TranNum12 { get; set; }
        public double? TranNum13 { get; set; }
        public double? TranNum14 { get; set; }
        public double? TranNum15 { get; set; }
        public double? TranNum16 { get; set; }
        public double? TranNum17 { get; set; }
        public double? TotalTranNum { get; set; }
        public double Price { get; set; }
        public double? Amount { get; set; }
        public double Cost { get; set; }
        public double? CostAmount { get; set; }
        [Required]
        [StringLength(10)]
        public string Brand { get; set; }
        [Required]
        [StringLength(10)]
        public string Factory { get; set; }
        public int Pos { get; set; }
    }
}