// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Keyless]
    public partial class POVInTranTemp
    {
        [StringLength(15)]
        public string StoreCode { get; set; }
        [StringLength(20)]
        public string CustName { get; set; }
        [StringLength(10)]
        public string FactoryID { get; set; }
        [StringLength(40)]
        public string FactoryShort { get; set; }
        [StringLength(8)]
        public string InOut_Date { get; set; }
        [StringLength(20)]
        public string ID { get; set; }
        public double? InQty { get; set; }
        public double? InAmt { get; set; }
        public double? OutQty { get; set; }
        public double? OutAmt { get; set; }
        [Required]
        [StringLength(9)]
        public string UserID { get; set; }
        [StringLength(10)]
        public string ModeName { get; set; }
        [StringLength(1)]
        public string OrderID { get; set; }
    }
}