// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    public partial class POVShip
    {
        [Key]
        public int CompanyID { get; set; }
        [Key]
        [StringLength(11)]
        public string ShipID { get; set; }
        [StringLength(20)]
        public string MemberID { get; set; }
        public bool isReturn { get; set; }
        [StringLength(200)]
        public string CollectionID { get; set; }
        public int? PaymentID { get; set; }
        public int CarriageAmount { get; set; }
        public int DeliveryCharge { get; set; }
        public int PointCash { get; set; }
        public int ProjectCash { get; set; }
        public bool IsNeedInvoice { get; set; }
        [StringLength(1)]
        public string InvoiceType { get; set; }
        [StringLength(50)]
        public string InvoiceTitle { get; set; }
        [StringLength(12)]
        public string InvoiceNo { get; set; }
        [StringLength(8)]
        public string UnifiedNum { get; set; }
        [StringLength(30)]
        public string ReceiverName { get; set; }
        [StringLength(1000)]
        public string Address { get; set; }
        [StringLength(16)]
        public string PhoneNo { get; set; }
        [StringLength(20)]
        public string TelNo { get; set; }
        [StringLength(100)]
        public string EMail { get; set; }
        [Column(TypeName = "ntext")]
        public string Remark { get; set; }
        public int? FlagID { get; set; }
        [StringLength(50)]
        public string OrderID { get; set; }
        [StringLength(50)]
        public string OrderID2 { get; set; }
        [StringLength(50)]
        public string Remark1 { get; set; }
        [StringLength(50)]
        public string Remark2 { get; set; }
        [StringLength(50)]
        public string Remark3 { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ShipDate { get; set; }
        [StringLength(6)]
        public string e7StoreID { get; set; }
        [StringLength(10)]
        public string e7StoreName { get; set; }
        [StringLength(20)]
        public string DistributionID { get; set; }
        public bool? ToSIN { get; set; }
        public bool? ToDC { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ToDCTime { get; set; }
        [StringLength(20)]
        public string ToDCRemark { get; set; }
        public bool? ToShop { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ToShopTime { get; set; }
        public bool? ToShopNotified { get; set; }
        [StringLength(20)]
        public string ToShopRemark { get; set; }
        public bool? ToClient { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ToClientTime { get; set; }
        public bool? Paid { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? PayTime { get; set; }
        public bool? DCReturn { get; set; }
        [StringLength(20)]
        public string DCReturnRemark { get; set; }
        public long? PlatformID { get; set; }
        [StringLength(1)]
        public string ShipMode { get; set; }
        [StringLength(50)]
        public string WayGoID { get; set; }
        [StringLength(50)]
        public string GroupID { get; set; }
        [StringLength(50)]
        public string WayStoreID { get; set; }
        [StringLength(50)]
        public string WayStoreName { get; set; }
        [StringLength(1)]
        public string ShipCheckFlag { get; set; }
        [StringLength(30)]
        public string WayID { get; set; }
        [StringLength(50)]
        public string Fname { get; set; }
        [StringLength(50)]
        public string SiteUrl { get; set; }
        [StringLength(25)]
        public string Ftel { get; set; }
    }
}