// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    public partial class PreArchieveSetting
    {
        [Key]
        [StringLength(13)]
        public string SerialID { get; set; }
        [Key]
        [StringLength(3)]
        public string Item { get; set; }
        [Required]
        [StringLength(1)]
        public string Type { get; set; }
        [Required]
        [StringLength(8)]
        public string Months { get; set; }
        [Required]
        [StringLength(15)]
        public string StoreID { get; set; }
        [Required]
        [StringLength(10)]
        public string BrandID { get; set; }
        [Required]
        [StringLength(4)]
        public string EmpID { get; set; }
        [Required]
        [StringLength(8)]
        public string SortID { get; set; }
        public double PreNum { get; set; }
        public double PreAmount { get; set; }
        [Required]
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [Required]
        [StringLength(4)]
        public string ChangePerson { get; set; }
        [StringLength(1)]
        public string SortType { get; set; }
        [StringLength(8)]
        public string Sort01ID { get; set; }
        [StringLength(8)]
        public string Sort02ID { get; set; }
    }
}