// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Index(nameof(PrePurchaseID), Name = "DR00A")]
    [Index(nameof(PrePurchaseFactory), nameof(PrePurchaseID), Name = "DR00B")]
    [Index(nameof(DealFlag), nameof(PrePurchaseFactory), nameof(PrePurchaseDate), Name = "DR00C")]
    [Index(nameof(GoodID), Name = "GoodID")]
    public partial class PrePurchase
    {
        [Key]
        [StringLength(13)]
        public string PrePurchaseID { get; set; }
        [StringLength(8)]
        public string PrePurchaseDate { get; set; }
        [StringLength(8)]
        public string PrePurchaseStore { get; set; }
        [StringLength(3)]
        public string PrePurchaseFactory { get; set; }
        [StringLength(20)]
        public string GoodID { get; set; }
        [StringLength(1)]
        public string SizeNo { get; set; }
        public double? PrePurchaseNum1 { get; set; }
        public double? PrePurchaseNum2 { get; set; }
        public double? PrePurchaseNum3 { get; set; }
        public double? PrePurchaseNum4 { get; set; }
        public double? PrePurchaseNum5 { get; set; }
        public double? PrePurchaseNum6 { get; set; }
        public double? PrePurchaseNum7 { get; set; }
        public double? PrePurchaseNum8 { get; set; }
        public double? PrePurchaseNum9 { get; set; }
        public double? PrePurchaseNum10 { get; set; }
        public double? PrePurchaseNum11 { get; set; }
        public double? PrePurchaseNum12 { get; set; }
        public double? PrePurchaseNum13 { get; set; }
        public double? PrePurchaseNum14 { get; set; }
        public double? PrePurchaseNum15 { get; set; }
        public double? PrePurchaseNum16 { get; set; }
        public double? PrePurchaseNum17 { get; set; }
        public double? TotalPrePurchaseNum { get; set; }
        public double? PrePurchasePrice { get; set; }
        public double? PrePurchaseAmount { get; set; }
        [StringLength(1)]
        public string PrePurchaseMode { get; set; }
        [StringLength(8)]
        public string PreDealDate { get; set; }
        [StringLength(1)]
        public string DealFlag { get; set; }
        [StringLength(100)]
        public string Remark { get; set; }
        [StringLength(4)]
        public string FillPerson { get; set; }
        [StringLength(1)]
        public string CancelFlag { get; set; }
        [StringLength(10)]
        public string Brand { get; set; }
        [StringLength(10)]
        public string Factory { get; set; }
        [StringLength(1)]
        public string DealMode { get; set; }
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [StringLength(4)]
        public string ChangePerson { get; set; }
        [Key]
        [StringLength(3)]
        public string Item { get; set; }
    }
}