// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    public partial class PreStore
    {
        [Key]
        [StringLength(13)]
        public string SerialID { get; set; }
        [Key]
        [StringLength(3)]
        public string Item { get; set; }
        [Required]
        [StringLength(1)]
        public string SortState { get; set; }
        [Required]
        [StringLength(8)]
        public string OccDate { get; set; }
        [Required]
        [StringLength(15)]
        public string StoreID { get; set; }
        [Required]
        [StringLength(4)]
        public string FillPerson { get; set; }
        [Required]
        [StringLength(200)]
        public string RemarkD { get; set; }
        [Required]
        [StringLength(50)]
        public string Remark { get; set; }
        [Required]
        [StringLength(20)]
        public string GoodID { get; set; }
        [Required]
        [StringLength(3)]
        public string SizeNo { get; set; }
        [Required]
        [StringLength(50)]
        public string Type { get; set; }
        [Required]
        [StringLength(50)]
        public string TypeName { get; set; }
        public double Num1 { get; set; }
        public double Num2 { get; set; }
        public double Num3 { get; set; }
        public double Num4 { get; set; }
        public double Num5 { get; set; }
        public double Num6 { get; set; }
        public double Num7 { get; set; }
        public double Num8 { get; set; }
        public double Num9 { get; set; }
        public double Num10 { get; set; }
        public double Num11 { get; set; }
        public double Num12 { get; set; }
        public double Num13 { get; set; }
        public double Num14 { get; set; }
        public double Num15 { get; set; }
        public double Num16 { get; set; }
        public double Num17 { get; set; }
        public double TotalNum { get; set; }
        [Required]
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [Required]
        [StringLength(4)]
        public string ChangePerson { get; set; }
        [StringLength(8)]
        public string StartDate { get; set; }
        [StringLength(8)]
        public string EndDate { get; set; }
        [StringLength(1)]
        public string HavePurchaseFlag { get; set; }
    }
}