// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Index(nameof(PreStockMode), Name = "ChangeID")]
    [Index(nameof(CloseMonth), nameof(PreStockDate), Name = "DDA0B")]
    [Index(nameof(FactoryID), Name = "FactoryID")]
    [Index(nameof(InvoiceID), Name = "InvoiceID")]
    public partial class PreStock
    {
        [Key]
        [StringLength(13)]
        public string PreStockID { get; set; }
        [StringLength(13)]
        public string FactoryID { get; set; }
        [StringLength(8)]
        public string PreStockDate { get; set; }
        [StringLength(4)]
        public string PreStockFactory { get; set; }
        [StringLength(6)]
        public string CloseMonth { get; set; }
        [StringLength(1)]
        public string PreStockMode { get; set; }
        [StringLength(8)]
        public string StockStore { get; set; }
        [StringLength(1)]
        public string DealMode { get; set; }
        public double? ShouldAmount { get; set; }
        public double? TaxPercent { get; set; }
        public double? Tax { get; set; }
        public double? DiscountPercent { get; set; }
        public double? Discount { get; set; }
        public double? DiscountAmount { get; set; }
        public double? OtherAmount { get; set; }
        public double? ChargeAmount { get; set; }
        [StringLength(1)]
        public string ChargeMode { get; set; }
        [StringLength(10)]
        public string Brand { get; set; }
        [StringLength(10)]
        public string Factory { get; set; }
        [StringLength(4)]
        public string Operation { get; set; }
        public int? Variable { get; set; }
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [StringLength(4)]
        public string ChangePerson { get; set; }
        [StringLength(1)]
        public string CloseAccount { get; set; }
        public double? InvoiceAmount { get; set; }
        [StringLength(8)]
        public string InvoiceDate { get; set; }
        [StringLength(10)]
        public string InvoiceID { get; set; }
        public double? PaymentAmount { get; set; }
        [StringLength(100)]
        public string Remark { get; set; }
        [StringLength(1)]
        public string TaxMode { get; set; }
    }
}