// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Index(nameof(PreTranID), Name = "DE00A")]
    [Index(nameof(FillPerson), nameof(GoodID), nameof(PreTranDate), Name = "DE00B")]
    [Index(nameof(PreTranNum2), nameof(PreTranInStore), nameof(PreTranDate), Name = "DE00C")]
    public partial class PreTransfer
    {
        [Key]
        [StringLength(13)]
        public string PreTranID { get; set; }
        [StringLength(15)]
        public string PreTranOutStore { get; set; }
        [StringLength(8)]
        public string PreTranDate { get; set; }
        [StringLength(15)]
        public string PreTranInStore { get; set; }
        [StringLength(4)]
        public string FillPerson { get; set; }
        [StringLength(20)]
        public string GoodID { get; set; }
        [StringLength(1)]
        public string SizeNo { get; set; }
        public double? PreTranNum1 { get; set; }
        public double? PreTranNum2 { get; set; }
        public double? PreTranNum3 { get; set; }
        public double? PreTranNum4 { get; set; }
        public double? PreTranNum5 { get; set; }
        public double? PreTranNum6 { get; set; }
        public double? PreTranNum7 { get; set; }
        public double? PreTranNum8 { get; set; }
        public double? PreTranNum9 { get; set; }
        public double? PreTranNum10 { get; set; }
        public double? PreTranNum11 { get; set; }
        public double? PreTranNum12 { get; set; }
        public double? PreTranNum13 { get; set; }
        public double? PreTranNum14 { get; set; }
        public double? PreTranNum15 { get; set; }
        public double? PreTranNum16 { get; set; }
        public double? PreTranNum17 { get; set; }
        public double? TotalPreTranNum { get; set; }
        public double? PreTranPrice { get; set; }
        public double? PreTranAmount { get; set; }
        public double? PreTranTotalAmount { get; set; }
        [StringLength(100)]
        public string Remark { get; set; }
        [StringLength(10)]
        public string Brand { get; set; }
        [StringLength(10)]
        public string Factory { get; set; }
        [StringLength(8)]
        public string ChangeDate { get; set; }
        public double? PreTranCost { get; set; }
        [StringLength(4)]
        public string ChangePerson { get; set; }
        [Key]
        [StringLength(3)]
        public string Item { get; set; }
        [StringLength(1)]
        public string RecordFlag { get; set; }
        public short? SheetFlag { get; set; }
    }
}