// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Keyless]
    [Index(nameof(PriceID), Name = "PriceID")]
    public partial class PriceL
    {
        [StringLength(4)]
        public string PriceID { get; set; }
        [StringLength(20)]
        public string PriceName { get; set; }
        public double? PriceBegin { get; set; }
        public double? PriceEnd { get; set; }
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [StringLength(4)]
        public string ChangePerson { get; set; }
    }
}