// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Keyless]
    [Index(nameof(GoodID), Name = "GoodID")]
    public partial class PriceAdjust
    {
        [StringLength(8)]
        public string AdjustStore { get; set; }
        [StringLength(6)]
        public string AdjustMonth { get; set; }
        [StringLength(20)]
        public string GoodID { get; set; }
        [StringLength(15)]
        public string GoodName { get; set; }
        public double? Price { get; set; }
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [StringLength(10)]
        public string ChangePerson { get; set; }
        [StringLength(2)]
        public string Sign { get; set; }
    }
}