// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    public partial class ProgramTask
    {
        [Key]
        [StringLength(13)]
        public string TaskID { get; set; }
        [StringLength(255)]
        public string TaskName { get; set; }
        [StringLength(255)]
        public string ExePath { get; set; }
        [StringLength(255)]
        public string Command { get; set; }
        public int? JobTime { get; set; }
        public int? DaysOfMonth { get; set; }
        public int? DaysOfWeek { get; set; }
        public int? Scheme { get; set; }
        public int? Distance0 { get; set; }
        public int? Distance1 { get; set; }
        public int? Distance2 { get; set; }
        [StringLength(10)]
        public string CreateDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastRunTime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NextRunTime { get; set; }
        [Column(TypeName = "text")]
        public string Stores { get; set; }
    }
}