// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Index(nameof(PurchaseID), Name = "DC00A")]
    [Index(nameof(PurchaseFactory), nameof(PurchaseID), Name = "DC00B")]
    [Index(nameof(DealFlag), nameof(PurchaseFactory), nameof(PurchaseDate), Name = "DC00C")]
    [Index(nameof(GoodID), Name = "GoodID")]
    [Index(nameof(SizeNo), Name = "KindID")]
    public partial class Purchase
    {
        [Key]
        [StringLength(20)]
        public string PurchaseID { get; set; }
        [StringLength(8)]
        public string PurchaseDate { get; set; }
        [StringLength(15)]
        public string PurchaseStore { get; set; }
        [StringLength(10)]
        public string PurchaseFactory { get; set; }
        [StringLength(20)]
        public string GoodID { get; set; }
        [StringLength(1)]
        public string SizeNo { get; set; }
        public double? PurchaseNum1 { get; set; }
        public double? PurchaseNum2 { get; set; }
        public double? PurchaseNum3 { get; set; }
        public double? PurchaseNum4 { get; set; }
        public double? PurchaseNum5 { get; set; }
        public double? PurchaseNum6 { get; set; }
        public double? PurchaseNum7 { get; set; }
        public double? PurchaseNum8 { get; set; }
        public double? PurchaseNum9 { get; set; }
        public double? PurchaseNum10 { get; set; }
        public double? PurchaseNum11 { get; set; }
        public double? PurchaseNum12 { get; set; }
        public double? PurchaseNum13 { get; set; }
        public double? PurchaseNum14 { get; set; }
        public double? PurchaseNum15 { get; set; }
        public double? PurchaseNum16 { get; set; }
        public double? PurchaseNum17 { get; set; }
        public double? TotalPurchaseNum { get; set; }
        public double? PurchasePrice { get; set; }
        public double? PurchaseAmount { get; set; }
        [StringLength(1)]
        public string PurchaseMode { get; set; }
        [StringLength(8)]
        public string PreDealDate { get; set; }
        [StringLength(1)]
        public string DealFlag { get; set; }
        [StringLength(100)]
        public string Remark { get; set; }
        [StringLength(4)]
        public string FillPerson { get; set; }
        [StringLength(1)]
        public string CancelFlag { get; set; }
        [StringLength(10)]
        public string Brand { get; set; }
        [StringLength(10)]
        public string Factory { get; set; }
        [StringLength(1)]
        public string DealMode { get; set; }
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [StringLength(4)]
        public string ChangePerson { get; set; }
        [Key]
        [StringLength(3)]
        public string Item { get; set; }
        [StringLength(4)]
        public string CurrencyID { get; set; }
        public double? CurrencyRate { get; set; }
        public double? Discount { get; set; }
        public double? TaxRate { get; set; }
        [StringLength(1)]
        public string TaxFlag { get; set; }
        [StringLength(4)]
        public string PurchasePerson01 { get; set; }
        [StringLength(4)]
        public string PurchasePerson02 { get; set; }
        [StringLength(1)]
        public string TaxMode { get; set; }
        public double? TaxPercent { get; set; }
        public double? Tax { get; set; }
        public double? AmountAfterTax { get; set; }
        public double? Non_Tax { get; set; }
        public double? AdvicePrice { get; set; }
        [StringLength(15)]
        public string PreStoreID { get; set; }
        [StringLength(1)]
        public string YuPeiHuoFlag { get; set; }
        [StringLength(1)]
        public string IsCheck { get; set; }
        [StringLength(8)]
        public string CheckDate { get; set; }
        [StringLength(100)]
        public string GoodName { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? NewTaxAmt { get; set; }
        public double? ForeignCost { get; set; }
        [StringLength(8)]
        public string FineDate { get; set; }
        [StringLength(200)]
        public string ClientGoodID { get; set; }
        [StringLength(20)]
        public string P_StyleC { get; set; }
        [StringLength(6)]
        public string Season { get; set; }
        [StringLength(200)]
        public string Remark01 { get; set; }
        [StringLength(200)]
        public string Remark02 { get; set; }
        [StringLength(200)]
        public string Remark03 { get; set; }
        [StringLength(200)]
        public string Remark04 { get; set; }
        [StringLength(200)]
        public string Remark05 { get; set; }
    }
}