// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    public partial class Receipts
    {
        [Key]
        [StringLength(13)]
        public string ReceiptsID { get; set; }
        [Key]
        [StringLength(3)]
        public string Item { get; set; }
        [StringLength(8)]
        public string ReceiptsDate { get; set; }
        [StringLength(15)]
        public string ReceiptsStore { get; set; }
        [StringLength(10)]
        public string ReceiptsFactory { get; set; }
        [StringLength(20)]
        public string GoodID { get; set; }
        [StringLength(1)]
        public string SizeNo { get; set; }
        public double? ReceiptsNum1 { get; set; }
        public double? ReceiptsNum2 { get; set; }
        public double? ReceiptsNum3 { get; set; }
        public double? ReceiptsNum4 { get; set; }
        public double? ReceiptsNum5 { get; set; }
        public double? ReceiptsNum6 { get; set; }
        public double? ReceiptsNum7 { get; set; }
        public double? ReceiptsNum8 { get; set; }
        public double? ReceiptsNum9 { get; set; }
        public double? ReceiptsNum10 { get; set; }
        public double? ReceiptsNum11 { get; set; }
        public double? ReceiptsNum12 { get; set; }
        public double? ReceiptsNum13 { get; set; }
        public double? ReceiptsNum14 { get; set; }
        public double? ReceiptsNum15 { get; set; }
        public double? ReceiptsNum16 { get; set; }
        public double? ReceiptsNum17 { get; set; }
        public double? TotalReceiptsNum { get; set; }
        public double? ReceiptsPrice { get; set; }
        public double? ReceiptsAmount { get; set; }
        [StringLength(1)]
        public string ReceiptsMode { get; set; }
        [StringLength(8)]
        public string PreDealDate { get; set; }
        [StringLength(1)]
        public string DealFlag { get; set; }
        [StringLength(100)]
        public string Remark { get; set; }
        [StringLength(4)]
        public string FillPerson { get; set; }
        [StringLength(1)]
        public string CancelFlag { get; set; }
        [StringLength(10)]
        public string Brand { get; set; }
        [StringLength(10)]
        public string Factory { get; set; }
        [StringLength(1)]
        public string DealMode { get; set; }
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [StringLength(4)]
        public string ChangePerson { get; set; }
        [StringLength(4)]
        public string CurrencyID { get; set; }
        public double? CurrencyRate { get; set; }
        public double? Discount { get; set; }
        public double? TaxRate { get; set; }
        [StringLength(1)]
        public string TaxFlag { get; set; }
        [StringLength(4)]
        public string ReceiptsPerson01 { get; set; }
        [StringLength(4)]
        public string ReceiptsPerson02 { get; set; }
        [StringLength(1)]
        public string TaxMode { get; set; }
        public double? TaxPercent { get; set; }
        public double? Tax { get; set; }
        public double? AmountAfterTax { get; set; }
        public double? Non_Tax { get; set; }
        public double? AdvicePrice { get; set; }
    }
}