// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Keyless]
    public partial class RequireRecord
    {
        [Required]
        [StringLength(15)]
        public string StoreId { get; set; }
        [Required]
        [StringLength(20)]
        public string GoodID { get; set; }
        [Required]
        [StringLength(1)]
        public string SizeNo { get; set; }
        public double RequireNum01 { get; set; }
        public double RequireNum02 { get; set; }
        public double RequireNum03 { get; set; }
        public double RequireNum04 { get; set; }
        public double RequireNum05 { get; set; }
        public double RequireNum06 { get; set; }
        public double RequireNum07 { get; set; }
        public double RequireNum08 { get; set; }
        public double RequireNum09 { get; set; }
        public double RequireNum10 { get; set; }
        public double RequireNum11 { get; set; }
        public double RequireNum12 { get; set; }
        public double RequireNum13 { get; set; }
        public double RequireNum14 { get; set; }
        public double RequireNum15 { get; set; }
        public double RequireNum16 { get; set; }
        public double RequireNum17 { get; set; }
        public double TotalRequireNum { get; set; }
        [Required]
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [Required]
        [StringLength(4)]
        public string ChangePerson { get; set; }
    }
}