// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    public partial class RptSet
    {
        [Key]
        [StringLength(200)]
        public string RptName { get; set; }
        [Key]
        [StringLength(200)]
        public string WorkStation { get; set; }
        [Key]
        [StringLength(200)]
        public string PrinterName { get; set; }
        public int PaperSize { get; set; }
        public int Orientation { get; set; }
        public int PaperWidth { get; set; }
        public int PaperHeight { get; set; }
        public int TopMargin { get; set; }
        public int BottomMargin { get; set; }
        public int LeftMargin { get; set; }
        public int RightMargin { get; set; }
        [Required]
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [Required]
        [StringLength(4)]
        public string ChangePerson { get; set; }
    }
}