// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Index(nameof(BranchID), Name = "BranchID")]
    [Index(nameof(GiftType), Name = "CardID")]
    [Index(nameof(InvoiceID), Name = "DFC0A")]
    [Index(nameof(SellID), Name = "DFC0B")]
    [Index(nameof(SellID), Name = "Idx_DeviceInfo_SellInvoice_SellID")]
    [Index(nameof(UniteID), Name = "UniteID")]
    public partial class SellInvoice
    {
        [Key]
        [StringLength(10)]
        public string InvoiceID { get; set; }
        [Key]
        [StringLength(13)]
        public string SellID { get; set; }
        [StringLength(1)]
        public string InvoiceKind { get; set; }
        [StringLength(15)]
        public string UniteID { get; set; }
        [StringLength(3)]
        public string CardType { get; set; }
        [StringLength(3)]
        public string GiftType { get; set; }
        [StringLength(5)]
        public string InvoiceTime { get; set; }
        public double? Cash { get; set; }
        public double? CardAmount { get; set; }
        public double? GiftAmount { get; set; }
        [StringLength(15)]
        public string InvoiceBranch { get; set; }
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [StringLength(4)]
        public string ChangePerson { get; set; }
        [StringLength(8)]
        public string InvoiceDate { get; set; }
        [StringLength(1)]
        public string CancelFlag { get; set; }
        [StringLength(15)]
        public string BranchID { get; set; }
        [Key]
        [StringLength(3)]
        public string UniqueID { get; set; }
        [StringLength(16)]
        public string CreditID { get; set; }
        [StringLength(200)]
        public string Remark { get; set; }
        [StringLength(1)]
        public string Mode { get; set; }
        [StringLength(200)]
        public string Buyer { get; set; }
        [StringLength(1)]
        public string InvoiceSort { get; set; }
    }
}