// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    public partial class SellVisitorNum
    {
        [Key]
        [StringLength(20)]
        public string SerialID { get; set; }
        [Required]
        [StringLength(8)]
        public string SellDate { get; set; }
        [Required]
        [StringLength(15)]
        public string StoreID { get; set; }
        public double Num { get; set; }
        [Required]
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [Required]
        [StringLength(4)]
        public string ChangePerson { get; set; }
    }
}