// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Index(nameof(SellID), Name = "DF00A")]
    [Index(nameof(GoodID), Name = "GoodID")]
    [Index(nameof(ID), Name = "ID")]
    [Index(nameof(SizeNo), Name = "IX_Sell")]
    [Index(nameof(PurchaseID), Name = "PurchaseID")]
    [Index(nameof(SellBranch), Name = "SellBranch")]
    [Index(nameof(SellDate), Name = "SellDate")]
    [Index(nameof(SellPerson), Name = "SellPerson")]
    [Index(nameof(SellStore), Name = "SellStore")]
    public partial class Sell
    {
        [Key]
        [StringLength(20)]
        public string SellID { get; set; }
        [StringLength(8)]
        public string SellDate { get; set; }
        [StringLength(15)]
        public string SellBranch { get; set; }
        [StringLength(15)]
        public string SellStore { get; set; }
        [Required]
        [StringLength(4)]
        public string SellPerson { get; set; }
        [StringLength(20)]
        public string GoodID { get; set; }
        [StringLength(1)]
        public string SizeNo { get; set; }
        [StringLength(4)]
        public string SizeName { get; set; }
        public short? SizePosition { get; set; }
        public double? SellNum1 { get; set; }
        public int? SellNum2 { get; set; }
        public int? SellNum3 { get; set; }
        public int? SellNum4 { get; set; }
        public int? SellNum5 { get; set; }
        public int? SellNum6 { get; set; }
        public int? SellNum7 { get; set; }
        public int? SellNum8 { get; set; }
        public int? SellNum9 { get; set; }
        public int? SellNum10 { get; set; }
        public int? SellNum11 { get; set; }
        public int? SellNum12 { get; set; }
        public int? SellNum13 { get; set; }
        public int? SellNum14 { get; set; }
        public int? SellNum15 { get; set; }
        public int? SellNum16 { get; set; }
        public int? SellNum17 { get; set; }
        public double? TotalSellNum { get; set; }
        public double? SellPrice { get; set; }
        public double? SellDiscount { get; set; }
        [StringLength(20)]
        public string MemberID { get; set; }
        [StringLength(40)]
        public string MemberName { get; set; }
        public double? SellCash { get; set; }
        public double? SellCardAmount { get; set; }
        public double? SellGiftAmount { get; set; }
        [StringLength(1)]
        public string SellMode { get; set; }
        public double? SellCost { get; set; }
        [StringLength(10)]
        public string Factory { get; set; }
        [StringLength(10)]
        public string Brand { get; set; }
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [StringLength(3)]
        public string ID { get; set; }
        [Key]
        [StringLength(3)]
        public string Item { get; set; }
        [StringLength(4)]
        public string FillPerson { get; set; }
        [StringLength(4)]
        public string ChangePerson { get; set; }
        [StringLength(50)]
        public string CloseAccount { get; set; }
        public double? Bonus { get; set; }
        [StringLength(20)]
        public string PurchaseID { get; set; }
        [StringLength(3)]
        public string PurchaseItem { get; set; }
        public double? Non_Tax { get; set; }
        public double? Tax { get; set; }
        [StringLength(20)]
        public string SM_GiftNo { get; set; }
        public double? ChouChengDiscount { get; set; }
        [StringLength(1)]
        public string Gender { get; set; }
        [StringLength(8)]
        public string Age { get; set; }
        [StringLength(20)]
        public string ZuHeID { get; set; }
        [StringLength(10)]
        public string ZuHeTypeName { get; set; }
        public double? HongLi { get; set; }
        [StringLength(50)]
        public string ZHBatchID { get; set; }
        [StringLength(100)]
        public string GoodName { get; set; }
        [StringLength(100)]
        public string Remark { get; set; }
        public double? HongLiTimes { get; set; }
        public double? ShouldSellPrice { get; set; }
        [StringLength(1)]
        public string CalcuMember { get; set; }
        [StringLength(8)]
        public string PreDate { get; set; }
        [StringLength(1)]
        public string Sex { get; set; }
        [StringLength(20)]
        public string Major { get; set; }
        [StringLength(15)]
        public string BSellInvoice { get; set; }
        [StringLength(3)]
        public string ZHBatchItem { get; set; }
        [StringLength(1)]
        public string HongLiMode { get; set; }
        [StringLength(20)]
        public string SellReturnsID { get; set; }
        [StringLength(1)]
        public string AloneFlag { get; set; }
        [StringLength(1)]
        public string A4PriceSort { get; set; }
        public double? T4Discount { get; set; }
        [StringLength(1)]
        public string T5chkComply { get; set; }
        [StringLength(4)]
        public string SM_TypeID { get; set; }
        public double? S_Value { get; set; }
        public double? S_SellPrice { get; set; }
        [StringLength(1)]
        public string ShipMode { get; set; }
        [StringLength(2000)]
        public string GSortGroup { get; set; }
        [StringLength(1)]
        public string birthdayMember { get; set; }
        [StringLength(100)]
        public string RemarkDet { get; set; }
        public double? CNY { get; set; }
        public double? JPY { get; set; }
        public double? KRW { get; set; }
        public double? USD { get; set; }
        public double? CNYAmt { get; set; }
        public double? JPYAmt { get; set; }
        public double? KRWAmt { get; set; }
        public double? USDAmt { get; set; }
        public double? Non_TaxA { get; set; }
        public double? NTCashAmt { get; set; }
        public double? NTCardAmt { get; set; }
        [StringLength(20)]
        public string BackSellID { get; set; }
        [StringLength(20)]
        public string BackSellItem { get; set; }
        [StringLength(20)]
        public string BackEInvID { get; set; }
        public int? GetPoint { get; set; }
        [StringLength(1)]
        public string BrithMode { get; set; }
        [StringLength(1)]
        public string BirthMode { get; set; }
        [StringLength(1)]
        public string InvoiceKind { get; set; }
        [StringLength(100)]
        public string ProductSerialID { get; set; }
        [StringLength(8)]
        public string OrderID { get; set; }
        [StringLength(1)]
        public string IsCalFlag { get; set; }
        public double? AdvicePrice { get; set; }
        [StringLength(100)]
        public string Color { get; set; }
        [StringLength(200)]
        public string RegistrationCode { get; set; }
        [StringLength(20)]
        public string GspecialID { get; set; }
    }
}