// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    public partial class Sellding
    {
        [Key]
        [StringLength(20)]
        public string SellID { get; set; }
        [Key]
        [StringLength(3)]
        public string SellItem { get; set; }
        [StringLength(200)]
        public string MemberName { get; set; }
        [StringLength(20)]
        public string TEL { get; set; }
        [StringLength(100)]
        public string Addr { get; set; }
        [StringLength(20)]
        public string GoodID { get; set; }
        [StringLength(3)]
        public string SizeNo { get; set; }
        [StringLength(6)]
        public string SizeName { get; set; }
        public short? SizePosition { get; set; }
        public double? Num { get; set; }
        [StringLength(8)]
        public string SellBranch { get; set; }
        [StringLength(8)]
        public string SellDate { get; set; }
        [StringLength(8)]
        public string FillPerson { get; set; }
        [StringLength(200)]
        public string Remark { get; set; }
        [StringLength(1)]
        public string Flag { get; set; }
        [StringLength(4)]
        public string CheckFlag { get; set; }
        [StringLength(4)]
        public string DoFlag { get; set; }
        [StringLength(4)]
        public string TranFlag { get; set; }
        [StringLength(20)]
        public string TransferID { get; set; }
        [StringLength(3)]
        public string TransferItem { get; set; }
        [StringLength(8)]
        public string TranStore { get; set; }
        [StringLength(8)]
        public string deliverDate { get; set; }
        [StringLength(8)]
        public string deliverTime { get; set; }
        [StringLength(8)]
        public string ChangePerson { get; set; }
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [StringLength(20)]
        public string WayID { get; set; }
        [StringLength(1)]
        public string WebFlag { get; set; }
        [StringLength(1)]
        public string ODFlag { get; set; }
    }
}