// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Keyless]
    public partial class SellDingTran
    {
        [Required]
        [StringLength(20)]
        public string SerialID { get; set; }
        [StringLength(20)]
        public string SellID { get; set; }
        [StringLength(200)]
        public string TransactionID { get; set; }
        [StringLength(200)]
        public string PlatformName { get; set; }
        [StringLength(8)]
        public string OldStore { get; set; }
        [StringLength(8)]
        public string NewStore { get; set; }
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [StringLength(8)]
        public string ChangePerson { get; set; }
    }
}