// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Keyless]
    public partial class SellChange
    {
        [Required]
        [StringLength(20)]
        public string SellID { get; set; }
        [Required]
        [StringLength(20)]
        public string OldSellStore { get; set; }
        [Required]
        [StringLength(20)]
        public string OldSellPerson { get; set; }
        [Required]
        [StringLength(20)]
        public string OldMemberID { get; set; }
        [Required]
        [StringLength(800)]
        public string OldRemark { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime ChangeDateTime { get; set; }
        [Required]
        [StringLength(20)]
        public string ChangePerson { get; set; }
        [StringLength(3)]
        public string Item { get; set; }
    }
}