// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Keyless]
    public partial class SellYahoo
    {
        [Required]
        [StringLength(20)]
        public string SellID { get; set; }
        [Required]
        [StringLength(20)]
        public string TradeID { get; set; }
        [Required]
        [StringLength(20)]
        public string ReceivePerson { get; set; }
        [Required]
        [StringLength(20)]
        public string ReceiveMobil { get; set; }
        [Required]
        [StringLength(100)]
        public string ReceiveAddr { get; set; }
        [Required]
        [StringLength(20)]
        public string ReceiveTel1 { get; set; }
        [Required]
        [StringLength(20)]
        public string ReceiveTel2 { get; set; }
        [StringLength(100)]
        public string YaEDate { get; set; }
        [StringLength(100)]
        public string WayID { get; set; }
        [StringLength(100)]
        public string YaSID { get; set; }
        [StringLength(100)]
        public string YaDID { get; set; }
        public double? WayMoney { get; set; }
        [StringLength(10)]
        public string ZipID { get; set; }
        [StringLength(100)]
        public string PlatformID { get; set; }
        [StringLength(100)]
        public string SellMode { get; set; }
        [StringLength(100)]
        public string WayKind { get; set; }
        [StringLength(200)]
        public string Remark { get; set; }
    }
}