// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Keyless]
    public partial class SellNoSaveTmp
    {
        public int? NoSaveID { get; set; }
        [StringLength(3)]
        public string Item { get; set; }
        [StringLength(8)]
        public string SaveDate { get; set; }
        [StringLength(40)]
        public string SaveTime { get; set; }
        [StringLength(15)]
        public string SellStore { get; set; }
        [StringLength(4)]
        public string SellPerson { get; set; }
        [StringLength(20)]
        public string GoodID { get; set; }
        [StringLength(1)]
        public string SizeNo { get; set; }
        [StringLength(4)]
        public string SizeName { get; set; }
        public short? SizePosition { get; set; }
        public int? SellNum1 { get; set; }
        public int? SellNum2 { get; set; }
        public int? SellNum3 { get; set; }
        public int? SellNum4 { get; set; }
        public int? SellNum5 { get; set; }
        public int? SellNum6 { get; set; }
        public int? SellNum7 { get; set; }
        public int? SellNum8 { get; set; }
        public int? SellNum9 { get; set; }
        public int? SellNum10 { get; set; }
        public int? SellNum11 { get; set; }
        public int? SellNum12 { get; set; }
        public int? SellNum13 { get; set; }
        public int? SellNum14 { get; set; }
        public int? SellNum15 { get; set; }
        public int? SellNum16 { get; set; }
        public int? SellNum17 { get; set; }
        public int? TotalSellNum { get; set; }
        public double? SellPrice { get; set; }
        public double? SellDiscount { get; set; }
        [StringLength(20)]
        public string MemberID { get; set; }
        [StringLength(40)]
        public string MemberName { get; set; }
        [StringLength(1)]
        public string SellMode { get; set; }
        public double? SellCost { get; set; }
        public double? SellCash { get; set; }
        [StringLength(20)]
        public string PurchaseID { get; set; }
        [StringLength(3)]
        public string PurchaseItem { get; set; }
        [StringLength(3)]
        public string CardType { get; set; }
        [StringLength(3)]
        public string GiftType { get; set; }
        [StringLength(16)]
        public string CreditID { get; set; }
        [StringLength(20)]
        public string ZuHeID { get; set; }
        [StringLength(10)]
        public string ZuHeTypeName { get; set; }
        public double? HongLi { get; set; }
        [StringLength(50)]
        public string ZHBatchID { get; set; }
        [StringLength(100)]
        public string GoodName { get; set; }
        [StringLength(100)]
        public string Remark { get; set; }
        public double? ShouldSellPrice { get; set; }
        [StringLength(1)]
        public string Sex { get; set; }
        [StringLength(20)]
        public string Age { get; set; }
        [StringLength(20)]
        public string Major { get; set; }
        [StringLength(20)]
        public string SM_GiftNo { get; set; }
        [StringLength(4)]
        public string SM_TypeID { get; set; }
        public double? S_Value { get; set; }
        public double? S_SellPrice { get; set; }
        [StringLength(1)]
        public string InvoiceKind { get; set; }
        [StringLength(20)]
        public string GspecialID { get; set; }
    }
}