// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    public partial class SellClosing
    {
        [Key]
        [StringLength(20)]
        public string SellID { get; set; }
        [Key]
        public int Item { get; set; }
        public int ClosingID { get; set; }
        [Required]
        [StringLength(20)]
        public string ClosingName { get; set; }
        [Required]
        [StringLength(20)]
        public string ClosingType { get; set; }
        public double Amount { get; set; }
        [Required]
        [StringLength(20)]
        public string CNo { get; set; }
        [Required]
        [StringLength(100)]
        public string CName { get; set; }
        [Required]
        [StringLength(100)]
        public string AccountNo { get; set; }
        public double Period { get; set; }
        public double Interest { get; set; }
        [Required]
        [StringLength(1)]
        public string WhoPayInterest { get; set; }
        public double LiXi { get; set; }
        [Required]
        [StringLength(100)]
        public string Remark { get; set; }
        [Required]
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [Required]
        [StringLength(4)]
        public string ChangePerson { get; set; }
    }
}