// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Index(nameof(CustID), Name = "CustID")]
    [Index(nameof(GoodID), Name = "GoodID")]
    public partial class ShipDetail
    {
        [Key]
        [StringLength(20)]
        public string ShipID { get; set; }
        [StringLength(1)]
        public string ShipMode { get; set; }
        [StringLength(8)]
        public string ShipDate { get; set; }
        [StringLength(15)]
        public string CustID { get; set; }
        [StringLength(15)]
        public string ShipStore { get; set; }
        [StringLength(6)]
        public string CloseMonth { get; set; }
        [StringLength(1)]
        public string DealMode { get; set; }
        [StringLength(4)]
        public string FillPerson { get; set; }
        [StringLength(20)]
        public string GoodID { get; set; }
        [StringLength(1)]
        public string SizeNo { get; set; }
        public double? ShipNum1 { get; set; }
        public double? ShipNum2 { get; set; }
        public double? ShipNum3 { get; set; }
        public double? ShipNum4 { get; set; }
        public double? ShipNum5 { get; set; }
        public double? ShipNum6 { get; set; }
        public double? ShipNum7 { get; set; }
        public double? ShipNum8 { get; set; }
        public double? ShipNum9 { get; set; }
        public double? ShipNum10 { get; set; }
        public double? ShipNum11 { get; set; }
        public double? ShipNum12 { get; set; }
        public double? ShipNum13 { get; set; }
        public double? ShipNum14 { get; set; }
        public double? ShipNum15 { get; set; }
        public double? ShipNum16 { get; set; }
        public double? ShipNum17 { get; set; }
        public int? TotalShipNum { get; set; }
        public double? SellPrice { get; set; }
        public double? ShipDiscount { get; set; }
        public double? ShipPrice { get; set; }
        public double? ShipAmount { get; set; }
        [StringLength(1)]
        public string OrderMode { get; set; }
        [StringLength(10)]
        public string Brand { get; set; }
        [StringLength(10)]
        public string Factory { get; set; }
        [StringLength(4)]
        public string Operation { get; set; }
        public double? ShipCost { get; set; }
        [Key]
        [StringLength(3)]
        public string Item { get; set; }
        [StringLength(20)]
        public string OrderID { get; set; }
        [StringLength(3)]
        public string OrderItem { get; set; }
        public double? Non_Tax { get; set; }
        public double? Tax { get; set; }
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [StringLength(4)]
        public string ChangePerson { get; set; }
        [StringLength(200)]
        public string ClientGoodID { get; set; }
        [StringLength(8)]
        public string DealModeID { get; set; }
        [StringLength(100)]
        public string MemoStr { get; set; }
        [StringLength(100)]
        public string GoodName { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? NewTaxAmt { get; set; }
        [StringLength(1)]
        public string Type { get; set; }
        [StringLength(20)]
        public string P_StyleC { get; set; }
        [StringLength(200)]
        public string Remark1 { get; set; }
        [StringLength(20)]
        public string AutoShipID { get; set; }
        [StringLength(5)]
        public string AutoShipItem { get; set; }
        [StringLength(20)]
        public string AutoBackID { get; set; }
        [StringLength(5)]
        public string AutoBackItem { get; set; }
        [StringLength(20)]
        public string AutoBatchID { get; set; }
        [StringLength(5)]
        public string AutoBatchItem { get; set; }
        [StringLength(1)]
        public string InMode { get; set; }
        public double? ForeignCost { get; set; }
        [StringLength(200)]
        public string Remarknew { get; set; }
        public double? ForeignPrice { get; set; }
    }
}