// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    public partial class Shop
    {
        [Key]
        [Column("Shop")]
        [StringLength(15)]
        public string Shop1 { get; set; }
        [StringLength(60)]
        public string ShopName { get; set; }
        [Key]
        [StringLength(8)]
        public string StartDay { get; set; }
        [Key]
        [StringLength(8)]
        public string EndDay { get; set; }
        [Column("100Discount")]
        public float? _100Discount { get; set; }
        [Column("90Discount")]
        public float? _90Discount { get; set; }
        [Column("80Discount")]
        public float? _80Discount { get; set; }
        [Column("76Discount")]
        public float? _76Discount { get; set; }
        [Column("70Discount")]
        public float? _70Discount { get; set; }
        [Column("60Discount")]
        public float? _60Discount { get; set; }
        [Column("50Discount")]
        public float? _50Discount { get; set; }
        [Column("40Discount")]
        public float? _40Discount { get; set; }
        [Column("30Discount")]
        public float? _30Discount { get; set; }
        [Column("20Discount")]
        public float? _20Discount { get; set; }
        [Column("10Discount")]
        public float? _10Discount { get; set; }
        public float? Sale { get; set; }
        public float? Card { get; set; }
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [StringLength(4)]
        public string ChangePerson { get; set; }
        [Key]
        [StringLength(10)]
        public string Brand { get; set; }
    }
}