// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    public partial class ShopDiscount
    {
        [Key]
        [StringLength(13)]
        public string SerialID { get; set; }
        [Required]
        [StringLength(8)]
        public string BranchID { get; set; }
        [Required]
        [StringLength(8)]
        public string BranchMonth { get; set; }
        public double? Discount1 { get; set; }
        public double? Discount2 { get; set; }
        public double? Discount3 { get; set; }
        public double? Discount4 { get; set; }
        public double? Discount5 { get; set; }
        public double? Discount6 { get; set; }
        public double? Discount7 { get; set; }
        public double? Discount8 { get; set; }
        public double? Discount9 { get; set; }
        public double? Discount10 { get; set; }
        public double? Discount11 { get; set; }
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [StringLength(8)]
        public string ChangePerson { get; set; }
    }
}