// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    public partial class SiteCollectionList
    {
        [Key]
        public int CompanyID { get; set; }
        [Key]
        [StringLength(200)]
        public string CollectionID { get; set; }
        [StringLength(50)]
        public string Name { get; set; }
        public bool? Actived { get; set; }
        public int? OrderBy { get; set; }
        public int? Carriage1 { get; set; }
        public int? Carriage2 { get; set; }
        public short? StatusShip { get; set; }
        public short? StatusToDC { get; set; }
        public short? StatusToShop { get; set; }
        public short? StatusToClient { get; set; }
        public short? StatusApply { get; set; }
        public short? StatusReturning { get; set; }
        public short? StatusReturn { get; set; }
        public int? DeliveryCharge1 { get; set; }
        public int? DeliveryCharge2 { get; set; }
        [StringLength(50)]
        public string CompanyName { get; set; }
    }
}