// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    public partial class Size
    {
        [Key]
        [StringLength(1)]
        public string SizeNo { get; set; }
        [StringLength(4)]
        public string Size01 { get; set; }
        [StringLength(4)]
        public string Size02 { get; set; }
        [StringLength(4)]
        public string Size03 { get; set; }
        [StringLength(4)]
        public string Size04 { get; set; }
        [StringLength(4)]
        public string Size05 { get; set; }
        [StringLength(4)]
        public string Size06 { get; set; }
        [StringLength(4)]
        public string Size07 { get; set; }
        [StringLength(4)]
        public string Size08 { get; set; }
        [StringLength(4)]
        public string Size09 { get; set; }
        [StringLength(4)]
        public string Size10 { get; set; }
        [StringLength(4)]
        public string Size11 { get; set; }
        [StringLength(4)]
        public string Size12 { get; set; }
        [StringLength(4)]
        public string Size13 { get; set; }
        [StringLength(4)]
        public string Size14 { get; set; }
        [StringLength(4)]
        public string Size15 { get; set; }
        [StringLength(4)]
        public string Size16 { get; set; }
        [StringLength(4)]
        public string Size17 { get; set; }
        [StringLength(100)]
        public string Remark { get; set; }
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [StringLength(4)]
        public string ChangePerson { get; set; }
    }
}