// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Keyless]
    public partial class SmartClientState
    {
        [StringLength(1)]
        public string PreRunMode { get; set; }
        [StringLength(8)]
        public string R_TO_L_LastDate { get; set; }
        [StringLength(2)]
        public string LocalTimes { get; set; }
    }
}