// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    public partial class SMSgoMemDet
    {
        [Key]
        [StringLength(20)]
        public string SMSgoID { get; set; }
        [Key]
        [StringLength(20)]
        public string MemberID { get; set; }
        [Required]
        [StringLength(20)]
        public string Mobil { get; set; }
        [Required]
        [StringLength(200)]
        public string msg { get; set; }
        [Required]
        [StringLength(1)]
        public string Flag { get; set; }
        [Required]
        [StringLength(8)]
        public string SendDate { get; set; }
        [Required]
        [StringLength(5)]
        public string SendTime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreateDate { get; set; }
    }
}