// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    public partial class stClockOnOff
    {
        [Key]
        [StringLength(8)]
        public string ClientID { get; set; }
        [Key]
        public int WeekN { get; set; }
        [StringLength(5)]
        public string StOn { get; set; }
        [StringLength(8)]
        public string StOff { get; set; }
    }
}