// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Keyless]
    [Index(nameof(Brand), nameof(CheckDate), nameof(CheckStore), nameof(GoodID), nameof(SizeNo), Name = "_412")]
    public partial class StgCheckDetail
    {
        [Required]
        [StringLength(13)]
        public string CheckID { get; set; }
        [Required]
        [StringLength(3)]
        public string Item { get; set; }
        [StringLength(8)]
        public string CheckDate { get; set; }
        [StringLength(15)]
        public string CheckStore { get; set; }
        [StringLength(20)]
        public string GoodID { get; set; }
        [StringLength(1)]
        public string SizeNo { get; set; }
        public int? CheckNum1 { get; set; }
        public int? CheckNum2 { get; set; }
        public int? CheckNum3 { get; set; }
        public int? CheckNum4 { get; set; }
        public int? CheckNum5 { get; set; }
        public int? CheckNum6 { get; set; }
        public int? CheckNum7 { get; set; }
        public int? CheckNum8 { get; set; }
        public int? CheckNum9 { get; set; }
        public int? CheckNum10 { get; set; }
        public int? CheckNum11 { get; set; }
        public int? CheckNum12 { get; set; }
        public int? CheckNum13 { get; set; }
        public int? CheckNum14 { get; set; }
        public int? CheckNum15 { get; set; }
        public int? CheckNum16 { get; set; }
        public int? CheckNum17 { get; set; }
        public int? TotalCheckNum { get; set; }
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [StringLength(10)]
        public string Brand { get; set; }
        [StringLength(10)]
        public string Factory { get; set; }
        [StringLength(4)]
        public string FillPerson { get; set; }
        [StringLength(4)]
        public string ChangePerson { get; set; }
        [StringLength(100)]
        public string remark { get; set; }
        [StringLength(1)]
        public string CheckFlag { get; set; }
    }
}