// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Index(nameof(Brand), nameof(CheckDate), nameof(CheckStore), nameof(GoodID), nameof(SizeNo), Name = "_412")]
    public partial class StgCheck
    {
        [Key]
        [StringLength(8)]
        public string CheckDate { get; set; }
        [Key]
        [StringLength(15)]
        public string CheckStore { get; set; }
        [Key]
        [StringLength(20)]
        public string GoodID { get; set; }
        [Key]
        [StringLength(1)]
        public string SizeNo { get; set; }
        public int? CheckNum1 { get; set; }
        public int? CheckNum2 { get; set; }
        public int? CheckNum3 { get; set; }
        public int? CheckNum4 { get; set; }
        public int? CheckNum5 { get; set; }
        public int? CheckNum6 { get; set; }
        public int? CheckNum7 { get; set; }
        public int? CheckNum8 { get; set; }
        public int? CheckNum9 { get; set; }
        public int? CheckNum10 { get; set; }
        public int? CheckNum11 { get; set; }
        public int? CheckNum12 { get; set; }
        public int? CheckNum13 { get; set; }
        public int? CheckNum14 { get; set; }
        public int? CheckNum15 { get; set; }
        public int? CheckNum16 { get; set; }
        public int? CheckNum17 { get; set; }
        public int? TotalCheckNum { get; set; }
        public int? OldNum1 { get; set; }
        public int? OldNum2 { get; set; }
        public int? OldNum3 { get; set; }
        public int? OldNum4 { get; set; }
        public int? OldNum5 { get; set; }
        public int? OldNum6 { get; set; }
        public int? OldNum7 { get; set; }
        public int? OldNum8 { get; set; }
        public int? OldNum9 { get; set; }
        public int? OldNum10 { get; set; }
        public int? OldNum11 { get; set; }
        public int? OldNum12 { get; set; }
        public int? OldNum13 { get; set; }
        public int? OldNum14 { get; set; }
        public int? OldNum15 { get; set; }
        public int? OldNum16 { get; set; }
        public int? OldNum17 { get; set; }
        public int? TotalOldNum { get; set; }
        [StringLength(1)]
        public string CheckFlag { get; set; }
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [StringLength(10)]
        public string Brand { get; set; }
        [StringLength(10)]
        public string Factory { get; set; }
        [StringLength(4)]
        public string FillPerson { get; set; }
        [StringLength(4)]
        public string ChangePerson { get; set; }
        [StringLength(80)]
        public string GoodName { get; set; }
    }
}