// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Index(nameof(StockMode), Name = "ChangID")]
    [Index(nameof(CloseMonth), nameof(StockDate), Name = "DDA0B")]
    [Index(nameof(FactoryID), Name = "FactorBillID")]
    [Index(nameof(InvoiceID), Name = "InvoiceID")]
    public partial class Stock
    {
        [Key]
        [StringLength(20)]
        public string StockID { get; set; }
        [StringLength(20)]
        public string FactoryID { get; set; }
        [StringLength(8)]
        public string StockDate { get; set; }
        [StringLength(10)]
        public string StockFactory { get; set; }
        [StringLength(6)]
        public string CloseMonth { get; set; }
        [StringLength(1)]
        public string StockMode { get; set; }
        [StringLength(15)]
        public string StockStore { get; set; }
        [StringLength(1)]
        public string DealMode { get; set; }
        public double? ShouldAmount { get; set; }
        public double? TaxPercent { get; set; }
        public double? Tax { get; set; }
        public double? DiscountPercent { get; set; }
        public double? Discount { get; set; }
        public double? DiscountAmount { get; set; }
        public double? OtherAmount { get; set; }
        public double? ChargeAmount { get; set; }
        [StringLength(1)]
        public string ChargeMode { get; set; }
        [StringLength(10)]
        public string Brand { get; set; }
        [StringLength(10)]
        public string Factory { get; set; }
        [StringLength(4)]
        public string Operation { get; set; }
        public int? Variable { get; set; }
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [StringLength(4)]
        public string ChangePerson { get; set; }
        [StringLength(1)]
        public string CloseAccount { get; set; }
        public double? InvoiceAmount { get; set; }
        [StringLength(8)]
        public string InvoiceDate { get; set; }
        [StringLength(10)]
        public string InvoiceID { get; set; }
        public double? PaymentAmount { get; set; }
        [StringLength(100)]
        public string Remark { get; set; }
        [StringLength(1)]
        public string TaxMode { get; set; }
        [StringLength(50)]
        public string StockNote { get; set; }
        [StringLength(1)]
        public string IsCheck { get; set; }
        [StringLength(8)]
        public string CheckDate { get; set; }
        [StringLength(50)]
        public string ChangePriceID { get; set; }
        [StringLength(13)]
        public string ClientChangePriceid { get; set; }
        public double? RealTotalAmount { get; set; }
        public double? PerAvgFee { get; set; }
        [StringLength(8)]
        public string BLDate { get; set; }
        [StringLength(4)]
        public string CurrencyID { get; set; }
        public double? CurrencyRate { get; set; }
        public double? Cost0 { get; set; }
        public double? Cost1 { get; set; }
        public double? Cost2 { get; set; }
        public double? Cost3 { get; set; }
        public double? Cost4 { get; set; }
        public double? Cost5 { get; set; }
        [StringLength(20)]
        public string AutoShipID { get; set; }
        [StringLength(20)]
        public string AutoBackID { get; set; }
        [StringLength(20)]
        public string AutoBatchID { get; set; }
        [StringLength(13)]
        public string CheckID { get; set; }
        [StringLength(10)]
        public string DeptID { get; set; }
        [StringLength(1)]
        public string SortMode { get; set; }
    }
}