// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Keyless]
    public partial class TBCalculate
    {
        [Required]
        [StringLength(1)]
        public string Calculate { get; set; }
    }
}