// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    public partial class TdSalePlanD
    {
        [Key]
        public Guid PlanID { get; set; }
        [Key]
        public int Item { get; set; }
        public int SortID { get; set; }
        [Required]
        [StringLength(50)]
        public string SubjectCode { get; set; }
        [Required]
        [StringLength(50)]
        public string SubjectName { get; set; }
        [Column(TypeName = "decimal(18, 6)")]
        public decimal Qty { get; set; }
        [Column(TypeName = "decimal(18, 6)")]
        public decimal Amt { get; set; }
        [Column(TypeName = "decimal(18, 6)")]
        public decimal Profit { get; set; }
        [Column(TypeName = "decimal(18, 6)")]
        public decimal StockQty { get; set; }
        [Column(TypeName = "decimal(18, 6)")]
        public decimal StockCost { get; set; }
        [Required]
        [StringLength(500)]
        public string Remark { get; set; }
    }
}