// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    public partial class TdSalePlan
    {
        [Key]
        public Guid PlanID { get; set; }
        [Required]
        [StringLength(50)]
        public string PlanCode { get; set; }
        public int SubjectType { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime PlanBeginDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime PlanEndDate { get; set; }
        [Required]
        public bool? IsPlanQty { get; set; }
        [Required]
        public bool? IsPlanAmt { get; set; }
        [Required]
        public bool? IsPlanProfit { get; set; }
        [Required]
        public bool? IsPlanStockQty { get; set; }
        [Required]
        public bool? IsPlanStockCost { get; set; }
        [Required]
        [StringLength(500)]
        public string Summary { get; set; }
    }
}