// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    public partial class TransConfig
    {
        [Key]
        [StringLength(15)]
        public string BranchID { get; set; }
        [Key]
        [StringLength(100)]
        public string TableName { get; set; }
        [Required]
        [StringLength(100)]
        public string TableRemark { get; set; }
        public byte Insert_Flag { get; set; }
        public byte Replace_Flag { get; set; }
        public byte Del_Flag { get; set; }
        public byte Stock_Flag { get; set; }
    }
}