// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Keyless]
    [Index(nameof(Bar), Name = "IX_TransToShip")]
    [Index(nameof(StoreID), Name = "IX_TransToShip_1")]
    [Index(nameof(UserID), Name = "IX_TransToShip_2")]
    public partial class TransToShip
    {
        [StringLength(50)]
        public string Bar { get; set; }
        [StringLength(15)]
        public string StoreID { get; set; }
        [StringLength(15)]
        public string CkStNo { get; set; }
        [StringLength(20)]
        public string GoodID { get; set; }
        [StringLength(1)]
        public string SizeNo { get; set; }
        [StringLength(2)]
        public string Position { get; set; }
        public double? Qty { get; set; }
        [StringLength(4)]
        public string UserID { get; set; }
        [StringLength(1)]
        public string KD { get; set; }
    }
}