// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Index(nameof(TransferID), Name = "DE00A")]
    [Index(nameof(FillPerson), nameof(GoodID), nameof(TranDate), Name = "DE00B")]
    [Index(nameof(TranNum2), nameof(TranInStore), nameof(TranDate), Name = "DE00C")]
    public partial class Transfer
    {
        [Key]
        [StringLength(20)]
        public string TransferID { get; set; }
        [StringLength(15)]
        public string TranOutStore { get; set; }
        [StringLength(8)]
        public string TranDate { get; set; }
        [StringLength(15)]
        public string TranInStore { get; set; }
        [StringLength(4)]
        public string FillPerson { get; set; }
        [StringLength(20)]
        public string GoodID { get; set; }
        [StringLength(1)]
        public string SizeNo { get; set; }
        public double? TranNum1 { get; set; }
        public double? TranNum2 { get; set; }
        public double? TranNum3 { get; set; }
        public double? TranNum4 { get; set; }
        public double? TranNum5 { get; set; }
        public double? TranNum6 { get; set; }
        public double? TranNum7 { get; set; }
        public double? TranNum8 { get; set; }
        public double? TranNum9 { get; set; }
        public double? TranNum10 { get; set; }
        public double? TranNum11 { get; set; }
        public double? TranNum12 { get; set; }
        public double? TranNum13 { get; set; }
        public double? TranNum14 { get; set; }
        public double? TranNum15 { get; set; }
        public double? TranNum16 { get; set; }
        public double? TranNum17 { get; set; }
        public double? TotalTranNum { get; set; }
        public double? TranPrice { get; set; }
        public double? TranAmount { get; set; }
        public double? TranTotalAmount { get; set; }
        [StringLength(100)]
        public string Remark { get; set; }
        [StringLength(10)]
        public string Brand { get; set; }
        [StringLength(10)]
        public string Factory { get; set; }
        [StringLength(8)]
        public string ChangeDate { get; set; }
        public double? TranCost { get; set; }
        [StringLength(4)]
        public string ChangePerson { get; set; }
        [Key]
        [StringLength(3)]
        public string Item { get; set; }
        [StringLength(1)]
        public string RecordFlag { get; set; }
        public short? SheetFlag { get; set; }
        [StringLength(200)]
        public string RemarkNew { get; set; }
        [StringLength(1)]
        public string Mode { get; set; }
        [StringLength(15)]
        public string FactStore { get; set; }
        [StringLength(1)]
        public string DealFlag { get; set; }
        [StringLength(20)]
        public string TranOutID { get; set; }
        [StringLength(20)]
        public string TranOutItem { get; set; }
        [StringLength(13)]
        public string RequireID { get; set; }
        [StringLength(100)]
        public string GoodName { get; set; }
        [StringLength(20)]
        public string ClientGoodID { get; set; }
        [StringLength(1)]
        public string IsCheck { get; set; }
        [StringLength(8)]
        public string CheckDate { get; set; }
        [StringLength(1)]
        public string SortMode { get; set; }
        [StringLength(1)]
        public string AccountFlag { get; set; }
        public double? xRemarkA { get; set; }
        [StringLength(50)]
        public string xRemarkB { get; set; }
        [StringLength(50)]
        public string xRemarkC { get; set; }
    }
}