// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    public partial class TransferBarList
    {
        [Key]
        public int RowID { get; set; }
        [Required]
        [StringLength(50)]
        public string Bar { get; set; }
        [Required]
        [StringLength(15)]
        public string SerialID { get; set; }
        [Required]
        [StringLength(20)]
        public string GoodID { get; set; }
        [Required]
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [Required]
        [StringLength(6)]
        public string ChangePerson { get; set; }
    }
}