// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Keyless]
    public partial class TransTmp
    {
        [StringLength(30)]
        public string Bar { get; set; }
        [StringLength(15)]
        public string StoreID { get; set; }
        [StringLength(20)]
        public string GoodsID { get; set; }
        [StringLength(1)]
        public string SizeNo { get; set; }
        [StringLength(2)]
        public string Position { get; set; }
        public double? Qty { get; set; }
    }
}