// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    public partial class TsLineHelpField
    {
        /// <summary>
        /// 代號
        /// </summary>
        [Key]
        public Guid LineHelpID { get; set; }
        /// <summary>
        /// 項次
        /// </summary>
        [Key]
        public int Item { get; set; }
        /// <summary>
        /// 序號
        /// </summary>
        public int SortID { get; set; }
        /// <summary>
        /// 名稱
        /// </summary>
        [Required]
        [StringLength(200)]
        public string Name { get; set; }
        /// <summary>
        /// 欄位名稱
        /// </summary>
        [Required]
        [StringLength(20)]
        public string FieldName { get; set; }
        /// <summary>
        /// 欄位類型
        /// </summary>
        public int FieldType { get; set; }
        /// <summary>
        /// 格式類型
        /// </summary>
        public int FormatType { get; set; }
        [StringLength(500)]
        public string Remark { get; set; }

        [ForeignKey(nameof(LineHelpID))]
        [InverseProperty(nameof(TsLineHelpMain.TsLineHelpField))]
        public virtual TsLineHelpMain LineHelp { get; set; }
    }
}