// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    /// <summary>
    /// LineHelp主表
    /// </summary>
    public partial class TsLineHelpMain
    {
        public TsLineHelpMain()
        {
            TsLineHelpField = new HashSet<TsLineHelpField>();
            TsReportCondition = new HashSet<TsReportCondition>();
        }

        /// <summary>
        /// 代號
        /// </summary>
        [Key]
        public Guid LineHelpID { get; set; }
        /// <summary>
        /// 名稱
        /// </summary>
        [Required]
        [StringLength(200)]
        public string LineHelpName { get; set; }
        /// <summary>
        /// 標題
        /// </summary>
        [Required]
        [StringLength(200)]
        public string Caption { get; set; }
        /// <summary>
        /// SQL語句
        /// </summary>
        [Required]
        [StringLength(4000)]
        public string SQL { get; set; }
        [Required]
        [StringLength(200)]
        public string DBObjectName { get; set; }
        [Required]
        [StringLength(255)]
        public string ReturnField { get; set; }
        [Required]
        [StringLength(255)]
        public string FilterFieldFullName { get; set; }
        [StringLength(255)]
        public string IDFieldName { get; set; }
        [StringLength(255)]
        public string CodeFieldName { get; set; }
        [StringLength(255)]
        public string NameFieldName { get; set; }
        [Column(TypeName = "image")]
        public byte[] Layout { get; set; }
        public int Width { get; set; }
        public int Height { get; set; }
        [StringLength(500)]
        public string Remark { get; set; }

        [InverseProperty("LineHelp")]
        public virtual ICollection<TsLineHelpField> TsLineHelpField { get; set; }
        [InverseProperty("LineHelp")]
        public virtual ICollection<TsReportCondition> TsReportCondition { get; set; }
    }
}