// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    public partial class TsReportConditionSection
    {
        /// <summary>
        /// 報表代號
        /// </summary>
        [Key]
        public Guid ReportID { get; set; }
        /// <summary>
        /// 項次
        /// </summary>
        [Key]
        public int Item { get; set; }
        /// <summary>
        /// 條件分組
        /// </summary>
        [Key]
        [StringLength(200)]
        public string WhereSection { get; set; }
        /// <summary>
        /// 序號
        /// </summary>
        public int SortID { get; set; }
        /// <summary>
        /// 欄位名稱
        /// </summary>
        [Required]
        [StringLength(200)]
        public string WhereFieldName { get; set; }
        [StringLength(500)]
        public string Remark { get; set; }

        [ForeignKey(nameof(ReportID))]
        [InverseProperty(nameof(TsReportMain.TsReportConditionSection))]
        public virtual TsReportMain Report { get; set; }
        [ForeignKey("ReportID,Item")]
        [InverseProperty("TsReportConditionSection")]
        public virtual TsReportCondition TsReportCondition { get; set; }
    }
}