// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    /// <summary>
    /// 報表條件項目
    /// </summary>
    public partial class TsReportCondition
    {
        public TsReportCondition()
        {
            TsReportConditionSection = new HashSet<TsReportConditionSection>();
        }

        /// <summary>
        /// 報表代號
        /// </summary>
        [Key]
        public Guid ReportID { get; set; }
        /// <summary>
        /// 項次
        /// </summary>
        [Key]
        public int Item { get; set; }
        /// <summary>
        /// 序號
        /// </summary>
        public int SortID { get; set; }
        /// <summary>
        /// 名稱
        /// </summary>
        [Required]
        [StringLength(200)]
        public string Name { get; set; }
        /// <summary>
        /// 欄位類型
        /// </summary>
        public int FieldType { get; set; }
        /// <summary>
        /// 允許錄入條件
        /// </summary>
        [Required]
        public bool? EnableCondition { get; set; }
        /// <summary>
        /// 鎖定條件類型
        /// </summary>
        public bool LockConditionType { get; set; }
        /// <summary>
        /// 默認條件類型
        /// </summary>
        public int ConditionType { get; set; }
        /// <summary>
        /// 默認條件值1
        /// </summary>
        [StringLength(200)]
        public string DefaultValue1 { get; set; }
        /// <summary>
        /// 默認條件值2
        /// </summary>
        [StringLength(200)]
        public string DefaultValue2 { get; set; }
        public Guid? LineHelpID { get; set; }
        /// <summary>
        /// 允許錄入條件
        /// </summary>
        public bool AllowMultiSelect { get; set; }
        [Required]
        public bool? CanMultiEntry { get; set; }
        [Required]
        public bool? Visible { get; set; }
        public bool MustEntry { get; set; }
        [StringLength(500)]
        public string Remark { get; set; }

        [ForeignKey(nameof(LineHelpID))]
        [InverseProperty(nameof(TsLineHelpMain.TsReportCondition))]
        public virtual TsLineHelpMain LineHelp { get; set; }
        [ForeignKey(nameof(ReportID))]
        [InverseProperty(nameof(TsReportMain.TsReportCondition))]
        public virtual TsReportMain Report { get; set; }
        [InverseProperty("TsReportCondition")]
        public virtual ICollection<TsReportConditionSection> TsReportConditionSection { get; set; }
    }
}