// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    /// <summary>
    /// 報表結果項目
    /// </summary>
    public partial class TsReportResult
    {
        /// <summary>
        /// 報表代號
        /// </summary>
        [Key]
        public Guid ReportID { get; set; }
        /// <summary>
        /// 項次
        /// </summary>
        [Key]
        public int Item { get; set; }
        /// <summary>
        /// 序號
        /// </summary>
        public int SortID { get; set; }
        /// <summary>
        /// 名稱
        /// </summary>
        [Required]
        [StringLength(200)]
        public string Name { get; set; }
        /// <summary>
        /// 欄位名稱
        /// </summary>
        [Required]
        [StringLength(200)]
        public string FieldName { get; set; }
        /// <summary>
        /// 欄位類型
        /// </summary>
        public int FieldType { get; set; }
        /// <summary>
        /// 格式類型
        /// </summary>
        public int FormatType { get; set; }
        /// <summary>
        /// 權限類型
        /// </summary>
        public int RightType { get; set; }
        /// <summary>
        /// 可顯示區域
        /// </summary>
        public int AllowShowArea { get; set; }
        /// <summary>
        /// 顯示區域
        /// </summary>
        public int ShowArea { get; set; }
        /// <summary>
        /// 合計類型
        /// </summary>
        public int SummaryType { get; set; }
        /// <summary>
        /// 計算欄位SQL字串
        /// </summary>
        [Required]
        [StringLength(2000)]
        public string SQLFormula { get; set; }
        /// <summary>
        /// 計算欄位網格公式
        /// </summary>
        [Required]
        [StringLength(500)]
        public string GridFormula { get; set; }
        [Required]
        public bool? Visible { get; set; }
        [Required]
        public bool? ShowTotal { get; set; }
        [StringLength(500)]
        public string Remark { get; set; }
        [Required]
        [StringLength(200)]
        public string GroupName { get; set; }

        [ForeignKey(nameof(ReportID))]
        [InverseProperty(nameof(TsReportMain.TsReportResult))]
        public virtual TsReportMain Report { get; set; }
    }
}