// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    /// <summary>
    /// 報表中心
    /// </summary>
    public partial class TsReportMain
    {
        public TsReportMain()
        {
            InverseParent = new HashSet<TsReportMain>();
            TsReportCondition = new HashSet<TsReportCondition>();
            TsReportConditionSection = new HashSet<TsReportConditionSection>();
            TsReportResult = new HashSet<TsReportResult>();
            TsReportScheme = new HashSet<TsReportScheme>();
        }

        /// <summary>
        /// 報表代號
        /// </summary>
        [Key]
        public Guid ReportID { get; set; }
        /// <summary>
        /// 序號
        /// </summary>
        public int SortID { get; set; }
        /// <summary>
        /// 報表名稱
        /// </summary>
        [Required]
        [StringLength(200)]
        public string ReportName { get; set; }
        [Required]
        [StringLength(200)]
        public string DBObjectName { get; set; }
        /// <summary>
        /// 類型
        /// </summary>
        public int XType { get; set; }
        /// <summary>
        /// 父編號
        /// </summary>
        public Guid? ParentID { get; set; }
        /// <summary>
        /// 說明
        /// </summary>
        [Required]
        [StringLength(1000)]
        public string Summary { get; set; }
        /// <summary>
        /// 菜單分組
        /// </summary>
        public bool BeginGroup { get; set; }
        /// <summary>
        /// 大量數據優化
        /// </summary>
        [Required]
        public bool? BigDataWise { get; set; }
        /// <summary>
        /// 區軸網格分析
        /// </summary>
        [Required]
        public bool? IsPivotGrid { get; set; }
        public bool IsNegativeMode { get; set; }

        [ForeignKey(nameof(ParentID))]
        [InverseProperty(nameof(TsReportMain.InverseParent))]
        public virtual TsReportMain Parent { get; set; }
        [InverseProperty(nameof(TsReportMain.Parent))]
        public virtual ICollection<TsReportMain> InverseParent { get; set; }
        [InverseProperty("Report")]
        public virtual ICollection<TsReportCondition> TsReportCondition { get; set; }
        [InverseProperty("Report")]
        public virtual ICollection<TsReportConditionSection> TsReportConditionSection { get; set; }
        [InverseProperty("Report")]
        public virtual ICollection<TsReportResult> TsReportResult { get; set; }
        [InverseProperty("Report")]
        public virtual ICollection<TsReportScheme> TsReportScheme { get; set; }
    }
}