// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Keyless]
    public partial class TsReportSchemeTmp
    {
        public Guid SchemeID { get; set; }
        public Guid ReportID { get; set; }
        public int SortID { get; set; }
        [Required]
        [StringLength(200)]
        public string ReportName { get; set; }
        public bool IsDefault { get; set; }
        public bool ViewType { get; set; }
        [Column(TypeName = "image")]
        public byte[] PivotLayout { get; set; }
        [Column(TypeName = "image")]
        public byte[] GridLayout { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime ChangeDate { get; set; }
        [StringLength(50)]
        public string UserCode { get; set; }
        [StringLength(500)]
        public string Remark { get; set; }
    }
}