// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    /// <summary>
    /// 用戶權限
    /// </summary>
    public partial class TsUserRight
    {
        /// <summary>
        /// 父功能編號
        /// </summary>
        public Guid? ParentFunctionID { get; set; }
        /// <summary>
        /// 用戶編號
        /// </summary>
        [Key]
        public Guid UserID { get; set; }
        /// <summary>
        /// 功能編號
        /// </summary>
        [Key]
        public Guid FunctionID { get; set; }
        /// <summary>
        /// 權限
        /// </summary>
        public int Rights { get; set; }
        /// <summary>
        /// 异動日期
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime ChangeDate { get; set; }
        /// <summary>
        /// 异動人員
        /// </summary>
        public Guid? ChangeUserID { get; set; }

        [ForeignKey(nameof(UserID))]
        [InverseProperty(nameof(TsUsers.TsUserRight))]
        public virtual TsUsers User { get; set; }
    }
}