// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Index(nameof(UserID), Name = "User_ID")]
    public partial class Users
    {
        [Key]
        [StringLength(10)]
        public string UserID { get; set; }
        [StringLength(4)]
        public string UserNumber { get; set; }
        [StringLength(10)]
        public string UserName { get; set; }
        [StringLength(10)]
        public string Password { get; set; }
        [StringLength(50)]
        public string Description { get; set; }
        [StringLength(30)]
        public string GroupName { get; set; }
    }
}