// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    public partial class UserGroup
    {
        [Key]
        [StringLength(30)]
        public string Group_Name { get; set; }
        [StringLength(50)]
        public string Description { get; set; }
    }
}