// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    public partial class WayBill
    {
        [Key]
        [StringLength(13)]
        public string WayBillID { get; set; }
        [StringLength(8)]
        public string WayBillDate { get; set; }
        [StringLength(4)]
        public string WayBillPerson { get; set; }
        [StringLength(1)]
        public string Area { get; set; }
        [StringLength(1)]
        public string No { get; set; }
        [StringLength(13)]
        public string OddNumID { get; set; }
        public double? OddNumTot { get; set; }
        public double? BoxNum { get; set; }
        public double? TakeBoxNum { get; set; }
        public double? NoTakeBoxNum { get; set; }
        public double? TotMoney { get; set; }
        [Key]
        [StringLength(4)]
        public string Item { get; set; }
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [StringLength(4)]
        public string ChangePerson { get; set; }
    }
}