// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Keyless]
    public partial class WayRemark
    {
        [StringLength(1)]
        public string Remark01 { get; set; }
        [StringLength(50)]
        public string Remark02 { get; set; }
        [StringLength(50)]
        public string Remark03 { get; set; }
        [StringLength(50)]
        public string Remark04 { get; set; }
        [StringLength(50)]
        public string Remark05 { get; set; }
        [StringLength(50)]
        public string Remark06 { get; set; }
        [StringLength(50)]
        public string Remark07 { get; set; }
        [StringLength(50)]
        public string Remark08 { get; set; }
        [StringLength(50)]
        public string Remark09 { get; set; }
        [StringLength(50)]
        public string Remark10 { get; set; }
        [StringLength(50)]
        public string Remark11 { get; set; }
        [StringLength(50)]
        public string Remark12 { get; set; }
        [StringLength(50)]
        public string Remark13 { get; set; }
        [StringLength(50)]
        public string Remark14 { get; set; }
        [StringLength(50)]
        public string Remark15 { get; set; }
        [StringLength(50)]
        public string Remark16 { get; set; }
        [StringLength(50)]
        public string Remark17 { get; set; }
        [StringLength(50)]
        public string Remark18 { get; set; }
        [StringLength(50)]
        public string Remark19 { get; set; }
        [StringLength(50)]
        public string Remark20 { get; set; }
        [StringLength(50)]
        public string Remark21 { get; set; }
        [StringLength(50)]
        public string Remark22 { get; set; }
        [StringLength(50)]
        public string Remark23 { get; set; }
        [StringLength(50)]
        public string Remark24 { get; set; }
        [StringLength(50)]
        public string Remark25 { get; set; }
        [StringLength(1)]
        public string API_91_OrderFlag { get; set; }
        [StringLength(1)]
        public string API_91_ShipFlag { get; set; }
        [StringLength(1)]
        public string TotFlag { get; set; }
        [StringLength(1)]
        public string TotSortFlag { get; set; }
        [StringLength(1)]
        public string DetFlag { get; set; }
        [StringLength(50)]
        public string Remark26 { get; set; }
        [StringLength(1)]
        public string KTJSort { get; set; }
    }
}