// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    public partial class Web_Ship
    {
        [Key]
        [StringLength(200)]
        public string OrderID { get; set; }
        [Key]
        public byte Item { get; set; }
        [StringLength(200)]
        public string CollectionID { get; set; }
        public int? PaymentID { get; set; }
        [StringLength(8)]
        public string MemberID { get; set; }
        [StringLength(200)]
        public string ReceiverName { get; set; }
        [StringLength(2000)]
        public string Address { get; set; }
        [StringLength(200)]
        public string PhoneNo { get; set; }
        [StringLength(200)]
        public string TelNo { get; set; }
        [StringLength(200)]
        public string EMail { get; set; }
        [StringLength(1)]
        public string InvoiceType { get; set; }
        [StringLength(50)]
        public string InvoiceTitle { get; set; }
        [StringLength(8)]
        public string UnifiedNum { get; set; }
        [StringLength(20)]
        public string GoodID { get; set; }
        [StringLength(2)]
        public string SizeNo { get; set; }
        public int? Num01 { get; set; }
        public int? Num02 { get; set; }
        public int? Num03 { get; set; }
        public int? Num04 { get; set; }
        public int? Num05 { get; set; }
        public int? Num06 { get; set; }
        public int? Num07 { get; set; }
        public int? Num08 { get; set; }
        public int? Num09 { get; set; }
        public int? Num10 { get; set; }
        public int? Num11 { get; set; }
        public int? Num12 { get; set; }
        public int? Num13 { get; set; }
        public int? Num14 { get; set; }
        public int? Num15 { get; set; }
        public int? Num16 { get; set; }
        public int? Num17 { get; set; }
        public int? Total { get; set; }
        public int? Amount { get; set; }
        public int? Carriage { get; set; }
        public int? DeliveryCharge { get; set; }
        public int? PointCash { get; set; }
        public int? ProjectCash { get; set; }
        [StringLength(50)]
        public string SiteUrl { get; set; }
        [StringLength(20)]
        public string SellID { get; set; }
        [StringLength(3)]
        public string SellItem { get; set; }
        [StringLength(30)]
        public string WayKind { get; set; }
        [StringLength(500)]
        public string WayGoid { get; set; }
        [StringLength(20)]
        public string WayStoreID { get; set; }
        [StringLength(50)]
        public string WayStoreName { get; set; }
        [StringLength(500)]
        public string WayID { get; set; }
        [StringLength(10)]
        public string WayStoreInDate { get; set; }
        [StringLength(10)]
        public string WayStoreOutDate { get; set; }
        [StringLength(1000)]
        public string FOID { get; set; }
        [StringLength(50)]
        public string Fname { get; set; }
        [StringLength(25)]
        public string Ftel { get; set; }
        [StringLength(30)]
        public string WayOrderID { get; set; }
        [StringLength(20)]
        public string WebGoodID { get; set; }
        [StringLength(100)]
        public string WebGoodName { get; set; }
        [StringLength(20)]
        public string WebSellID { get; set; }
        [StringLength(20)]
        public string CGoodID { get; set; }
        [StringLength(20)]
        public string CGoodName { get; set; }
        [StringLength(50)]
        public string DetailRemark { get; set; }
        public double? CollectionMey { get; set; }
        public double? RptTotNum { get; set; }
        public double? RptShipNum { get; set; }
        public double? RptDetNum { get; set; }
        [StringLength(20)]
        public string BPUPListID { get; set; }
        public long? PlatformID { get; set; }
        [StringLength(1)]
        public string SellMode { get; set; }
        [StringLength(8)]
        public string YaEDate { get; set; }
        [StringLength(20)]
        public string YaSID { get; set; }
        [StringLength(20)]
        public string YaDID { get; set; }
        public double? WayMoney { get; set; }
        [StringLength(200)]
        public string MemTel03 { get; set; }
        [StringLength(200)]
        public string ZipID01 { get; set; }
        [StringLength(10)]
        public string HCTID { get; set; }
        [StringLength(1)]
        public string ShipMode { get; set; }
        [StringLength(100)]
        public string TransactionId { get; set; }
        [StringLength(50)]
        public string GroupID { get; set; }
        [StringLength(2000)]
        public string Remark { get; set; }
        [StringLength(1)]
        public string SelldingFlag { get; set; }
        [StringLength(20)]
        public string DingSellID { get; set; }
        [StringLength(20)]
        public string TransferID { get; set; }
        [StringLength(8)]
        public string ClientID { get; set; }
    }
}