// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    public partial class Web_BatchPickStore
    {
        [Key]
        public long PlatformID { get; set; }
        [Key]
        [StringLength(8)]
        public string Store { get; set; }
        public long? StoreOrder { get; set; }
        [StringLength(200)]
        public string CollectionID { get; set; }
        [StringLength(1)]
        public string SelldingFlag { get; set; }
        [StringLength(1)]
        public string OutStoreFlag { get; set; }
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [StringLength(8)]
        public string ChangePerson { get; set; }
    }
}