// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    public partial class Web_WayTrans
    {
        [Key]
        public long PlatformID { get; set; }
        [Key]
        [StringLength(20)]
        public string TransactionId { get; set; }
        [Key]
        [StringLength(20)]
        public string OrderID { get; set; }
        [StringLength(30)]
        public string WayID { get; set; }
        [StringLength(50)]
        public string WayStoreID { get; set; }
        [StringLength(50)]
        public string WayStoreName { get; set; }
        [StringLength(50)]
        public string WayGoID { get; set; }
        [StringLength(50)]
        public string Fname { get; set; }
        [StringLength(50)]
        public string SiteUrl { get; set; }
        [StringLength(25)]
        public string Ftel { get; set; }
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [StringLength(8)]
        public string ChangePerson { get; set; }
    }
}