// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Keyless]
    public partial class WebDelLog
    {
        [Required]
        [StringLength(200)]
        public string OrderID { get; set; }
        public byte Item { get; set; }
        [StringLength(20)]
        public string ChangeDateTime { get; set; }
        [StringLength(8)]
        public string ChangeDate { get; set; }
        [StringLength(8)]
        public string ChangePerson { get; set; }
    }
}