// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Keyless]
    public partial class WebToolsGroupProgram
    {
        [Required]
        [StringLength(30)]
        public string Group_Name { get; set; }
        [Required]
        [StringLength(30)]
        public string Program_Name { get; set; }
        [StringLength(1)]
        public string Insert_Flag { get; set; }
        [StringLength(1)]
        public string View_Flag { get; set; }
        [StringLength(1)]
        public string Edit_Flag { get; set; }
        [StringLength(1)]
        public string Delete_Flag { get; set; }
        [StringLength(1)]
        public string Print_Flag { get; set; }
        [StringLength(1)]
        public string Money_Flag { get; set; }
        [StringLength(1)]
        public string Cost_Flag { get; set; }
    }
}