// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Keyless]
    public partial class YahooSell
    {
        [Required]
        [StringLength(20)]
        public string SellID { get; set; }
        [Required]
        [StringLength(20)]
        public string YaID { get; set; }
        [StringLength(8)]
        public string YaEDate { get; set; }
        [StringLength(20)]
        public string WayID { get; set; }
        [StringLength(20)]
        public string YaSID { get; set; }
        [StringLength(20)]
        public string YaDID { get; set; }
        public double? WayMoney { get; set; }
        [StringLength(1)]
        public string SellMode { get; set; }
        [StringLength(20)]
        public string MemName { get; set; }
        [StringLength(20)]
        public string MemTel01 { get; set; }
        [StringLength(20)]
        public string MemTel02 { get; set; }
        [StringLength(20)]
        public string MemTel03 { get; set; }
        [StringLength(20)]
        public string ZipID01 { get; set; }
        [StringLength(160)]
        public string MemAddr { get; set; }
        [StringLength(1)]
        public string SortID { get; set; }
        [StringLength(20)]
        public string SellReturnsID { get; set; }
        [StringLength(200)]
        public string Transport { get; set; }
    }
}