// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Table("shopping_cart", Schema = "POVWeb")]
    public partial class shopping_cart
    {
        [Key]
        [StringLength(20)]
        public string SellBranch { get; set; }
        [Required]
        [StringLength(20)]
        public string SellStore { get; set; }
        [Key]
        [StringLength(1)]
        public string terminalID { get; set; }
        [Key]
        [StringLength(3)]
        public string Item { get; set; }
        [StringLength(20)]
        public string GoodID { get; set; }
        [StringLength(2)]
        public string SizeNo { get; set; }
        [StringLength(4)]
        public string SizeName { get; set; }
        public short? SizePosition { get; set; }
        public double? SellPrice { get; set; }
        public double? AdvicePrice { get; set; }
        public double? TotalSellNum { get; set; }
        public double? SellDiscount { get; set; }
        [StringLength(20)]
        public string MemberID { get; set; }
        public double? SellCash { get; set; }
        [StringLength(20)]
        public string PurchaseID { get; set; }
        [StringLength(3)]
        public string PurchaseItem { get; set; }
        [StringLength(1)]
        public string SellMode { get; set; }
        [StringLength(8)]
        public string SellPerson { get; set; }
        [StringLength(20)]
        public string ZuHeID { get; set; }
        [StringLength(50)]
        public string ZHBatchID { get; set; }
        [StringLength(3)]
        public string ZHBatchItem { get; set; }
        public double? ShouldSellprice { get; set; }
        [StringLength(20)]
        public string BackSellID { get; set; }
        [StringLength(3)]
        public string BackSellItem { get; set; }
        [StringLength(20)]
        public string BackEInvID { get; set; }
        public string FrontEndMemo { get; set; }
        public DateTime? CreateDTM { get; set; }
        public DateTime? ModifyDTM { get; set; }
    }
}