// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POVWebDomain.Models.DB.POVWeb
{
    [Table("tmpHello", Schema = "POVWeb")]
    public partial class tmpHello
    {
        [Key]
        public int id { get; set; }
        public string memo { get; set; }
        public DateTime? createDTM { get; set; }
    }
}