// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CityAdminDomain.Models.DB.CityAdmin
{
    [Table("ACL", Schema = "SSO")]
    public partial class ACL
    {
        public long users_id { get; set; }
        [Required]
        [StringLength(32)]
        public string action { get; set; }
        [Required]
        [StringLength(32)]
        public string subject { get; set; }
        public DateTime? updateDTM { get; set; }
        public DateTime? createDTM { get; set; }

        [ForeignKey(nameof(users_id))]
        public virtual Users users_ { get; set; }
    }
}