// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CityAdminDomain.Models.DB.CityAdmin
{
    [Table("Users", Schema = "SSO")]
    public partial class Users
    {
        [Key]
        public long id { get; set; }
        [Required]
        [StringLength(64)]
        public string company_id { get; set; }
        [Required]
        [StringLength(64)]
        public string user_name { get; set; }
        [StringLength(64)]
        public string name { get; set; }
        [StringLength(128)]
        public string email { get; set; }
        [StringLength(16)]
        public string role { get; set; }
        /// <summary>
        /// 帳號狀態。0：關閉；1：暫停；10：啟用(正常)
        /// </summary>
        public byte? status { get; set; }
        public DateTime updateDTM { get; set; }
        public DateTime createDTM { get; set; }
        [StringLength(256)]
        public string role_detail { get; set; }
        [StringLength(20)]
        public string store_id { get; set; }
        [StringLength(2)]
        public string terminal_id { get; set; }

        [StringLength(20)]
        public string macAddress { get; set; }

        [Column("IsFront", TypeName = "bit")]
        public bool? IsFront { get; set; }
    }
}